### ISSUE TITLE
Request object different than the xml (soap)

### ISSUE THREAD

**Issue by amaccis** [phpro/soap-client#104]
Hi guys.
I've an object (this is an excerpt)

```
[items:\RQtype:private] => Array
    (
        [0] => \Items Object
            (
                [itemtype:\Items:private] => TEST
                [itemcode:\Items:private] => TS
                [type:\Items:private] => Type Object
                    (
                        [typecode:\type:private] => A
                        [number:\type:private] => 2
                    )
                [foo:\Items:private] => Foo Object
                    (
                        [index:\Foo:private] => 1
                    )
            )
    )
```

and after the clientBuilder receives it, the xml produced is

```
<ns1:items xsi:type="ns1:items">
    <ns1:itemtype>TEST</ns1:itemtype>
    <ns1:itemcode>TS</ns1:itemcode>
    <ns1:type>
        <ns1:typecode>A</ns1:typecode>
        <ns1:number>2</ns1:number>
    </ns1:type>
</ns1:items>
```

As you can see Foo is missing.
I double checked the entities and they seem OK and I'm running out of ideas.
Does it ring any bells?
Thanks!
A.

**Comment by veewee** [comment]
Hi @amaccis,

It's always handy if you could provide as much information as possible about your setup. At this point I guess that the `Foo` type isn't available inside the `Items` type in the wsdl. Which means that ext-soap isn't able to add it to the soap message (which makes sense).

Can you provide a WSDL or the generated class for the Items object?
Is the `foo` property available in the WSDL or is this some dynamic property?

**Comment by amaccis** [comment]
Hi @veewee .
I got what was wrong. 
I'm using two endopoints that share a few object names and when I created the entities a few of them resulted merged. Anyway, it was totally my fault, soap-client worked fine!  
Thank you very much!
A.

**Comment by veewee** [comment]
No problem!
