### ISSUE TITLE
Can't override default type converters

### ISSUE THREAD

**Issue by csiszarattila** [phpro/soap-client#106]
Hi,
My problem is that I can not override the default type converters (datetime, date etc.) with a custom one because ClientBuilder::addTypeConverter() checking first that a converter already exists, and the default converters already added during ClientBuilder __constuct().

Solution: I think adding the default type converters on the build() method would solve this issue.

**Comment by csiszarattila** [comment]
@veewee  Do you mind if I started working on this and make a pull request?

**Comment by veewee** [comment]
Hi @csiszarattila,

Thanks for reporting! Feel free to suggest something that does work for you.
Maybe it's easier to just make it possible to overwrite types?
