### ISSUE TITLE
Filter logged params?

### ISSUE THREAD

**Issue by GaryJones** [phpro/soap-client#108]
I pass an instance of Monolog to `$clientBuilder->withLogging()`, and the Logging plugin all works fine.

However, the API I'm using requires username and password as two of the standard params, and without them, the API doesn't respond. This results in log entries like (formatted for readability):

```
[2017-12-12 15:47:16] [SiteReference] General.INFO: [phpro/soap-client] request: call "DemoSetup" with params My\PackageName\SoapTypes\DemoSetup Object (
    [adminUsername:protected] => myUsername
    [adminPassword:protected] => myPassword
    [firstName:protected] => Gary
    [lastName:protected] => Jones
    [email:protected] => me@example.com
    [clientIp:protected] => 123.123.123.321
)  [] []
```

The issue here is that the API's password (and username) are now recorded in the log files.

Is there a way to filter the params when the [request logging is done](https://github.com/phpro/soap-client/blob/c5c2d6e4fb77aef3ccec261fe2dcde55bac9c8ac/src/Phpro/SoapClient/Plugin/LogPlugin.php#L39-L43) so that we can remove, or change the password value to `(redacted)`?

**Comment by veewee** [comment]
You can do this by creating a custom monolog formatter / processor. More info: https://github.com/Seldaek/monolog/blob/master/doc/02-handlers-formatters-processors.md

If you think the formatter or processor could be made reusable, I'dd accept a PR for that.

**Comment by GaryJones** [comment]
Thank you for the pointer - that may well be enough for what we need.
