### ISSUE TITLE
New subscriber (e.g. logger) added for each client built by ClientBuilder

### ISSUE THREAD

**Issue by podarcis** [phpro/soap-client#112]
The problem: Same log message is logged multiple times.

Situation: We are using several services with different WSDLs. For each service we created a seperate client.

As far as I understand the example on the "Basic Usage" page, for the instantiation of a specific client a ClientFactory is needed, which in turn is fed into the ClientBuilder. So for **each** our clients we have
```
$clientFactory = new ClientFactory(YourClient::class);
$clientBuilder = new ClientBuilder($clientFactory, $wsdl, $soapOptions);
$clientBuilder->withLogger($container->get('logger') /* always the same logger-instance */);
// ...
$client = $clientBuilder->build();
```
Unfortunately, the log messages from each client is logged multiple times (number of clients).

When I look into https://github.com/phpro/soap-client/blob/v0.5.3/src/Phpro/SoapClient/ClientBuilder.php#L221 , a new instance of a LogPlugin (Subscriber) is added.

Am I using the library the wrong way or might this be a bug? As a workaround for now I specify `withLogger()` only for the first client.

**Comment by veewee** [comment]
Hi @podarcis,

You are probably sharing the same EventDispatcher as well?
The logger plugin is actually an event listener which you are registering 5 times.

So one solution is not to inject the event dispatcher.
If you do want to share the event dispatcher, it's probably better just to register the logger plugin directly to the dispatcher in this case. (So don't use the `withLogger()` method.)

Something like this:

```php
$dispatcher->addSubscriber(new LogPlugin($logger));
```

**Comment by podarcis** [comment]
Hi @veewee,

Thank you very much for your detailled answer!

You are right, in my code the EventDispatcher is shared among the clients. I solved this issue by using for second suggestion and registering the LogPlugin as a subscriber once in the dispatcher.

I wonder how the documentation could be improved to make that clear...?

Thanks again!
