### ISSUE TITLE
Generated getResult() method is incompatible with ResultProviderInterface parent method due to missing return type declaration

### ISSUE THREAD

**Issue by GaryJones** [phpro/soap-client#113]
The [ResultProviderAssembler](https://github.com/phpro/soap-client/blob/524c5c2e7e914e421671f3cb30fe5a74b04b1b37/docs/code-generation/assemblers.md#resultproviderassembler) generates classes with a `getResult()` method.

Here's a part of my WSDL:

```xml
<s:element name="CalcRatesResponse">
    <s:complexType>
        <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="CalcRatesResult" type="tns:CalcRatesResult" />
        </s:sequence>
    </s:complexType>
</s:element>
```

Here's the relevant rule in my config file:

```php
    ->addRule(new Rules\TypenameMatchesRule(
        new Rules\AssembleRule(new ResultProviderAssembler()),
        '/Response$/'
     ))
```

Here's one of my generated classes:

```php
<?php

namespace GAA\CorpManagerApi\SoapTypes;

use Phpro\SoapClient\Type\ResultProviderInterface;
use Phpro\SoapClient\Type\ResultInterface;

class CalcRatesResponse implements ResultProviderInterface
{

    /**
     * @var CalcRatesResult
     */
    private $CalcRatesResult;

    /**
     * @return CalcRatesResult|ResultInterface
     */
    public function getResult()
    {
        return $this->CalcRatesResult;
    }
}
```

However, the [`getResult()` method](https://github.com/phpro/soap-client/blob/bfa61a1aa42f2b40e921e9fc756ade28b8432063/src/Phpro/SoapClient/Type/ResultProviderInterface.php#L18) in the `ResultProviderInterface` has a return type declaration (added via #80), which means the generated method is an incompatible signature, causing a fatal error.

```php
    /**
     * @return ResultInterface
     */
    public function getResult(): ResultInterface;
```

The [method generation code](https://github.com/phpro/soap-client/blob/bfa61a1aa42f2b40e921e9fc756ade28b8432063/src/Phpro/SoapClient/CodeGenerator/Assembler/ResultProviderAssembler.php#L87-L102) doesn't appear to have anything suggesting that a return type declaration should be included.

Zend-code does have the [support](https://github.com/zendframework/zend-code/blob/6b1059db5b368db769e4392c6cb6cc139e56640d/src/Generator/MethodGenerator.php#L195) of adding a `returntype` when generating the method from an array.

**Comment by veewee** [comment]
Hi @GaryJones,

Thanks for reporting. 
That is indeed a bug that needs to be fixed.

**Comment by GaryJones** [comment]
```php
'returntype' => ResultInterface::class,
```
...may be to be a working fix, though not ideal since the FQN is added, which is redundant since the `use` statement at the top of the file is already present. Result is:

```php
    /**
     * @return CalcRatesResult|ResultInterface
     */
    public function getResult() : \Phpro\SoapClient\Type\ResultInterface
    {
        return $this->CalcRatesResult;
    }
```

If we try to use:
```php
'returntype' => Normalizer::getClassNameFromFQN(ResultInterface::class),
```

Then zend-code changes it to:

```php
    /**
     * @return CalcRatesResult|ResultInterface
     */
    public function getResult() : \ResultInterface
    {
        return $this->CalcRatesResult;
    }
```

which is wrong since `ResultInterface` is not in the global scope.

I'm not familiar enough / not dived in further to see if the ideal is possible:

```php
   /**
     * @return CalcRatesResult|ResultInterface
     */
    public function getResult() : ResultInterface
    {
        return $this->CalcRatesResult;
    }
```

**Comment by veewee** [comment]
Hi @GaryJones,

That is a known issue in zend-code that isn't going to be fixed. I suggest to use the FQCN and run a tool like php-cs-fixer on it after the code is generated.

More info at:

- https://github.com/zendframework/zend-code/issues/76
- https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/3276
