### ISSUE TITLE
Remove duplicated "overwrite or patch" logic in console commands

### ISSUE THREAD

**Issue by veewee** [phpro/soap-client#114]
Currently the logic for overwriting or patching a file is duplicated in the console commands.
Suggested solution:

- [ ] Add CLI option 'filemode' with options ['patch', 'override']. Make sure to mark 'patch' as default.
- [ ] Remove old option --overwrite  or make it force pathmode=override
- [ ] Remove all interactive questions.
- [ ] Drop backup logic. We all use version control, so there is no need to create .backup files
- [ ] Make sure the code generation invocation is placed inside one private method inside the command
- [ ] Optionally: make it possible to configure the filemode inside the CodeGeneration config file.
- [ ] Make sure the generators work in a consistent way (code should be generated by assemblers so that all code generation is customizable)
- [ ] Add documentation 
- [ ] Profit!

**Comment by janvernieuwe** [comment]
Guess we can close this, because we're going to remove all the patching all together.
