### ISSUE TITLE
Documentation needed for ClientMethodAssembler, ClientContext, ClientMethodContext

### ISSUE THREAD

**Issue by GaryJones** [phpro/soap-client#116]
I can see that [ClientMethodAssembler](https://github.com/phpro/soap-client/blob/5e0f5dd74a0a261db8c73cb669bdc376ad258d50/src/Phpro/SoapClient/CodeGenerator/Assembler/ClientMethodAssembler.php), [ClientContext](https://github.com/phpro/soap-client/blob/master/src/Phpro/SoapClient/CodeGenerator/Context/ClientContext.php) and [ClientMethodContext](https://github.com/phpro/soap-client/blob/5e0f5dd74a0a261db8c73cb669bdc376ad258d50/src/Phpro/SoapClient/CodeGenerator/Context/ClientMethodContext.php) classes exist, but there is no relevant documentation about them on the [Assemblers](https://github.com/phpro/soap-client/blob/5e0f5dd74a0a261db8c73cb669bdc376ad258d50/docs/code-generation/assemblers.md) docs or [Custom Rules](https://github.com/phpro/soap-client/blob/master/docs/code-generation/rules.md#creating-your-own-rule) docs.

**Comment by GaryJones** [comment]
My use case (which I've not figured out yet):

The `generate:client` gives me the following:

```php
public function demoSetup(\GAA\CorpManagerApi\SoapTypes\DemoSetup $DemoSetup) : \GAA\CorpManagerApi\SoapTypes\DemoSetupResponse
{
    return $this->call('DemoSetup', $DemoSetup);
}

public function demoSetupGain(\GAA\CorpManagerApi\SoapTypes\DemoSetupGain $DemoSetupGain) : \GAA\CorpManagerApi\SoapTypes\DemoSetupGainResponse
{
    return $this->call('DemoSetupGain', $DemoSetupGain);
}
```

But I need those two "demoSetup" methods to be consolidated as per my manually created (and working) client, and a new method (and ideally documentation for each method) added:

```php
    /**
     * Setup demo.
     *
     * @param RequestInterface $request
     *
     * @return DemoSetupResult|ResultInterface
     * @throws \Phpro\SoapClient\Exception\SoapException
     */
    public function demoSetup(RequestInterface $request)
    {
        return $this->call($this->getClassName($request), $request);
    }

    /**
     * Get the name of a class, without its namespace.
     *
     * @param RequestInterface $request
     *
     * @return string
     */
    private function getClassName(RequestInterface $request): string
    {
        $classname = \get_class($request);
        $pos = strrpos($classname, '\\');
        if ($pos) {
            return substr($classname, $pos + 1);
        }

        return $request;
    }
```
(That allows a consistent API to the Client, and it's the Request object passed to it which determines what is actually called).

An example of how to do that in the documentation would be wonderful!

**Comment by veewee** [comment]
The current implementation of the `generate:client` is mostly targeted to generate basic client code which can be customized afterwards. 

The case you mention probably won't be possible without writing some custom assemblers or rules.
At the moment you can assemble in `ClientMethodContext`. Currently the ClientContext doesn't trigger the rules to assemble. This is a rather easy enhancement.

Currently we don't have access to the soap function description since we are using the built-in [SoapClient::__getFunctions](http://php.net/manual/en/soapclient.getfunctions.php) method.

**Comment by GaryJones** [comment]
Here's what I've got which I think is working:

## Config:

```php
->addRule(new ClientMethodMatchesRule(
	new AssembleRule(new ConsolidatedClientMethodAssembler()),
	'/^(demoSetup|thirdPartySubscribe)$/'
))

->addRule(new ClientMethodMatchesRule(
	new AssembleRule(new RemovedClientMethodAssembler()),
	'/^(demoSetupGain|thirdPartySubscribeGain)$/'
))
```
----
## `ClientMethodMatchesRule`
See https://github.com/phpro/soap-client/issues/118#issuecomment-354496590

----
## `RemoveClientMethodAssembler`
```php
<?php

namespace GAA\CorpManagerApi\CodeGenerator\Assembler;

use Phpro\SoapClient\Client;
use Phpro\SoapClient\CodeGenerator\Assembler\AssemblerInterface;
use Phpro\SoapClient\CodeGenerator\Context\ContextInterface;
use Phpro\SoapClient\CodeGenerator\Context\ClientMethodContext;
use Phpro\SoapClient\Exception\AssemblerException;

/**
 * Class ClientMethodAssembler
 *
 * @package Phpro\SoapClient\CodeGenerator\Assembler
 */
class RemovedClientMethodAssembler implements AssemblerInterface
{
    /**
     * @param ContextInterface $context
     *
     * @return bool
     */
    public function canAssemble(ContextInterface $context): bool
    {
        return $context instanceof ClientMethodContext;
    }

    /**
     * @param ContextInterface|ClientMethodContext $context
     *
     * @return bool
     * @throws AssemblerException
     */
    public function assemble(ContextInterface $context): bool
    {
        $class = $context->getClass();
        $class->setExtendedClass(Client::class);
        $method = $context->getMethod();
        try {
            $class->removeMethod($method->getMethodName());
        } catch (\Exception $e) {
            throw AssemblerException::fromException($e);
        }

        return true;
    }
}
```
----
## `ConsolidatedClientMethodAssembler`

Similar to `RemovedClientMethod Assembler`, but with a different `assemble` method to produce the code I need for this project (little value in sharing here).

----
## Output

Generated client that has default method output (`getExchanges`) (albeit with extra documentation per #117), modified method (`demoSetup`) with interface-level param and return types, removed method (`demoSetupGain` - not shown, obviously), and an extra private method (`getClassName`).

![screenshot 2017-12-29 20 52 52](https://user-images.githubusercontent.com/88371/34447297-6215b2e8-ecda-11e7-8b45-ebd6ab4f7a59.png)
