### ISSUE TITLE
Add DocBlocks to output of generate:client

### ISSUE THREAD

**Issue by GaryJones** [phpro/soap-client#117]
The current output of the `generate:client` code has no documentation. Other than making it harder to follow, IDEs also complain:

![screenshot 2017-12-29 17 04 41](https://user-images.githubusercontent.com/88371/34442482-620dfbe0-ecba-11e7-82bd-9b08bc50ab5d.png)

When DocBlocks are added, with the right types for `@return`, then IDEs are happier (not only for this file, but for code that uses this Client):

![screenshot 2017-12-29 17 05 23](https://user-images.githubusercontent.com/88371/34442525-9d84ec42-ecba-11e7-9c34-7dcb3a06c975.png)

**Comment by veewee** [comment]
Adding the docblocks shouldn't be hard.

We currently don't have access to the SOAP function description since we are using the built-in [SoapClient::__getFunctions()](http://php.net/manual/en/soapclient.getfunctions.php) method to load the function information.  As you can see in the docs, there is no description being returned there. However, this might be possible once #65 is ready.

**Comment by GaryJones** [comment]
A starting point (though I'm sure it could be improved) for adding docs via `ClientMethodAssembler::assemble` and the `MethodGenerator::fromArray()` call:

```php
'docblock' => DocBlockGenerator::fromArray([
    'tags' => [
        [
            'name' => 'param',
            'description' => sprintf('\%s $%s', RequestInterface::class, 'request'),
        ],
        [
        	'name' => 'return',
            'description' => '\\' . ResultInterface::class . '|\\'.$method->getParameterNamespace().'\\'.$method->getReturnType(),
        ],
        [
        	'name' => 'throws',
            'description' => '\\' . SoapException::class,
        ],
    ]
]),
```

For me, this produces a method like:

![screenshot 2017-12-29 18 58 39](https://user-images.githubusercontent.com/88371/34445229-4ec84df0-ecca-11e7-96ea-bb0ab577eaec.png)

Which would be fine, except that the `@return` description is wrapped on the next line, and so isn't picked up.

Cutting the `return` description down to:

```php
'description' => '\\' . ResultInterface::class,
```
And we get a working version (happy IDE) of:

![screenshot 2017-12-29 19 01 21](https://user-images.githubusercontent.com/88371/34445287-ac169746-ecca-11e7-8b53-a3e00c53b144.png)

**Comment by veewee** [comment]
Feel free to create a PR in which we can discuss the code.
