### ISSUE TITLE
Generated Client method return types

### ISSUE THREAD

**Issue by GaryJones** [phpro/soap-client#121]
Here's the relevant bit of the WSDL:

```xml
<s:element name="GetReleaseNotes">
    <s:complexType>
        <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="x" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="y" type="s:string" />
        </s:sequence>
    </s:complexType>
</s:element>
<s:element name="GetReleaseNotesResponse">
    <s:complexType>
        <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="GetReleaseNotesResult" type="tns:GetReleaseNotesResult" />
        </s:sequence>
    </s:complexType>
</s:element>
<s:complexType name="GetReleaseNotesResult">
    <s:complexContent mixed="false">
        <s:extension base="tns:CorpWebResult">
            <s:sequence>
                <s:element minOccurs="0" maxOccurs="1" name="MajorVersions" type="tns:ArrayOfReleaseMajorVersion" />
            </s:sequence>
        </s:extension>
    </s:complexContent>
</s:complexType>
```

My understanding is, `GetReleaseNotesResponse` is a ResultProvider, and as such, I have the following Rule:

```php
->addRule(new TypenameMatchesRule(
    new AssembleRule(new ResultProviderAssembler()),
        '/Response$/'
))
```

This gives me a `GetReleaseNotesResponse` of:

```php
namespace GAA\CorpManagerApi\SoapTypes;

use Phpro\SoapClient\Type\ResultProviderInterface;
use Phpro\SoapClient\Type\ResultInterface;

class GetReleaseNotesResponse implements ResultProviderInterface
{

    /**
     * @var GetReleaseNotesResult
     */
    private $GetReleaseNotesResult = null;

    /**
     * @return GetReleaseNotesResult|ResultInterface
     */
    public function getResult() : \Phpro\SoapClient\Type\ResultInterface
    {
        return $this->GetReleaseNotesResult;
    }
}
```

Now, in the `\Phpro\SoapClient\Client::call()` method, there is [code](https://github.com/phpro/soap-client/blob/5e0f5dd74a0a261db8c73cb669bdc376ad258d50/src/Phpro/SoapClient/Client.php#L97-L99) to skip straight to the `getResult()` value:

```php
if ($result instanceof ResultProviderInterface) {
    $result = $result->getResult();
}
```

When I use `generate:client` command, I get (as one example) a default client method assembler giving me:

```php
public function getReleaseNotes(\GAA\CorpManagerApi\SoapTypes\GetReleaseNotes $GetReleaseNotes) : \GAA\CorpManagerApi\SoapTypes\GetReleaseNotesResponse
{
    return $this->call('GetReleaseNotes', $GetReleaseNotes);
}
```
![screenshot 2017-12-30 14 03 34](https://user-images.githubusercontent.com/88371/34454783-789e4c06-ed6a-11e7-96dc-6c12b54e28bd.png)

Note that it's giving a return type of `GetReleaseNotesResponse`, yet the `@return` from `call()` is `ResultInterface`.

My manually created Client that has been working was return type declared as `ResultInterface`.

So my question:

Am I doing something wrong in my setup that is making the generated return type be incorrect, or is the [`returntype` value](https://github.com/phpro/soap-client/blob/5e0f5dd74a0a261db8c73cb669bdc376ad258d50/src/Phpro/SoapClient/CodeGenerator/Assembler/ClientMethodAssembler.php#L54) in the ClientMethodAssembler incorrect?

Here would be the proposed change if its a bug:

```diff
- 'returntype' => '\\'.$method->getParameterNamespace().'\\'.$method->getReturnType(),
+ 'returntype' => ResultInterface::class,
```

**Comment by veewee** [comment]
Hi @GaryJones,

That is indeed a bug. Hower, I would avoid setting ResultInterface as the return type of the client.

**Comment by veewee** [comment]
Hi @GaryJones,

Thanks for your work. It took me some time to review. Can you take a look at the remarks?

**Comment by janvernieuwe** [comment]
I think this issue is reloved now with the new docblocks in the client.
If not, respond here and we'll reopen it.
