### ISSUE TITLE
Symfony 4 Release

### ISSUE THREAD

**Issue by rickogden** [phpro/soap-client#127]
I see that the composer.json has already included support for Symfony 4, but there are no releases containing this version. Any chance a release could be tagged with this update?

**Comment by veewee** [comment]
Hi @rickogden,

We'll be releasing a new version soon. I need to get some PRs merged in first - probably somewhere next week.

**Comment by icanhazstring** [comment]
@veewee is the release out soon?
Because right now I can't use the lib due to version contraints :(

**Comment by veewee** [comment]
All issues for next release have been merge. We'll do some additional tests to make sure everything works. If everything goes wel: we'll be able to release tomorrow.

Thanks for your patience :)

**Comment by icanhazstring** [comment]
Awesome. Thank you!

**Comment by veewee** [comment]
Released : https://github.com/phpro/soap-client/releases/tag/0.6.1
