### ISSUE TITLE
Error running Wizard

### ISSUE THREAD

**Issue by gassius** [phpro/soap-client#147]
Clean instalation:
composer require phpro/soap-client
composer require --dev zendframework/zend-code:^3.1.0

Executing
./vendor/bin/soap-client wizard
PHP Parse error:  syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE) in /home/cgonzalez/Code/emaisSOAP/vendor/phpro/soap-client/src/Phpro/SoapClient/Console/Application.php on line 19

php -v
PHP 7.0.25-0ubuntu0.16.04.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies

It seems like visibility modifiers are available only from PHP 7.1 (as per [documentation](http://php.net/manual/en/language.oop5.constants.php)) However your composer.json requires `"php": "^7.0",`

**Comment by janvernieuwe** [comment]
Hi @gassius,
Thank you for reporting this issue.
The visibility modifier needs to be dropped.

**Comment by gassius** [comment]
Hi @janvernieuwe 
You are welcome

I will patch them locally while a new package is available via composer.

Regards

**Comment by veewee** [comment]
Hi @gassius,

Thanks for reporting! We've tagged a fix and will soon make sure the CI will detect these errors in the future.
https://github.com/phpro/soap-client/releases/tag/0.7.1

**Comment by gassius** [comment]
You are welcome @veewee and thanks for the lightning quick turn around on the issue.
