### ISSUE TITLE
 stream_get_contents(): SSL: Connection reset by peer

### ISSUE THREAD

**Issue by gyaan** [phpro/soap-client#152]
Hey 

I am getting below soap error.

stream_get_contents(): SSL: Connection reset by peer

Any idea why?

It may be not phpro soap-client but still if anything I am missing in configuration please let me know.

**Comment by janvernieuwe** [comment]
Hi @gyaan ,

I don't think this is an issue with the package itself, as you already stated.

You can try and debug the last request, and see if there's something wrong with that.
You can also try to send the request manually in the CLI or HTTP Client to test it out, perhaps a more useful error can be seen this way.

**Comment by veewee** [comment]
As @janvernieuwe  mentions, this error is due to invalid or untrusted SSL certificates and not to this package.

**Comment by rohang1997** [comment]
i have having same issue . i wrapped socket with SSL layer.
It was occurring due to mismatch between server and client certificates.
