### ISSUE TITLE
Wrap only a subset of operations

### ISSUE THREAD

**Issue by aderuwe** [phpro/soap-client#155]
I've been wondering if it is possible to somehow only wrap the calls that I will be needing? Or should I always generate all calls in the WSDL?

**Comment by janvernieuwe** [comment]
Hi @aderuwe (long time no see!)

The client generator is currently made so it will implement all calls it finds in the wsdl (I assume that is what this is about).
You can always edit the generated code to throw out what you don't need ofcourse.

**Comment by aderuwe** [comment]
Hi @janvernieuwe, yes indeed, it's been a while. :)

Ok - I was asking because I have about 185 simple types I will need to convert somehow, and limiting those was one idea - by only generating code for the calls that I need.
Had some discussions with @veewee offline, and I will try to make a middleware to deal with those simple types.

I'll close this for now. :)
