### ISSUE TITLE
Class 'SoapClient' not found  while generating client

### ISSUE THREAD

**Issue by kunoSchlonz** [phpro/soap-client#157]
_while calling:_
`~/projects/soap-test$ vendor/bin/soap-client generate:client -o --config=config/soap-client.php`

_this output appears_
`**PHP Fatal error:**  Class 'SoapClient' not found in /home/....../projects/soap-test/vendor/phpro/soap-client/src/Phpro/SoapClient/Soap/SoapClient.php on line 18`

PHP Version is:
`PHP 7.2.3-1ubuntu1 (cli) (built: Mar 14 2018 22:03:58) ( NTS )`

**Comment by janvernieuwe** [comment]
Did you install ext-soap?
We have already added a dependency in composer for this in the develop branch.

**Comment by kunoSchlonz** [comment]
now it works
`sudo apt-get install php-soap`
