### ISSUE TITLE
Adding option withTypeHints to FluentSetterAssemblerOptions

### ISSUE THREAD

**Issue by HKandulla** [phpro/soap-client#167]
Hi,

is there a reason why the option withTypeHints only exists on the SetterAssemblerOptions and not on the FluentSetterAssemblerOptions? If not, can I provide a PR to add this option?

Thanks, Hannes

**Comment by janvernieuwe** [comment]
Hi @HKandulla ,

Not that I can think of right now, we'd be happy to merge such a PR!

**Comment by HKandulla** [comment]
great! Thanks for the quick reply.

**Comment by HKandulla** [comment]
https://github.com/phpro/soap-client/pull/168

**Comment by janvernieuwe** [comment]
It's in the 0.7.5 release :tada:
