### ISSUE TITLE
How to bind a simpleContent with POPO ?

### ISSUE THREAD

**Issue by Neirda24** [phpro/soap-client#173]
Hi,

Following this sample: https://www.w3schools.com/xml/el_simpleContent.asp ;
How do we create a mapping for the simpleContent ?

For example: set the property value to 35.

Thanks in advance.

**Comment by janvernieuwe** [comment]
Hi @Neirda24,

I'm going to have to try some things out myself, if at all possible, could you share the service you are trying  this on? That would save us alot of time.

Regards,

**Comment by Neirda24** [comment]
Hmmm that would be complicated TBH as it is a private service. But really any WSDL that has the structure linked above and you create a class like said in the documentation, it will automatically create a `_` property. After some research it seems to be related to the native `\SoapClient`. I don't know if you can create some way to mep it but I don't think it is a bug actually... More like `Some weird behavior still not documented` of the use of SOAP in PHP...

**Comment by janvernieuwe** [comment]
Hehe there is plenty of `Some weird behavior still not documented` unfortunately.
The `_` property is the textContent of the node, so this is the property you'll need to set or get. 

I'll try and see if there is anything generic we can do to access it.

**Comment by Neirda24** [comment]
Thanks ;)

**Comment by janvernieuwe** [comment]
So much to do, you can use the _ getter and setter for now.
We're happy to accept a PR for improvements ofcourse!
