### ISSUE TITLE
generate types to wrong directory

### ISSUE THREAD

**Issue by irfanevrens** [phpro/soap-client#176]
Hello,

WSDL: http://ws.ups.com.tr/wsCreateShipment/wsCreateShipment.asmx?WSDL

There is a type named "Login_Type1".

Login_Type1 generated BlaBla/Type/Login/Type1.php but class named "Login_Type1"

This brake PSR-4 autoloading.

Look at this codes;
$name = str_replace('_', DIRECTORY_SEPARATOR, $this->getName());

This code is in CodeGenerator/Model/Type.php line: 87 (V: 0.7.5)

Thanks.

**Comment by janvernieuwe** [comment]
Hi @irfanevrens ,

Thanks for reporting this, we'll take a look at it.

**Comment by janvernieuwe** [comment]
Going to try to get this one in the master asap, release is scheduled at the end of the month.
Now I just need to find someone with time to review this :)

**Comment by irfanevrens** [comment]
Hemen bakıyorum @janvernieuwe

**Comment by janvernieuwe** [comment]
Expect a new release next friday!
Thanks for the review!
