### ISSUE TITLE
Multiples namespaces, wrong one in the generated XML

### ISSUE THREAD

**Issue by vichenze** [phpro/soap-client#177]
|    Q        |   A
|------------ | -----
| Version     | 0.7.4

### Support Question

I'm facing a problem when calling a specific method in a WSDL. When I try using a SOAP client like soapUI, the generated XML is correct and I got a correct answer. But when I use phpro and I debug the XML request, I see a weird tag (and the server gives me an error). The problem may be cause by the multiples namespaces used by this WSDL.

The expected XML looks like (part of) :
```
<cb:Customer>
                    <sch:Address1>xxxx</sch:Address1>
                    <sch:Address2 xsi:nil="true"/>
                    <sch:CellPhoneNumber>00000000</sch:CellPhoneNumber>
                    <sch:CustomerRef>000#5544</sch:CustomerRef>
</cb:Customer>
<cb:Order>
                    <sch:OrderDate>2018-07-30</sch:OrderDate>
                    <sch:SaleChannel>DESKTOP</sch:SaleChannel>
                    <sch:ShoppingCartRef>125445</sch:ShoppingCartRef>
</cb:Order>
```

The XML I got from Phpro (I replaced ns1 and ns2 by the namespaces from above, but I doesn't change the problem)  :
```
<cb:Customer>
                    <sch:Address1>xxxx</sch:Address1>
                    <sch:Address2 xsi:nil="true"/>
                    <sch:CellPhoneNumber>00000000</sch:CellPhoneNumber>
                    <sch:CustomerRef>000#5544</sch:CustomerRef>
</cb:Customer>
<cb:Order xsi:type="sch:Order">
                    <sch:OrderDate>2018-07-30</sch:OrderDate>
                    <sch:SaleChannel>DESKTOP</sch:SaleChannel>
                    <sch:ShoppingCartRef>125445</sch:ShoppingCartRef>
</cb:Order>
```

I don't understand where this `<cb:Order xsi:type="sch:Order">` comes from, and why only the Order tag is impacted and not the Customer one.
Is there any way to remove it ? Is it possible in the Type files to define a specific namespace ?

Thanks

**Comment by vichenze** [comment]
https://services.recette-cb4x.fr/cb4xFrontService.svc?wsdl

I may have a clue. There is an "Order" type defined in 2 namespaces, and it's not the same in both.
I debug using `getSoapTypes()`, the Order type appears only once.
When I do the same with the native PHP soap client with `$client->__getTypes()`, I see the 2 types (because the key in the array are numeric and aren't the type name)

**Comment by janvernieuwe** [comment]
I can't access that file it seems (firewalled?) can you upload / attach it here?
We'll take a look when we have the time.

A PR is always welcome ofcourse!

**Comment by vichenze** [comment]
Oh yep, I wasn't aware of this firewall issue. Actually I'm not sure I can give publicly the link. Can I send it to you in private somewhere ? 

We'll see for the PR if I have time.

**Comment by janvernieuwe** [comment]
You can send it to the email address of my account.
