### ISSUE TITLE
How could I introduce and html_entity_decode in SoapClient?

### ISSUE THREAD

**Issue by killua99** [phpro/soap-client#180]
|    Q        |   A
|------------ | -----
| Version     | 0.6.1

### How could I introduce and html_entity_decode in SoapClient?

I'm trying to figure out how to implement an `html_entity_decode()` at the __doRequest. So far I tested to hack the file SoapClient.php to see if that would solve the error I'm having related encoding. I was trying to figure out if that could be achieve via middleware or types.

Please let me know if I didn't explain what I'm trying to achieve.

**Comment by veewee** [comment]
@killua99,

Can you tell me more about what you are trying to do exactly?
Do you want to decode the request or response?
Normally the soapclient handles xml entities by default.

**Comment by killua99** [comment]
what I'm trying to do is this.

```php
    public function __doRequest( $request, $location, $action, $version, $oneWay = 0 ) {
        $request = html_entity_decode( $request );

        parent::__doRequest( $request, $location, $action, $version, $oneWay );
    }
```

The request has something that make it fail. Some character there is messing the request.

**Comment by killua99** [comment]
This code is one thought I've, tho, I haven't try it yet.

```php
<?php
/**
 * Entity Decode Request
 *
 * @package My
 */

namespace My\Resources\Middlewares;

use Http\Promise\Promise;
use Phpro\SoapClient\Middleware\Middleware;
use Psr\Http\Message\RequestInterface;

/**
 * Class RequestDecode
 *
 * @package My\Resources\Middlewares
 */
class RequestDecode extends Middleware {

	/**
	 * @inheritdoc
	 */
	public function beforeRequest( callable $next, RequestInterface $request ) : Promise {

		$body         = $request->getBody();
		$body_decoded = html_entity_decode( $body->getContents() );
		$body->write( $body_decoded );
		$request->withBody( $body );

		return parent::beforeRequest( $next, $request );
	}
}
```

**Comment by veewee** [comment]
Wouldn't it make more sense to add the failing entity declaration to the xml request instead?
Can you give me an example of those failing characters?

**Comment by killua99** [comment]
It's related to a CDATA character, I'll try to tracked down.

**Comment by veewee** [comment]
Hi @killua99,

Since this issue didn't get an update in a while, we are closing this one.
Feel free top open a new issue with more information on the topic.
