### ISSUE TITLE
 Phpro\SoapClient\Client::call() requires second argument to be an in stance of Phpro\SoapClient\Type\RequestInterface but client methods expect \App\Type arguments

### ISSUE THREAD

**Issue by systemovich** [phpro/soap-client#181]
|    Q        |   A
|------------ | -----
| Version     | 0.7.5

### Support Question

I am testing out the public SOAP web service at http://webservices.oorsprong.org/websamples.countryinfo/CountryInfoService.wso?WSDL that supplies information about countries. 

This is what a portion of the WSDL looks like:

```xml
<message name="CountryNameSoapRequest">
  <part name="parameters" element="tns:CountryName"/>
</message>
<message name="CountryNameSoapResponse">
  <part name="parameters" element="tns:CountryNameResponse"/>
</message>
```

I used the client wizard which produced the following configuration in **config/soap-client.php**:

```php
<?php

use Phpro\SoapClient\CodeGenerator\Assembler;
use Phpro\SoapClient\CodeGenerator\Rules;
use Phpro\SoapClient\CodeGenerator\Config\Config;

return Config::create()
    ->setWsdl('http://webservices.oorsprong.org/websamples.countryinfo/CountryInfoService.wso?WSDL')
    ->setTypeDestination('src\Type')
    ->setTypeNamespace('App\Type')
    ->setClientDestination('src')
    ->setClientName('CountryClient')
    ->setClientNamespace('App')
    ->setClassMapDestination('src')
    ->setClassMapName('CountryClassmap')
    ->setClassMapNamespace('App')
    ->addRule(new Rules\AssembleRule(new Assembler\GetterAssembler(new Assembler\GetterAssemblerOptions())))
    ->addRule(new Rules\AssembleRule(new Assembler\ImmutableSetterAssembler()))
    ->addRule(
        new Rules\TypenameMatchesRule(
            new Rules\MultiRule([
                new Rules\AssembleRule(new Assembler\RequestAssembler()),
                new Rules\AssembleRule(new Assembler\ConstructorAssembler()),
            ]),
            '/Request$/i'
        )
    )
    ->addRule(
        new Rules\TypenameMatchesRule(
            new Rules\MultiRule([
                new Rules\AssembleRule(new Assembler\ResultAssembler()),
            ]),
            '/Response$/i'
        )
    )
;
```

In my script to try out the service, I call the client's countryName method which expects an instance of CountryName.

```php
<?php

require_once __DIR__ . '/vendor/autoload.php';

$config = require_once __DIR__ . '/config/soap-client.php';

$client = \App\CountryClientFactory::factory($config->getWSDL());
$response = $client->countryName(
    (new \App\Type\CountryName())->withSCountryISOCode('ZAF')
);
var_dump($response);
```

When I run it with `php test.php`, I get this error:

> PHP Fatal error:  Uncaught TypeError: Argument 2 passed to Phpro\SoapClient\Client::call() must be an in
stance of Phpro\SoapClient\Type\RequestInterface, instance of App\Type\CountryName given, called in C:\U
sers\geoffrey\tmp\soapclienttester\src\CountryClient.php on line 100 and defined in C:\Users\geoffrey\tm
p\soapclienttester\vendor\phpro\soap-client\src\Phpro\SoapClient\Client.php:88
Stack trace:
#0 C:\Users\geoffrey\tmp\soapclienttester\src\CountryClient.php(100): Phpro\SoapClient\Client->call('Cou
ntryName', Object(App\Type\CountryName))
#1 C:\Users\geoffrey\tmp\soapclienttester\test.php(9): App\CountryClient->countryName(Object(App\Type\Co
untryName))
#2 {main}
  thrown in C:\Users\geoffrey\tmp\soapclienttester\vendor\phpro\soap-client\src\Phpro\SoapClient\Client.
php on line 88

When I modify the \App\CountryName class to implement \Phpro\SoapClient\Type\RequestInterface, then I get the expected result.

> object(App\Type\CountryNameResponse)#101 (1) {
  ["CountryNameResult":"App\Type\CountryNameResponse":private]=>
  string(12) "South Africa"
}

**Comment by veewee** [comment]
Hello @systemovich,

As you can see, the request type is named `App\Type\CountryName`. The type is not ending on regex `/Request$/i`. Therefor, the `RequestInterface` is not added to that type.
Please update the regex or add the interface manually.

More info:
- https://github.com/phpro/soap-client/blob/master/docs/client.md
- https://github.com/phpro/soap-client/blob/master/docs/code-generation/assemblers.md#requestassembler

**Comment by systemovich** [comment]
Thanks @veewee, I thought the regex applied to the name attribute of the message element.
