### ISSUE TITLE
How to separate in soap client Exceptions for SOAP service availability from Exceptions for SOAP service error codes?

### ISSUE THREAD

**Issue by devicebusy** [phpro/soap-client#183]
|    Q        |   A
|------------ | -----
| Version     | 0.7.5

### Support Question
How can i implement different handlers for situation when SOAP service is unavailable or return non-SOAP responses and for situation when SOAP service is working correctly but returns SOAP Fault as response for request (for example request is correct but requested operation is invalid for requested parameters)? I've try to look for Middleware, but it seems like Middleware working only with request, not response. Or i should create some Plugin for it? 

Thank you.

**Comment by janvernieuwe** [comment]
Hi @devicebusy,

Have you tried using the dispatcher and event subscribers?
You can create subscribers for response and fault events.

```
        $clientBuilder->withEventDispatcher($dispatcher);
        $dispatcher->addSubscriber(new ResponseSubscriber());
        $dispatcher->addSubscriber(new FaultSubscriber());
```

For more information you can check out this documentation: https://github.com/phpro/soap-client/blob/master/docs/events.md

**Comment by devicebusy** [comment]
Thank you, exactly what i need.
