### ISSUE TITLE
Issues due to property normalizing 

### ISSUE THREAD

**Issue by jyggen** [phpro/soap-client#185]
I'm trying to integrate against a SOAP service and I'm running into some issues with the property normalizing.

All properties in the WSDL are in UpperCamelCase (e.g. OutErrorCode, OutNumAvail etc.) and are normalized during code generation to lowerCamelCase (e.g. `$outErrorCode`, `$outNumAvail` etc.). So far so good!

However, problems occur when making requests and trying to use the result classes since our friend SoapClient seems to assign values to the properties' UpperCamelCase variant.

Dumping the result (using `symfony/var-dumper`) outputs something along the lines of:

```
FoobarResponse {#101
  -outErrorCode: null
  -outFoobar: null
  +"OutErrorCode": "11"
  +"OutFoobar": ""
}
```

I assume this isn't the intended behaviour? The workaround right now is to manually change all type properties to the correct case. My assumption is that SoapClient is unaware of the `OutErrorCode -> outErrorCode` transformation, but I'm not sure it's possible to make it aware either.

Thanks!

**Comment by veewee** [comment]
Hi @jyggen,

Nice to meet you in this package as well!
You should be able to fix this behaviour by using the [SetterAssembler](https://github.com/phpro/soap-client/blob/master/docs/code-generation/assemblers.md#setterassembler).  Does this work for you?

**Comment by jyggen** [comment]
Hi! It's nice to have found a sane little oasis in the devastating Soap desert!

Maybe I'm missing something, but I'm already generating setters for my types and they're not being used by SoapClient at all. The instance of my type that is returned [here](https://github.com/phpro/soap-client/blob/f9b3f7bb15f95e52f2fd9870eac972b8f03197be/src/Phpro/SoapClient/Client.php#L95) already contains the erroneous class properties.

In the WSDL that my types are generated from, the properties are named `OutErrorCode` and `OutFoobar`, but in the type they've been normalized by the code generator to  `outErrorCode` and `outFoobar`. As I mentioned in my first post, it seems like SoapClient is setting these properties as-is (aka. `OutErrorCode` and `OutFoobar`), which is why I end up with duplicated properties on my type class.

The obvious solution is, of course, to change my properties to use the same casing as the SOAP service, but I just wanted to make sure that I'm not missing something or encountering a bug :)

**Comment by janvernieuwe** [comment]
Hi @jyggen ,

I think I found the issue, can you check if my PR works for you?
You will need to regenerate the types for it to work.
