### ISSUE TITLE
Request does not contain parameters

### ISSUE THREAD

**Issue by max21** [phpro/soap-client#186]
|    Q        |   A
|------------ | -----
| Version     | 0.7.6

### Support Question

Each methods does not contain parameters when request it.
For example : 

`$client = \Example\ERP\ERPClientFactory::factory('mywsdl.xsld');
$soapCalcKey = new \Example\ERP\Type\CalcKey('url','id','key');
$response = $client->get_calc_key($soapCalcKey);
var_dump($client->debugLastSoapRequest());exit;`

The debug request call the right method but does not contains parameters url, id and key.

**Comment by janvernieuwe** [comment]
@max21 can you checkout dev-master, and regenrate your types to see if this solves your issue?

**Comment by veewee** [comment]
Hi @max21,

We consider this issue to be fixed. Feel free to create a new issue with additional WSDL + code generation information if you still have any problems.
