### ISSUE TITLE
Use documentation from .wsdl in generated code?

### ISSUE THREAD

**Issue by GaryJones** [phpro/soap-client#19]
The code generated by soap-client tends to just add a DocBlock with the `@var` or `@return` type. I'd love to be able to get Summary and Description added in for methods and properties. 

* How might this information be added in to the WSDL?
* How might soap-client be able to read that and make use of it?

**Comment by veewee** [comment]
Internally, the built-in [__getTypes](http://php.net/manual/en/soapclient.gettypes.php)() method is used to detect ask the different types and properties. There is no way to load the description nor summary.
This means that this is not possible at the moment to fetch this data from the WSDL without parsing it manually.
