### ISSUE TITLE
Entity names with underscores are treated inconsistently

### ISSUE THREAD

**Issue by clamburger** [phpro/soap-client#191]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | unknown
| Version     | master

#### Summary

SOAP entities containing underscores are treated inconsistently in generated PHP code.

#### Current behavior

When generating PHP code, a SOAP entity with an underscore in the name will keep the underscore in some generated code, but will lose it in other generated code. The worst result of this is that the method calls generated using `generate:client` will have typehints that don't match the actual class names, causing them to be unusable.

#### How to reproduce

Create a config file with the following contents:

```
<?php

use Phpro\SoapClient\CodeGenerator\Assembler;
use Phpro\SoapClient\CodeGenerator\Rules;
use Phpro\SoapClient\CodeGenerator\Config\Config;

return Config::create()
    ->setWsdl('https://api.smdservers.net/CCWs_3.5/CallCenterWs.asmx?WSDL')
    ->setTypeDestination('src\Type')
    ->setTypeNamespace('Example')
    ->setClientDestination('src')
    ->setClientName('ExampleClient')
    ->setClientNamespace('Example')
    ->setClassMapDestination('src')
    ->setClassMapName('ExampleClassmap')
    ->setClassMapNamespace('Example')
    ->addRule(
        new Rules\AssembleRule(
            new Assembler\GetterAssembler(
                new Assembler\GetterAssemblerOptions()
            )
        )
    )
;
```

Run these commands:

```
vendor/bin/soap-client generate:classmap --config=config/soap-client.php
vendor/bin/soap-client generate:client --config=config/soap-client.php
vendor/bin/soap-client generate:types --config=config/soap-client.php
```

Using the `TenantUpdate_NationalAccount` entity as an example (and the associated Response and Result entities), we can see the following differences:

* The name of the result class in src/Type is `TenantUpdateNationalAccountResult`
* The member name and getter in `TenantUpdateNationalAccountResponse` uses `TenantUpdate_NationalAccountResult` instead
* The function in `CallCenterClient` has the name `tenantUpdate_NationalAccount` and has an invalid typehint (`TenantUpdate_NationalAccount`) and return type (`TenantUpdate_NationalAccountResponse`)

#### Expected behavior

The entity name is treated the same way in all generated code: it either keeps the underscore, or loses it.

**Comment by veewee** [comment]
Lets continue the discussion in #196.
