### ISSUE TITLE
Problem with ListCustomers

### ISSUE THREAD

**Issue by Stoufine** [phpro/soap-client#202]
|    Q        |   A
|------------ | -----
| Version     | 0.7.8

### Support Question

Hello,

I allow myself to post a car with a problem with phpro / soap-client.

Indeed, the server sends me a client with the correct identifier, but when I want to display the list of clients, I have the error message `ERROR_EMPTY_RESPONSE`.

I used this command 
`var_dump($client->listCustomers(new MultiArgumentRequest([$token, "", "", "GOODNAME", ""])));`

**Comment by janvernieuwe** [comment]
Hi @Stoufine,

Can you provide the WSDL you used, and possibly the last request and response?
Otherwise it's pretty much impossible for us to check this.
