### ISSUE TITLE
Error while creating soap-client.php with wizard

### ISSUE THREAD

**Issue by KevinArtus** [phpro/soap-client#204]
|    Q        |   A
|------------ | -----
| Version     | 0.7.8

Hi

I'm facing a problem when trying to trying to use the wizard.
I got this error :

> PHP Parse error:  syntax error, unexpected ']' in /home/CO_LINK/config/soap-client.php on line 24

It seems that the wizard is missing a ) here :

> new Rules\AssembleRule(new Assembler\ConstructorAssembler(new Assembler\ConstructorAssemblerOptions())

could be

> new Rules\AssembleRule(new Assembler\ConstructorAssembler(new Assembler\ConstructorAssemblerOptions())**)**

Here is the soap-config.php generated:
```php
<?php

use Phpro\SoapClient\CodeGenerator\Assembler;
use Phpro\SoapClient\CodeGenerator\Rules;
use Phpro\SoapClient\CodeGenerator\Config\Config;

return Config::create()
    ->setWsdl('test.wsdl')
    ->setTypeDestination('src/Type')
    ->setTypeNamespace('App\Type')
    ->setClientDestination('src')
    ->setClientName('ProviderClient')
    ->setClientNamespace('App')
    ->setClassMapDestination('src')
    ->setClassMapName('ProviderClassmap')
    ->setClassMapNamespace('App')
    ->addRule(new Rules\AssembleRule(new Assembler\GetterAssembler(new Assembler\GetterAssemblerOptions())))
    ->addRule(new Rules\AssembleRule(new Assembler\ImmutableSetterAssembler()))
    ->addRule(
        new Rules\TypenameMatchesRule(
            new Rules\MultiRule([
                new Rules\AssembleRule(new Assembler\RequestAssembler()),
                new Rules\AssembleRule(new Assembler\ConstructorAssembler(new Assembler\ConstructorAssemblerOptions()),
            ]),
            '/(?<!Response)$/i'
        )
    )
    ->addRule(
        new Rules\TypenameMatchesRule(
            new Rules\MultiRule([
                new Rules\AssembleRule(new Assembler\ResultAssembler()),
            ]),
            '/Response$/i'
        )
    )
;
```

Thanks in advance

**Comment by janvernieuwe** [comment]
Hi @KevinArtus could you provide the wsdl so we can recreate this?

**Comment by janvernieuwe** [comment]
Actually, I already see the issue, will push a fix and tag soon.

**Comment by janvernieuwe** [comment]
@KevinArtus a new version with this fix is released.
You can update when packagist fetches it, or use dev-master for now.

Thanks for the report!

**Comment by KevinArtus** [comment]
Thanks for your replies. I'll test it asap.
