### ISSUE TITLE
Getting a "A method by name X already exists in this class." when generating client from complex wsdl

### ISSUE THREAD

**Issue by steenbag** [phpro/soap-client#206]
|    Q        |   A
|------------ | -----
| Version     | master (dbd76b80), 0.7.8, 0.7.9

### Support Question

Hi, I'm trying to generate a service client from a third-party wsdl (gist with -> https://gist.github.com/steenbag/a66732648bd546a1c44dff18fbe60ba7 and client config -> https://gist.github.com/steenbag/b11419115bc6cc5413d5ebc0a55b75e8). I am able to generate the types and classmap without issue. However when I go to generate the client, I get the error:

In AssemblerException.php line 20:

  [Phpro\SoapClient\Exception\AssemblerException]
  A method by name memberGetAttendanceReportForRpartySelMem already exists in this class.

Exception trace:
 () at /home/vagrant/code/spectrum-sdk-php/vendor/phpro/soap-client/src/Phpro/SoapClient/Exception/AssemblerException.php:20
 Phpro\SoapClient\Exception\AssemblerException::fromException() at /home/vagrant/code/spectrum-sdk-php/vendor/phpro/soap-client/src/Phpro/SoapClient/CodeGenerator/Assembler/ClientMethodAssembler.php:64
 Phpro\SoapClient\CodeGenerator\Assembler\ClientMethodAssembler->assemble() at /home/vagrant/code/spectrum-sdk-php/vendor/phpro/soap-client/src/Phpro/SoapClient/CodeGenerator/Rules/AssembleRule.php:45
 Phpro\SoapClient\CodeGenerator\Rules\AssembleRule->apply() at /home/vagrant/code/spectrum-sdk-php/vendor/phpro/soap-client/src/Phpro/SoapClient/CodeGenerator/Rules/RuleSet.php:50
 Phpro\SoapClient\CodeGenerator\Rules\RuleSet->applyRules() at /home/vagrant/code/spectrum-sdk-php/vendor/phpro/soap-client/src/Phpro/SoapClient/CodeGenerator/ClientGenerator.php:50
 Phpro\SoapClient\CodeGenerator\ClientGenerator->generate() at /home/vagrant/code/spectrum-sdk-php/vendor/phpro/soap-client/src/Phpro/SoapClient/Console/Command/GenerateClientCommand.php:108
 Phpro\SoapClient\Console\Command\GenerateClientCommand->generateClient() at /home/vagrant/code/spectrum-sdk-php/vendor/phpro/soap-client/src/Phpro/SoapClient/Console/Command/GenerateClientCommand.php:92
 Phpro\SoapClient\Console\Command\GenerateClientCommand->execute() at /home/vagrant/code/spectrum-sdk-php/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /home/vagrant/code/spectrum-sdk-php/vendor/symfony/console/Application.php:919
 Symfony\Component\Console\Application->doRunCommand() at /home/vagrant/code/spectrum-sdk-php/vendor/symfony/console/Application.php:262
 Symfony\Component\Console\Application->doRun() at /home/vagrant/code/spectrum-sdk-php/vendor/symfony/console/Application.php:145
 Symfony\Component\Console\Application->run() at /home/vagrant/code/spectrum-sdk-php/vendor/phpro/soap-client/bin/soap-client:26

In ClassGenerator.php line 878:

  [Zend\Code\Generator\Exception\InvalidArgumentException]
  A method by name memberGetAttendanceReportForRpartySelMem already exists in this class.

Exception trace:
 () at /home/vagrant/code/spectrum-sdk-php/vendor/zendframework/zend-code/src/Generator/ClassGenerator.php:878
 Zend\Code\Generator\ClassGenerator->addMethodFromGenerator() at /home/vagrant/code/spectrum-sdk-php/vendor/phpro/soap-client/src/Phpro/SoapClient/CodeGenerator/Assembler/ClientMethodAssembler.php:59
 Phpro\SoapClient\CodeGenerator\Assembler\ClientMethodAssembler->assemble() at /home/vagrant/code/spectrum-sdk-php/vendor/phpro/soap-client/src/Phpro/SoapClient/CodeGenerator/Rules/AssembleRule.php:45
 Phpro\SoapClient\CodeGenerator\Rules\AssembleRule->apply() at /home/vagrant/code/spectrum-sdk-php/vendor/phpro/soap-client/src/Phpro/SoapClient/CodeGenerator/Rules/RuleSet.php:50
 Phpro\SoapClient\CodeGenerator\Rules\RuleSet->applyRules() at /home/vagrant/code/spectrum-sdk-php/vendor/phpro/soap-client/src/Phpro/SoapClient/CodeGenerator/ClientGenerator.php:50
 Phpro\SoapClient\CodeGenerator\ClientGenerator->generate() at /home/vagrant/code/spectrum-sdk-php/vendor/phpro/soap-client/src/Phpro/SoapClient/Console/Command/GenerateClientCommand.php:108
 Phpro\SoapClient\Console\Command\GenerateClientCommand->generateClient() at /home/vagrant/code/spectrum-sdk-php/vendor/phpro/soap-client/src/Phpro/SoapClient/Console/Command/GenerateClientCommand.php:92
 Phpro\SoapClient\Console\Command\GenerateClientCommand->execute() at /home/vagrant/code/spectrum-sdk-php/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /home/vagrant/code/spectrum-sdk-php/vendor/symfony/console/Application.php:919
 Symfony\Component\Console\Application->doRunCommand() at /home/vagrant/code/spectrum-sdk-php/vendor/symfony/console/Application.php:262
 Symfony\Component\Console\Application->doRun() at /home/vagrant/code/spectrum-sdk-php/vendor/symfony/console/Application.php:145
 Symfony\Component\Console\Application->run() at /home/vagrant/code/spectrum-sdk-php/vendor/phpro/soap-client/bin/soap-client:26

The referenced method, memberGetAttendanceReportForRpartySelMem, is the very first method in the service, and is actually named "Member_GetAttendanceReportForRpartySelMem" so I'm not sure if normalization is the issue. Additionally, this WSDL contains bindings for SOAP 1 and 1.2 services, so I'm not sure if that could be causing the issue as well.

FWIW, I have a working copy of the client that was generated on October 16th, it looks like maybe before PR #196 was merged in, if I revert back to commit aeceaae5 I am able to generate a client again, however in this version normalization is broken. The client method is called "member_GetAttendanceReportForRpartySelMem", it is type hinted with "Member_GetAttendanceReportForRpartySelMem" but the generated class is called "MemberGetAttendanceReportForRpartySelMem".

Thanks,
Andrew

**Comment by janvernieuwe** [comment]
Hi @steenbag,

Thanks for reporting this with all the needed information.
I can generate a client if we allow underscores in the method name, I have pushed this change to my fork here https://github.com/janvernieuwe/soap-client/tree/issue-206 .

Can you try that version?
If it all works for you, then I will merge it into the client.

Regards,
Jan

**Comment by steenbag** [comment]
Wow, thanks for the incredible response time!  That change seems to fix this issue, thanks.

**Comment by janvernieuwe** [comment]
@steenbag you can use dev-master until we tag a new version.
