### ISSUE TITLE
Phpro\SoapClient\Client::call() must be an instance of Phpro\SoapClient\Type\RequestInterface

### ISSUE THREAD

**Issue by wujekbogdan** [phpro/soap-client#208]
|    Q        |   A
|------------ | -----
| Version     | 0.7.9

### Support Question

I'm trying to get started with `phpro/soap-client` but I got stuck at the very beginning. I'm not able to send a request.

Here's my config file:

``` php
return Config::create()
    ->setWsdl('https://www.transpact.com/SecurePartner/Partner.asmx?WSDL')
    ->setTypeDestination('Transpact/Type')
    ->setTypeNamespace('Transpact\Type')
    ->setClientDestination('Transpact')
    ->setClientName('TranspactClient')
    ->setClientNamespace('Transpact')
    ->setClassMapDestination('Transpact')
    ->setClassMapName('TranspactClassmap')
    ->setClassMapNamespace('Transpact')
    ->addRule(new Rules\AssembleRule(new Assembler\GetterAssembler(new Assembler\GetterAssemblerOptions())))
    ->addRule(new Rules\AssembleRule(new Assembler\ImmutableSetterAssembler()))
;
```

Here's the code:

``` php
use \Transpact\TranspactClientFactory;
use \Transpact\Type\TranspactHistory;

$client = TranspactClientFactory::factory('https://www.transpact.com/SecurePartner/Partner.asmx?WSDL');
$request = new TranspactHistory();
$requestData = $request->withIsTest(true);
$response = $client->transpactHistory($requestData);
```

I see that `$client->transpactHistory()` method requires an instance of a `\Transpact\Type\TranspactHistory`, but when I pass an instance of that class to it then I get an error:

```
Fatal error: Uncaught TypeError: Argument 2 passed to Phpro\SoapClient\Client::call() must be an instance of Phpro\SoapClient\Type\RequestInterface, instance of Transpact\Type\TranspactHistory given
```

So it seems that `TranspactHistory` should implement the `Phpro\SoapClient\Type\RequestInterface` but it doesn't implement it.

Is it a bug in the code generated by the wizard or is it me dosing something wrong?

---
**UPDATE**

I see that `Phpro\SoapClient\Type\RequestInterface` does not contain any methods, it's just a placeholder, so should I simply change my class declaration from `class TranspactHistory` to `class TranspactHistory implements RequestInterface`? If so, then why doesn't the wizard do it automatically?

**Comment by veewee** [comment]
hi @wujekbogdan,

Yes, you have to add that interface.
The wizard can do that automatically if you specify a valid request regex.

**Comment by wujekbogdan** [comment]
@veewee 

You're right -  I didn't provide any regexps for requests/responses. Now, after I ran the wizard providing both regexps everything works fine.

Thanks!
