### ISSUE TITLE
Make it possible to configure the ImmutableSetterAssembler via ImmutableSetterAssemblerOptions and add withTypeHints() method

### ISSUE THREAD

**Issue by wujekbogdan** [phpro/soap-client#210]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

It would be great if we could configure the `ImmutableSetterAssembler()` class using an options class (`ImmutableSetterAssemblerOptions`, for instance) and if the options class had a `withTypeHints()` method.

**Comment by veewee** [comment]
Hi @wujekbogdan,

Can you give me an example of what the code should look like with this option enabled?

**Comment by wujekbogdan** [comment]
> Can you give me an example of what the code should look like with this option enabled?

Sure:

``` php
$assemblerOptions = new Assembler\RequestAssemblerOptions();
$assemblerOptionsWithTypeHints = $assemblerOptions->withTypeHints();

Config::create()
    // ...
    ->addRule(
        new Rules\TypenameMatchesRule(
            new Rules\MultiRule([
                new Rules\AssembleRule(new Assembler\RequestAssembler($options)),
            ]),
            '/(?<!Response)$/i'
        )
    );
```

**Comment by wujekbogdan** [comment]
Let's say that I generate the code for the following API `https://www.transpact.com/SecurePartner/Partner.asmx?WSDL`. The `Type/CreateTranspact` class has a `withUsername` method that, based on the WSDL file, takes a string as an argument.

Here's the generated code:

``` php
/** 
 * @param string $Username
 * @return CreateTranspact
 */
public function withUsername($Username)
{
    $new = clone $this;
    $new->Username = $Username;

    return $new;
}
```

with `withTypeHint(true)` the code should be:

``` php
/** 
 * @param string $Username
 * @return CreateTranspact
 */
public function withUsername(string $Username)
{
    $new = clone $this;
    $new->Username = $Username;

    return $new;
}
```

**Comment by veewee** [comment]
Hi @wujekbogdan,

I've changed some of the terminology above. The correct assembler to do this in is `ImmutableSetterAssembler`.
Sounds loke a good addition. I'dd accept a PR for that.
