### ISSUE TITLE
API XML 

### ISSUE THREAD

**Issue by victorgp89** [phpro/soap-client#215]
Hi,

Sorry for the inconvenience

You also have an api to consume xml? Without wsdl

**Comment by victorgp89** [comment]
The problem is that they ask me for a development for an api that works with XML, without WSDL or XSD, simply an endpoint to receive multiple messages and return an answer, I do not know if that would be possible with this project.

Many thanks for advance,
regards.

**Comment by victorgp89** [comment]
it would be something similar to acting as a soap server but with the specifications of the messages defined by a client

**Comment by veewee** [comment]
This is a client only solution. 
You probably shouldn't be looking at SOAP at all IMO :)
