### ISSUE TITLE
Enum Type Classes not generated

### ISSUE THREAD

**Issue by jangaehler** [phpro/soap-client#217]
I have generated a client according to your gif. Everything looks good and works fine, only the enum classes are missing. 
The generator has recognized the enums and noted the not existing Classes in the docblocks.
Is this a bug, feature or or did I do something wrong?
```    
    /**
     * @return MessageProcessTypeEnumEBOType
     */
    public function getCommunicationProcessType()
    {
        return $this->CommunicationProcessType;
    }

    /**
     * @param MessageProcessTypeEnumEBOType $CommunicationProcessType
     * @return ExternalCommunicationEBOType
     */
    public function withCommunicationProcessType($CommunicationProcessType)
    {
        $new = clone $this;
        $new->CommunicationProcessType = $CommunicationProcessType;

        return $new;
    }
```

**Comment by veewee** [comment]
Hi @jangaehler,

This is a known limitation of using ext-soap.
You can read more about it and how to create enum types here: https://github.com/phpro/soap-client/blob/master/docs/known-issues/ext-soap.md#enumerations
