### ISSUE TITLE
Generated Response Classes are not used in Client

### ISSUE THREAD

**Issue by just-tom** [phpro/soap-client#220]
|    Q        |   A
|------------ | -----
| Version     | 0.7.11

Hi guys, Im using the generator on some open WSDL's to test its functionality before integrating it with the service I need to. It's working great so far, except one problem. The response given is always a MixedResult, so the generate call methods throw an error expecting an instance of a generated Response class. Im not too sure where to go to solve the issue. 

The WSDL file im testing with is:

> http://www.xignite.com/xcurrencies.asmx?WSDL

An example call is:
```
/**
     * @param RequestInterface|Type\ListActiveCurrencies $parameters
     * @return ResultInterface|Type\ListActiveCurrenciesResponse
     * @throws SoapException
     */
    public function listActiveCurrencies(\App\Type\ListActiveCurrencies $parameters) : \App\Type\ListActiveCurrenciesResponse
    {
        return $this->call('ListActiveCurrencies', $parameters);
    }
```
Error Thrown is:

> PHP Fatal error:  Uncaught TypeError: Return value of App\CurrencyClient::listActiveCurrencies() must be an instance of App\Type\ListActiveCurrenciesResponse, instance of Phpro\SoapClient\Type\MixedResult returned in /Users/thomasburman/temp/soap-scaff/src/CurrencyClient.php:30
> Stack trace:
> #0 /Users/thomasburman/temp/soap-scaff/run.php(39): App\CurrencyClient->listActiveCurrencies(Object(App\Type\ListActiveCurrencies))
> #1 /Users/thomasburman/temp/soap-scaff/run.php(48): MyVatClient->getCompanyVatDetails('GB', '282194785')
> #2 {main}

Generated config is:
```
<?php

use Phpro\SoapClient\CodeGenerator\Assembler;
use Phpro\SoapClient\CodeGenerator\Rules;
use Phpro\SoapClient\CodeGenerator\Config\Config;

return Config::create()
    ->setWsdl('http://www.xignite.com/xcurrencies.asmx?WSDL')
    ->setTypeDestination('src/Type')
    ->setTypeNamespace('App\Type')
    ->setClientDestination('src')
    ->setClientName('CurrencyClient')
    ->setClientNamespace('App')
    ->setClassMapDestination('src')
    ->setClassMapName('CurrencyClassmap')
    ->setClassMapNamespace('App')
    ->addRule(new Rules\AssembleRule(new Assembler\GetterAssembler(new Assembler\GetterAssemblerOptions())))
    ->addRule(new Rules\AssembleRule(new Assembler\ImmutableSetterAssembler()))
    ->addRule(
        new Rules\TypenameMatchesRule(
            new Rules\MultiRule([
                new Rules\AssembleRule(new Assembler\RequestAssembler()),
                new Rules\AssembleRule(new Assembler\ConstructorAssembler(new Assembler\ConstructorAssemblerOptions())),
            ]),
            '/(?<!Response)$/i'
        )
    )
    ->addRule(
        new Rules\TypenameMatchesRule(
            new Rules\MultiRule([
                new Rules\AssembleRule(new Assembler\ResultAssembler()),
            ]),
            '/Response$/i'
        )
    )
;
```

Any info will be much appreciated. Thanks

**Comment by janvernieuwe** [comment]
I am getting a valid response when I recreated your client tho.
(Even tho it is an error message)

![image](https://user-images.githubusercontent.com/7813447/52398967-16b93c00-2abb-11e9-891b-adea6e74ca2b.png)

This is the call I made:
```php
<?php

require_once 'vendor/autoload.php';

$client = \App\CurrencyClientFactory::factory('http://www.xignite.com/xcurrencies.asmx?WSDL');
$request = new \App\Type\ListActiveCurrencies();
$response = $client->listActiveCurrencies($request);

dump($response);
```

**Comment by just-tom** [comment]
@janvernieuwe Thanks for getting back to me, I tested with your bootstrap, it does work fine on this and other WSDL files - thanks.

Basically I was using the client completely wrong, it may be worth putting this simple example in the docs for usage?

Thanks very much for your help!

**Comment by janvernieuwe** [comment]
Hi @just-tom how were you using it wrongly then? so we can update the documentation in the best way possible.

**Comment by just-tom** [comment]
Hi @janvernieuwe 
Just opening this one back up again. Firstly apologies for not getting back to you, I didn't see that you had replied!

Secondly, Its got to the point where I need to add HTTP header into my calls. From my understanding this cant be achieved by using the client as above, but instead by using HTTPlug. So have following the same instructions as on here https://github.com/phpro/soap-client/blob/master/docs/handlers/httplug.md to create my client instead, here is the code:

```
<?php

require_once 'vendor/autoload.php';

use Eurostop\EurostopClient;
use Eurostop\Type\CheckVat;
use Http\Adapter\Guzzle6\Client;
use Phpro\SoapClient\Soap\Driver\ExtSoap\ExtSoapEngineFactory;
use Phpro\SoapClient\Soap\Driver\ExtSoap\ExtSoapOptions;
use Phpro\SoapClient\Soap\Handler\HttPlugHandle;
use Symfony\Component\EventDispatcher\EventDispatcher;

$handler = HttPlugHandle::createForClient(
    Client::createWithConfig(['headers' => ['User-Agent' => 'testing/1.0']])
);

$engine = ExtSoapEngineFactory::fromOptionsWithHandler(
    ExtSoapOptions::defaults('http://ec.europa.eu/taxation_customs/vies/checkVatService.wsdl', []),
    $handler
);
$eventDispatcher = new EventDispatcher();
$client = new EurostopClient($engine, $eventDispatcher);

$result = $client->checkVat(new CheckVat('GB', '282194785'));
```

But when running it again gives me the same original issue for Mixed Responses. Am I using this client method incorrectly too?

Any help will be appreciated.
Thanks

**Comment by j-schumann** [comment]
Having the same problem, the wizard-generated type classes for requests/responses are fine but the request classes miss the
`implements RequestInterface`
part and the response classes miss
`implements ResultInterface`
 (with the respective `use` statements). Adding those manually makes the classes work.

**Comment by janvernieuwe** [comment]
Did they match the regexes though?
If not, it is not possible to automatically implement them...

**Comment by RafaelKr** [comment]
I also got the MixedResult problem when using a custom HttplugClient which I need for basic auth.
The solution was adding the classmap.

```php
use Http\Adapter\Guzzle6\Client;
use Phpro\SoapClient\Middleware\BasicAuthMiddleware;
use Phpro\SoapClient\Soap\Driver\ExtSoap\ExtSoapEngineFactory;
use Phpro\SoapClient\Soap\Driver\ExtSoap\ExtSoapOptions;
use Phpro\SoapClient\Soap\Handler\HttPlugHandle;

[...]

private static function getClient(string $wsdl) {
    $handler = HttPlugHandle::createForClient(
        Client::createWithConfig(['headers' => ['User-Agent' => 'testing/1.0']])
    );
    $handler->addMiddleware(
        new BasicAuthMiddleware(getenv('SOAP_BASIC_AUTH_USER'), getenv('SOAP_BASIC_AUTH_PASS'))
    );

    $engine = ExtSoapEngineFactory::fromOptionsWithHandler(
        ExtSoapOptions::defaults($wsdl, [])
            ->withClassMap(QueryMaterialInClassmap::getCollection()),
        $handler
    );

    $eventDispatcher = new EventDispatcher();
    return new QueryMaterialInClient($engine, $eventDispatcher);
}
```


I have to work with a lot of different services, all using the same basic auth. So I wrote a little factory class to create my SOAP clients:

<details>
  <summary>SoapFactory.php</summary>

The file is located in the folder `Soap` in my `src` directory. In it is another folder with all my wsdl files. To create a new soap-client I use the following wizard answers:

```
$ ./vendor/bin/soap-client wizard

 Where would you like to store your config file? [config/soap-client.php]:
 > src/Soap/config/QueryMaterialIn-client.php

 Wsdl location (URL or path to file):
 > src/Soap/wsdl/QueryMaterialIn.wsdl

 Generic name used to name this client (Results in <name>Client <name>Classmap etc.):
 > QueryMaterialIn

 Directory where the client should be generated in:
 > src/Soap/services/QueryMaterialIn

 Namespace for your client:
 > VendorPrefix\PluginName\Soap\Services\QueryMaterialIn
```


```php
<?php

namespace VendorPrefix\PluginName\Soap;

use Http\Adapter\Guzzle6\Client;
use Phpro\SoapClient\Client as PhproSoapClient;
use Phpro\SoapClient\Middleware\BasicAuthMiddleware;
use Phpro\SoapClient\Soap\ClassMap\ClassMapCollection;
use Phpro\SoapClient\Soap\Driver\ExtSoap\ExtSoapEngineFactory;
use Phpro\SoapClient\Soap\Driver\ExtSoap\ExtSoapOptions;
use Phpro\SoapClient\Soap\Handler\HttPlugHandle;
use Symfony\Component\EventDispatcher\EventDispatcher;

class SoapFactory
{
    /**
     * @return PhproSoapClient
     */
    public static function getClient(string $serviceName): PhproSoapClient {
        $wsdl = __DIR__ . "/wsdl/$serviceName.wsdl";
        $clientFqdn = 'VendorPrefix\PluginName\Soap\Services\\' . $serviceName . '\\' . $serviceName . 'Client';

        $engine = ExtSoapEngineFactory::fromOptionsWithHandler(
            ExtSoapOptions::defaults($wsdl, [])
                ->withClassMap(self::resolveClassmapCollection($serviceName)),
            self::createHandler()
        );

        $eventDispatcher = new EventDispatcher();
        return new $clientFqdn($engine, $eventDispatcher);
    }

    private static function resolveClassmapCollection(string $serviceName): ClassMapCollection {
        $classmapFqdn = 'VendorPrefix\PluginName\Soap\Services\\' . $serviceName . '\\' . $serviceName . 'Classmap';
        $classmapCollectionFqdn = ($classmapFqdn . '::getCollection');
        return $classmapCollectionFqdn();
    }

    private static function createHandler(): HttPlugHandle {
        $handler = HttPlugHandle::createForClient(
            Client::createWithConfig(['headers' => ['User-Agent' => 'VendorPrefix\PluginName/1.0']])
        );
        $handler->addMiddleware(
            new BasicAuthMiddleware(getenv('SOAP_BASIC_AUTH_USER'), getenv('SOAP_BASIC_AUTH_PASS'))
        );

        return $handler;
    }
}

```
</details>

**Comment by alexeynefedov-bildbau** [comment]
Hello guys! Have the same issue with MixedResult as @just-tom 

**Return value of A24\Modules\MalteserSoapClient\Soap\MalteserSoapClientClient::auftragErstellen() must be an instance of A24\Modules\MalteserSoapClient\Soap\Type\DTTerminAuftragErstellenResponse, instance of Phpro\SoapClient\Type\MixedResult returned**


Thanks 

```php 
$base64str = file_get_contents(__DIR__.'/testbase64stream_2');
$responseAPI = $client->auftragErstellen(
    new DTTerminAuftragErstellen(
        $anrNr,                  // ok
	 json_encode($person),   // ok
	$_POST['terminblockID'], // ok
	'hausnotruf',            // ok
	$_POST['leistungart'],   // ok
	$base64str               // works if less than 64kb
	)
);
			    			
```
But only, when i give DTO a String, larger as 64kb. Before 64kb all works just fine.

**Comment by veewee** [comment]
@alexeynefedov-bildbau  : That sounds like a strange case. Can you share more about it in a new issue? Looks like either ext-soap is having troubles parsing it to xml - or that the HTTP-layer complains at some point. Are you using httplug as handler (recommended)?

**Comment by alexeynefedov-bildbau** [comment]
@veewee thanks a lot for answering and
yes I'm using httplug; just installed and still have the same issue.
So I'm opening then an issue.
Best regards
