### ISSUE TITLE
DocBlockGenerator allow to set wordrwrap

### ISSUE THREAD

**Issue by dakorpar** [phpro/soap-client#221]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

It's wierd when docblock is over multiple rows:
```
     /**
      * @param 
      * SomeLongNamespace\Type\Blaa
      * $paramName
      *
```

Id like to be able to turn off this, also I'm running phpcbf after this is generated which automatically imports all those

**Comment by janvernieuwe** [comment]
Hi @dakorpar ,

That's a good idea, I'd accept a PR for that.
We are working on a new version too though, but this shouldn't be a huge change.

**Comment by janvernieuwe** [comment]
@dakorpar the new version has just been released (many many thanks to Toon!!!)
If you want to make a PR, you can do it against the new version.

**Comment by dakorpar** [comment]
thanks I'll add PR later today

**Comment by dakorpar** [comment]
There are some usages of DocBlockGenerator:
![screenshot_4](https://user-images.githubusercontent.com/9303856/53491800-8d809e00-3a97-11e9-9b5f-cc99c59ce4a3.png)

also on ClientMethodAssembler is setWordwrap already set

I'm not really sure how to pass config on all those places and how to set that up with your config. I'm not fammiliar with code, but I can add setWordWrap false to all usages easily if that is good enough.

**Comment by MidnightDesign** [comment]
I don't see any reason to allow it to wrap. Wrapping should always be turned off. I'm working on a fix right now.
