### ISSUE TITLE
Custom Middleware

### ISSUE THREAD

**Issue by DaveWeissDotNet** [phpro/soap-client#222]
|    Q        |   A
|------------ | -----
| Version     | 1.0.0

### Support Question

Thank you for this SOAP client - it is great. I've got just about everything figured out when updating to 1.0.0, but I'm struggling with middleware. I see your example for manipulating the XML, but I do not see where or how you actually attach the middleware to the client.

My scenario is that I want to add unique SoapHeaders to the XML every time a soap client method is called. I just don't see how to do that.

Thanks for the help.

**Comment by veewee** [comment]
Hello,

You have to make sure that you are using the HttPlugHandle of another handler that supports Middleware.

Next, you add the Middleware directly to the handler. More info and documentation can be found here:

https://github.com/phpro/soap-client/blob/master/docs/handlers/httplug.md
