### ISSUE TITLE
Set the header

### ISSUE THREAD

**Issue by matheo98** [phpro/soap-client#232]
Hey, 
my request is as follow:

`  <soap:Header>
    <AuthenticationHeader xmlns="http://mobile.crossdesk.com/">
      <Username>PWB_WebServices</Username>
      <Password>526358</Password>
    </AuthenticationHeader>
  </soap:Header>
  <soap:Body>
    <GetCustomerOrderInformation xmlns="http://mobile.crossdesk.com/">
      <orderNumber>940303AA</orderNumber>
    </GetCustomerOrderInformation>
  </soap:Body>`

So I need to set a header for authentification. For me the easiest way should be to access to the __setSoapHeaders from the php clients. But I can't acces to it because it encapsulate on different object with no setter. So if you have any recommadation for this kind of issue let me know ! Thanks guys !

**Comment by veewee** [comment]
Hello @matheo98,

The suggested way of fixing this is by adding a custom HTTP middleware.
More information can be found here:
https://github.com/phpro/soap-client/blob/master/docs/middlewares.md#creating-your-own-middleware

The middleware can change the HTTP request before sending it to the server.
You can attach headers this way:


```php
$xml = SoapXml::fromStream($request->getBody());
$newHeader = $xml->createSoapHeader(); // you can use the logic inside this method to create a namespaced header
// Add info username + password to the header here
$xml->prependSoapHeader($newHeader);
```

You'll need to use the HttPlug handler to enable middleware.
More info: https://github.com/phpro/soap-client/blob/master/docs/handlers/httplug.md

**Comment by avrahamappel** [comment]
I also needed this. Seems like the client should provide a way to do this directly while constructing the request, as it's something that is directly serialized into the XML request body. It feels somewhat backwards to serialize a request into a string, and then unserialize the string again in order to add headers.

**Comment by veewee** [comment]
It depends ... For the example above I agree it might feel like overkill.
However, for more advanced headers like WSSE security headers in which you need to calculate hashes based on particular items in both the soap header and body, it is the most powerfull tool.

If you use the ext-soap driver, you can always use https://www.php.net/manual/en/soapclient.setsoapheaders.php if that makes you feel any better :) However, it is not what I would suggest you to use.

**Comment by avrahamappel** [comment]
@veewee Beyond overkill, it also seems somewhat unstable to create the header in a middleware. Since the middleware doesn't have access to the base client, you can't just pass an instance of `SoapHeader` to the `__setSoapHeaders` method as you normally would. Instead, you have to manually construct an instance of `DOMElement` and append it back into the tree, hoping that you haven't written invalid SOAP or broken some namespace, etc.

Just my two cents. I'll probably go with passing parameters to the factory for now.

**Comment by veewee** [comment]
I'dd say that using middleware is more stable than adding  soap headers through the ext-soap client directly... 

* At least it is testable by not messing around with stream wrappers. Imagine you mistype a namespace in a soap header, how would you know? The middleware provided by this package are fully tested.
* The SoapHeader takes SoapVar as data input, which can be a random broken XML string. At that point, you'll receive a vague SoapFault during request. By using DOM, you at least know the XML is valid and if not, you get a useful exception. (Anyways: The soap XML isn't very hard to work with)
* I wouldn't know why you would ever want the client inside a middleware. At that point, the request was already made. But if you do, you can always inject it manually. (By the way, you could go for an event listener which operates at model level (before/after the HTTP layer) instead: https://github.com/phpro/soap-client/blob/master/docs/events.md)
* using middleware do make sense in a lot of cases: most of the time, you want to add metadata which you want to be available on every request.


In any case, choose whichever weapon suites you well. I wouldn't go for SoapHeaders myself :)

**Comment by avrahamappel** [comment]
@veewee I like the idea of listening for the request event, then I don't have to change handlers to be able to support middleware. But how would I go about using the events system to add headers?

**Comment by veewee** [comment]
Something like this:

```php

class SomeListener
{

	public function __construct(\SoapClient $client) {
		$this->client = $client;
	}

	public function onRequest()
	{
		$this->client->__setSoapHeaders(...);
	}
}
```

However, you'dd still have all the downsides of using setSoapHeaders that I mentioned above ...

**Comment by avrahamappel** [comment]
Where do I get the SoapClient from to pass into the listener? I want to subscribe in the factory method:
```php
public static function factory(
    string $wsdl,
    array $options = []
) {
    $engine = ExtSoapEngineFactory::fromOptions(
        ExtSoapOptions::defaults($wsdl, $options)
                      ->withClassMap(SoapServiceClassmap::getCollection())
    );
    $eventDispatcher = new EventDispatcher();
    $eventDispatcher->addSubscriber(new MyListener()); // <-- What can I pass in here?

    return new SoapServiceClient($engine, $eventDispatcher);
}
```

**Comment by veewee** [comment]
You'll have to unwrap the code inside the factories. It will look like this:

```php

use Phpro\SoapClient\Soap\Driver\ExtSoap\AbusedClient;
use Phpro\SoapClient\Soap\Driver\ExtSoap\ExtSoapDriver;
use Phpro\SoapClient\Soap\Driver\ExtSoap\ExtSoapOptions;
use Phpro\SoapClient\Soap\Driver\ExtSoap\Handler\ExtSoapClientHandle;
use Phpro\SoapClient\Soap\Engine\Engine;

public static function factory(
    string $wsdl,
    array $options = []
) {
    $soapClient = AbusedClient::createFromOptions(
        ExtSoapOptions::defaults($wsdl, $options)
            ->withClassMap(SoapServiceClassmap::getCollection())
    );
    $driver = ExtSoapDriver::createFromClient($soapClient);
    $handler = new ExtSoapClientHandle($driver->getClient());
    $engine = new Engine($driver, $handler);
    
    $eventDispatcher = new EventDispatcher();
    $eventDispatcher->addSubscriber(new MyListener($soapClient));

    return new SoapServiceClient($engine, $eventDispatcher);
}

```

(Note: You might want to switch the handler to httplug, since ext-soap has a big list of known HTTP issues)

**Comment by mfedak-tqgg** [comment]
I too struggled a bit yesterday trying to get Basic Auth working in the recommended way using http plugins and the https://github.com/php-soap/psr18-transport package. After an hour of reading and re-reading the docs (always useful) I got something working.

I used the wizard to generate a client "MyTestClient" and later I modified the generated factory like so:

```php
<?php

use Http\Client\Common\Plugin\AuthenticationPlugin;
use Http\Client\Common\PluginClient;
use Http\Discovery\Psr18ClientDiscovery;
use Http\Message\Authentication;
use Phpro\SoapClient\Caller\EngineCaller;
use Phpro\SoapClient\Caller\EventDispatchingCaller;
use Phpro\SoapClient\Soap\DefaultEngineFactory;
use Soap\ExtSoapEngine\ExtSoapOptions;
use Soap\Psr18Transport\Psr18Transport;
use Symfony\Component\EventDispatcher\EventDispatcher;

...

public static function factory(string $wsdl, array $options = []) 
{
    // Create auth middleware
    $authentication = new Authentication\BasicAuth($options['username'], $options['password']);
    $authenticationPlugin = new AuthenticationPlugin($authentication);

    $clientInterface = Psr18ClientDiscovery::find();
    $pluginClient = new PluginClient($clientInterface, [$authenticationPlugin]);
    $transport = Psr18Transport::createForClient($pluginClient);

    $soapOptions = ExtSoapOptions::defaults($wsdl)->withClassMap(MyTestClientClassmap::getCollection());
    $engine = DefaultEngineFactory::create($soapOptions, $transport);

    $eventDispatcher = new EventDispatcher();
    $caller = new EventDispatchingCaller(new EngineCaller($engine), $eventDispatcher);

    return new MyTestClient($caller);
}

...

```
