### ISSUE TITLE
Response With Headers and Generic Responses

### ISSUE THREAD

**Issue by just-tom** [phpro/soap-client#236]
|    Q        |   A
|------------ | -----
| Version     | v1.0.1
| Driver       | ExtSoapDriver
| Handler    | HttPlugHandle 

### Support Question
Hi guys,

Im successfully sending requests to a SOAP service which is great. But I have a response issue, I keep getting this message returned: 

`The server was unable to process the request due to an internal error.  For more information about the error, either turn on IncludeExceptionDetailInFaults (either from ServiceBehaviorAttribute or from the <serviceDebug> configuration behavior) on the server in order to send the exception information back to the client, or turn on tracing as per the Microsoft .NET Framework SDK documentation and inspect the server trace logs.`

I have spoke to the team im dealing with that run the SOAP Service and they are telling me this is a red heron message and the settings it suggests don't exist.

So I followed a request all the way through with xdebug and can see that the full response gives me a 402:Unauthorised response, what is above is just the body of the stream. 

Now I have two questions:

1) Is what they say about this message true? It's just a generalised message? ( I know this is out of the realm of your library, but thought you may be able to help)

2) I only get given the message rather then all the response data because of `vendor/phpro/soap-client/src/Phpro/SoapClient/Soap/HttpBinding/Converter/Psr7Converter.php:convertSoapResponse` - is there any way to get the full response returned? This way atleast I can test the response and handle it correctly instead of the generic message shown.

Thanks

**Comment by veewee** [comment]
Hi @just-tom,

1. The message is coming from the server. I can't really give you any additional information about that. Do you need to authenticate to the service? Maybe that part is broken? A 402 HTTP response is for "payment required". Maybe you have to pay for the service or they are using a paid component on there server?

2. You can use https://github.com/php-http/logger-plugin to log the full http request + response or create your own middleware for this purpose.
