### ISSUE TITLE
Support chaining of `with*` methods on request

### ISSUE THREAD

**Issue by sjelfull** [phpro/soap-client#237]
### Feature Request

Request classes has the `with*` methods to set properties on the request, which made me assume you could chain them.

After seeing all values except for the first being `NULL`, I found that each `with*` method clones `$this`, sets the prop, and returns a new instance.

This means the following won't work:

```php
$payload
    ->withClientKey($clientKey)
    ->withTerminalID($terminalId)
    ->withAmount(100)
    ->withCardProgram($cardProgram)
    ->withProgramType($programType)
```

Is there any reason for this behaviour? If not, it would be great if it was changed from cloning to just returning `$this`, so that chaining would work.

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | ?
| BC Break    | no?

**Comment by janvernieuwe** [comment]
@sjelfull setters that use `with` are usually immutable setters, this behavior is as expected.
You can chain them, you just need to do it like this:

```php
$payload = $payload
    ->withClientKey($clientKey)
    ->withTerminalID($terminalId)
    ->withAmount(100)
    ->withCardProgram($cardProgram)
    ->withProgramType($programType);
```

**Comment by sjelfull** [comment]
Thank you, that makes sense.
