### ISSUE TITLE
Use of $this->soapClient in debugLastSoapRequest results in "Undefined property" error

### ISSUE THREAD

**Issue by dxvargas** [phpro/soap-client#239]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 1.0.2

#### Summary

There is a regression in [Client::debugLastSoapRequest](https://github.com/phpro/soap-client/blob/1.0.2/src/Phpro/SoapClient/Client.php#L44) introduced in [this commit](https://github.com/phpro/soap-client/commit/5f3cc796b1f1b7c3985627d1a6e125c2b1b99284) and released in 1.0.2.

We can see the original commit [here](https://github.com/dxvargas/soap-client/commit/753ca87e18e94788be7505669e6fbda485fad838), the change was applied to `$this->soapClient` but in the more recent versions what we had there was `$lastRequestInfo` which uses `$this->engine` instead of `$this->soapClient`. Now we can see that `$lastRequestInfo` is still there but it's not used.

It all looks like the conflict mentioned in [this commit](https://github.com/phpro/soap-client/commit/e37513d786e6ea96111cd239bdc5e67217e7e3c2) was not well resolved.

#### Current behavior

With version 1.0.1 unit tests were passing, with version 1.0.2 I have this error:
`Undefined property: RequestClient::$soapClient`

#### How to reproduce

When calling a SOAP method with the client, something like:
`
$client->soapMethod($request);
$debug = $client->debugLastSoapRequest()['request'];
`
I get the error:
`Undefined property: RequestClient::$soapClient`

This can be seen here:
https://drone.fpfis.eu/openeuropa/epoetry-client/257/13
which originated from [this commit|https://github.com/openeuropa/epoetry-client/pull/18/commits/4e4e859ec6b380a45f7522a763554e2e07ae4a17] here:
https://github.com/openeuropa/epoetry-client/pull/18

I hope, if needed, it's easy to put up this environment and reproduce the error there.

#### Expected behavior

No error as before with 1.0.1.

**Comment by veewee** [comment]
Thanks for describing the issue in such a detailed way!
