### ISSUE TITLE
Keep getting failed to connect host error

### ISSUE THREAD

**Issue by yasinn** [phpro/soap-client#242]
|    Q        |   A
|------------ | -----
| Version     | ^1.0

### Support Question
Keep getting following error to a public soap 1.1 web server.
`Exception 'Phpro\SoapClient\Exception\SoapException' with message 'cURL error 7: Failed to connect to 127.0.0.1 port 8080: Operation timed out (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)`

i guess it trying to connect my local address, that ip specified in wsdl file <wsdl:service> block:
`    <wsdl:service name="StandardProviderService">
        <wsdl:port binding="tns:StandardSoap11" name="StandardSoap11">
            <soap:address location="http://127.0.0.1/stand/soap/standard/"/>
        </wsdl:port>
    </wsdl:service>`

Here is the client factory:

`<?php

namespace console\models\Soap;

use console\models\Soap\MyClient;
use console\models\Soap\MyClassmap;
use Symfony\Component\EventDispatcher\EventDispatcher;
use Phpro\SoapClient\Soap\Driver\ExtSoap\ExtSoapEngineFactory;
use Phpro\SoapClient\Soap\Driver\ExtSoap\ExtSoapOptions;
use Http\Adapter\Guzzle6\Client;
use Phpro\SoapClient\Soap\Handler\HttPlugHandle;

class MyClientFactory
{

    public static function factory(string $wsdl) : \console\models\Soap\MyClient
    {
        $handler = HttPlugHandle::createForClient(
            Client::createWithConfig(['headers' => ['Content-Type' => 'text/xml']])
        );

        $engine = ExtSoapEngineFactory::fromOptionsWithHandler(
            ExtSoapOptions::defaults($wsdl, [])
                ->withClassMap(MyClassmap::getCollection()),
                $handler
        );
        $eventDispatcher = new EventDispatcher();

        return new MyClient($engine, $eventDispatcher);
    }

}`

i've used SoapUI to test it and it works fine.
but why soap-client try to connect my local 127.0.0.1:8080?
isn't should be request to http://servicedomain.com/standart.wsdl and routed to internal 127.0.0.1:8080 on the server?

I'm new to soap world. please help.

**Comment by yasinn** [comment]
It was server side configuration issue.

**Comment by veewee** [comment]
Hello @yasinn,

The WSDL is indeed telling your client to look at 127.0.0.1.
You could however override this domain by overwriting the request uri as described here: http://docs.php-http.org/en/latest/plugins/request-uri-manipulations.html

You can for example use the HTTPlug [AddHostPlugin](https://github.com/php-http/client-common/blob/master/src/Plugin/AddHostPlugin.php) for this.

```php
use Http\Client\Common\Plugin\AddHostPlugin;

$plugin = new AddHostPlugin(UriFactoryDiscovery::find()->createUri('https://servicedomain.com'), [
    'replace' => true,
]));
```
