### ISSUE TITLE
Class not found

### ISSUE THREAD

**Issue by abenamer** [phpro/soap-client#245]
|    Q        |   A
|------------ | -----
| Version     | 1.0.3

### Support Question

I can't create a new client. It keeps saying class not found. What am I doing wrong? Every time I try to instantiate a new client by referencing the ClientFactory, it acts like it can't find the ClientFactory.

**Comment by hshhhhh** [comment]
And what exactly are you doing? Have you tried wizard? Have you tried to run wizard in new empty project?

Or do you can't include generated client to your project?

**Comment by abenamer** [comment]
I've tried to run the wizard in a new empty project. The wizard generates the classmaps correctly as well as the Client and ClientFactory files. The problem is when I try to instantiate a client by calling the ClientFactory object. It refused to find that object. I tried to instantiate using code similar to:

```
$client = MyclientFactory::factory($wsdl = 'http://path.to/your.wsdl');
$response = $client->helloWorld(new HelloWorldRequest('name'));
echo $response->getGreeting();
```

That first line is where the error happens. I noticed that another version of the test code in the demo also has a require_once for autoload.php. That doesn't work either for me. I'm on PHP 7.3.

**Comment by hshhhhh** [comment]
So it seems like you have issues with autoloader, right?

```php
$loader = require 'vendor/autoload.php';
$loader->add('namespaceYouUsedInWizard', __DIR__);
$client = MyclientFactory::factory('http://path.to/your.wsdl');
$response = $client->helloWorld(new HelloWorldRequest('name'));
echo $response->getGreeting();
```

**Comment by abenamer** [comment]
My code looks like this: 
```
$loader = require '../vendor/autoload.php';
$loader->add('Client', __DIR__);
$client = AppClientFactory::factory('http://path.to/your.wsdl');
```

Client was the namespace and App was the generic name. I'm still getting the
```
PHP Fatal error:  Uncaught Error: Class 'AppClientFactory' not found
```
error despite the addition of that namespace. I've also tried playing around with autoload.php by doing a composer dump autoloader after adding this to composer.json:
```
      "Client\\" : "src/"
```

**Comment by abenamer** [comment]
OK, I've fixed this -- it was a problem with the autoload settings. What's interesting is that it wasn't set up properly in composer.json upon installation. Is that a bug?

**Comment by veewee** [comment]
Glad you found the issue.

No, i'ts not a but. We are not touching your composer file.
Autoloading is something you'll have to do manually.

**Comment by abenamer** [comment]
Is there any chance the documentation can be revised to include a discussion on namespaces?

**Comment by hshhhhh** [comment]
> Is there any chance the documentation can be revised to include a discussion on namespaces?

You ask strange questions.
Wizard allows you to set up namespace for generating files and it also allows you to set up directory where you want to place generated files.

You can generate them inside of `src/` with root namespace and it will work.

If you do not know how to configure autoloading with composer you can review documentation I mentioned above: https://getcomposer.org/doc/04-schema.md#autoload
