### ISSUE TITLE
ExtSoapDecoder fails to cleanUpTemporaryState on SoapFault Exception

### ISSUE THREAD

**Issue by lukastaferner** [phpro/soap-client#252]
### Bug Report

|    Q        |   A
|------------ | ------
| Version     | 1.0.3

#### Summary

\Phpro\SoapClient\Soap\Driver\ExtSoap\ExtSoapDecoder fails to call cleanUpTemporaryState() if a SoapFault Exception in __soapCall is thrown. The next SOAPcall will not contact the server but return the stored (faulty) response.

#### How to reproduce

Produce a SOAPFault and re-send the request in the same thread. You need to restart thread to clear the cache
#### Expected behavior

The Exception should be cought, and the temporary state should be cleared.

**Comment by veewee** [comment]
Thanks for reporting and fixing!
