### ISSUE TITLE
How to unit test the soap-client in my application

### ISSUE THREAD

**Issue by mohamednagy** [phpro/soap-client#261]
I want to add unit using PHPUnit test to my application so i've to mock the SoapClient. I'm asking how could i mock the soap-client here ?

**Comment by veewee** [comment]
Hello @mohamednagy ,

There are some options:

* For the default ext-soap handle
  * Use php-vcr (https://github.com/php-vcr/php-vcr)
* For the Httplug handle you could use one of those:
  * mock client: https://github.com/php-http/mock-client
  * VCR plugin http://docs.php-http.org/en/latest/plugins/vcr.html
