### ISSUE TITLE
PHP 74 support

### ISSUE THREAD

**Issue by veewee** [phpro/soap-client#267]
Unit tests fail on PHP74. To investigate and fix ....
See Travis:
https://travis-ci.org/phpro/soap-client/jobs/621513849?utm_medium=notification&utm_source=github_status

**Comment by veewee** [comment]
Blocked by

    php-vcr/php-vcr#289
    php-vcr/php-vcr#293

**Comment by janvernieuwe** [comment]
Going to close this as this is resolved sufficiently for now.
We only need a tag from php-vcr, but its not blocking anymore
