### ISSUE TITLE
PEM key authentication configuration

### ISSUE THREAD

**Issue by andrei-dascalu** [phpro/soap-client#269]
|    Q        |   A
|------------ | -----
| Version     | 1.1.0

### Support Question

Hello,

I'm trying to figure out how I can configure phpro/soap-client to use  a pem key for authentication. I've generated the configuration file and next I wanted to generate the client based on it, but the wsdl url requires the use of a pem key.

I'm not sure how to go about configuring that. Do I need a middleware? If so, how can I specify it in the configuration file? I've seen the docs about configuring middlewares but not sure how that fits in the configuration to also wrap around fetching the wsdl.

Cheers

**Comment by veewee** [comment]
Hello @andrei-dascalu 

I assume you want to add a pem as client side certificate to ssl?

There are some options:

* You could use the httplug handler with guzzle as http client and configure the pem file in the cert request option: http://docs.guzzlephp.org/en/stable/request-options.html#cert
* (Or another curl based client that passes the `CURLOPT_SSLCERT` option)
* You could use the native soapclient handler and pass the certificate through `stream_context`: https://www.php.net/manual/en/context.ssl.php

Since this is on the ssl layer, the solution does not involve a Middleware.
If however, you also need the pem certificate to sign the soap request, then the Middleware you are looking for is
https://github.com/phpro/soap-client/blob/master/docs/middlewares.md#wssemiddleware

**Comment by andrei-dascalu** [comment]
@veewee 
Hi and thanks for taking the time to answer (also, Merry Christmas!)

I've tried solution #1 (here's my code)

```php
$myClient =      Client::createWithConfig([
    'headers' => ['User-Agent' => 'testing/1.0'],
    'cert' => [$certPem, $certPass]
]);

$handler = HttPlugHandle::createForClient(
    $myClient
);

$engine = new Engine(
    ExtSoapDriver::createFromOptions(ExtSoapOptions::defaults($wsdl, [])
        ->disableWsdlCache()),
    $handler
);

return Config::create()
    ->setEngine($engine)
... other setters, as generated by wizard
```

Now, if I manually create a Request object and perform a simple GET against the url from $wsdl variable, using the same client, I get the contents of the WSDL. If instead  I  run `generate:client` using the same config, I get an error

```
In AbusedClient.php line 43:

  SOAP-ERROR: Parsing WSDL: Couldn't load from '...?wsdl' : failed to load external entity "...?wsdl"
```

(when running the request manually, I simply use the exact same client instance, perform the request and dump/exit before the config:create() )

**Comment by veewee** [comment]
I forgot to mention you also need a custom wsdl provider:
https://github.com/phpro/soap-client/blob/master/docs/wsdl-providers.md#httplugwsdlprovider

Otherwise the soapclient uses the internal http implementation and it's stream context.

**Comment by andrei-dascalu** [comment]
@veewee just to clarify, does this mean I need to create a  custom driver? From what I see in the ExtSoapDriver, it creates an instance of AbusedClient in its factory method, while ExtSoapOptions does a `new MixedWsdlProvider()` in its constructor, instead of injecting it.

**Comment by veewee** [comment]
No, you can configure it on the soap options class:
https://github.com/phpro/soap-client/blob/master/src/Phpro/SoapClient/Soap/Driver/ExtSoap/ExtSoapOptions.php#L71

It is also described on the page I linked you (at the top: 
https://github.com/phpro/soap-client/blob/master/docs/wsdl-providers.md#get-in-control-of-the-wsdl-file)

**Comment by paulverdu** [comment]
@veewee  I'm having some issues disabling the ssl verification myself. Where can I find how to seal with this? The linked pages about wsdl provider are not available anymore and unfortunately can't find them in the new version of the library.

**Comment by veewee** [comment]
Hello @paulverdu 

You can configure custom WSDL providers that work based on an PSR-18 HTTP client:
https://github.com/php-soap/wsdl#psr18loader

You can select that custom WSDL provider through [ExtSoapOptions](https://github.com/php-soap/ext-soap-engine#extsoapoptions)

In short:

```php
$engine = DefaultEngineFactory::create(
    ExtSoapOptions::defaults($wsdl, [])
        ->withWsdlProvider(
            Psr18Loader::createForClient($psr18Client)
        );
);
```
(Of course, you'll want to configure some other stuff as well, e.g. use the PSR18 transport to use the same http client for doing the actual soap call)


The psr18 client could be guzzle. In this case you can configure it with the option `['verify' => false]`
