### ISSUE TITLE
Add SwA / MTOM attachements middleware 

### ISSUE THREAD

**Issue by veewee** [phpro/soap-client#27]
Make it possible to send / receive attachements in the soap-client.

- SwA: SOAP Messages with Attachments [Spec](https://www.w3.org/TR/SOAP-attachments)
- MTOM: SOAP Message Transmission Optimization Mechanism [Spec](https://www.w3.org/TR/soap12-mtom/)

A sample Jave implementation:
- http://www.codejava.net/java-ee/web-services/using-mtom-to-optimize-binary-data-transfer-with-jax-ws-web-services

Sample PHP implementations:
- https://github.com/debuss/MTOMSoapClient/blob/master/MTOMSoapClient.php
- https://github.com/BeSimple/BeSimpleSoap/blob/master/src/BeSimple/SoapClient/README.md

**Comment by IlGala** [comment]
+1 for veewee are any workarounds available atm?

**Comment by veewee** [comment]
Hello @IlGala,

Currently there isn't a way nor Middleware for this package. I was thinking about creating one that accepts a filebag for sending / storing files and zend-mime to assemble / extract the message.

For the moment I do not have a use-case for this feature nor the time to work it out. Feel free to implement a middleware solution at any time.

There is also another soap library with a slightly different approach. You might want to take a look at:
https://github.com/BeSimple/BeSimpleSoap

**Comment by veewee** [comment]
If somebody knows of a SOAP service which accepts or provides attachement: that would be a good start! :)
