### ISSUE TITLE
Middleware Interface relies upon Http\Client\Common\Plugin

### ISSUE THREAD

**Issue by tm1000** [phpro/soap-client#274]
The middleware interface relies upon Http\Client\Common\Plugin which means you effectively have to install httplug even when writing your own handler (that doesnt need httplug)

Is this intended?

**Comment by tm1000** [comment]
There's also numerous calls to Http\Promise\Promise which is also an httplug library. It seems like even when attempting to write your own handler you have to install httplug.

**Comment by veewee** [comment]
Currently, only the httplug handler accepts middleware. This isn't an existing concept in ext-soap, but we might add something in that handler as well if it makes sense.
Those httplug packages contain a lot of well designed components for creating middleware. We din't want to reinvent the weel there.

Feel free to suggest an improvement if you know of a better way to do this. 

Is there any particular reason you dont want to use httplug?

**Comment by tm1000** [comment]
Well it's not *specifically* stated that middle ware requires httplug (https://github.com/phpro/soap-client/blob/master/docs/middlewares.md#creating-your-own-middleware). Though it is stated it requires a thin wrapper.

It's fair to say you didn't want to reinvent the wheel. But you can't say that people can create their own handlers and their own middleware since they appear to be mutually exclusive. You can *only* create your own middle ware if you use httplug and you can't use middleware if you write your own handler. That should probably be mentioned

As for why I don't want to use httplug. It's being removed from several packages. See here: https://github.com/getsentry/sentry-php/pull/890

> With this PR I'm going to add the support out-of-the-box for Guzzle so that we can switch later the default HTTP client from Httplug Curl which is bugged and far less developed and maintained

Not saying you have to remove it but I wanted to write a pure Guzzle handler. Unfortunately I can't do that as Guzzle could support middleware but I have to install httplug anyways so it negates the whole exercise.

**Comment by veewee** [comment]
True, we might have to put some additional effort in the middleware documentation there and review the middleware system for v2.

Previously, we used guzzle by default but moved to make it http-client independant. (well : as you mentioned above : more or less).
Technically it is possible to create a guzzle handler + use the middleware system. It does require you to use `php-http/promise` and `php-http/client-common` (which is not full httplug - but still 2 additional packages - that last package we could drop if we made some changes to the middleware system).

In that case : you might want to decorate the middleware with something like `ThinGuzzleMiddlewareWrapper(MiddlewareInterface $x)` : in that case you could even use guzzle promises without needing httplug. But thats some work though :)

Personally I would avoid using the `ExtSoapClientHandle`. There are just way too many known, unresolved issues in the HTTP layer of ext-soap.
(https://bugs.php.net/search.php?cmd=display&search_for=ext-soap+http&x=0&y=0)

**Comment by tm1000** [comment]
@veewee ugh! But it's your default driver! :( 

Well that list is pretty daunting. Perhaps I will end up switching to httplug for now or do what you say

**Comment by veewee** [comment]
Yeah ... in a lot of situations it works just fine. It is easier to install + configure and therefor it is the default driver. 
The idea is : if you want more - you can switch to httplug. 
But you might see some strange ext-soap related things before you transistion.

**Comment by tm1000** [comment]
Thanks for all the responses @veewee much appreciated!

**Comment by veewee** [comment]
Thanks for the new insights as well! No problem :)

**Comment by tm1000** [comment]
Side note as well php-http/httplug required in this library is 1.1 while the library itself is at 2.x now. So in here it's very outdated and actually conflicts with sentry's older version that used httplug 2.x

**Comment by veewee** [comment]
Created an issue to keep in mind that upgrade #275.
