### ISSUE TITLE
Enummerations, SimpleTypes and Arrays in Entity generation

### ISSUE THREAD

**Issue by ivoba** [phpro/soap-client#28]
hi, i played a bit around with the library and noticed that some elements of the wsdl i tested werent recognized in the entity generation:

1. simpleTypes are ignored
   `<xs:simpleType name="ExampleState">`

2. enumerations are ignored
```
<xs:enumeration value="Cancelled">
  <xs:annotation>
    <xs:appinfo>
      <EnumerationValue xmlns="http://schemas.microsoft.com/2003/10/Serialization/">4</EnumerationValue>
    </xs:appinfo>
  </xs:annotation>
</xs:enumeration>
```

3. array elements are not converted to arrays
minOccurs & maxOccurs could maybe detect arrays.
```
<xs:complexType name="PriceArray">
  <xs:sequence>
    <xs:element minOccurs="0" maxOccurs="unbounded" name="Price" nillable="true" type="tns:Price"/>
  </xs:sequence>
</xs:complexType>
```

Maybe i did some misconfiguration or you have some idea to circumvent this?

**Comment by veewee** [comment]
Hi @ivoba,

Thanks for logging the issue.

First I want to tell you that this package does not compile the WSDL itself. We are using the built-in [SoapClient::__getTypes()](http://php.net/manual/en/soapclient.gettypes.php) method to fetch the object. We are not planning to add custom WSDL parsing because we want to re-use as much of the existing functionality in ext-soap. In this case: the classmaps. If the `__getTypes()` is not returning a class, it also won't work in the classmap part of ext-soap.

So to answer your questions:

1. This is something I also noticed. You'll probably want to map the simple types to a php type in the code generation. I haven't done this before myself.

2. We mostly fix this by adding some constants to the type and use those one. If you really want to validate the values on the client side, you should write your own assembler for this.

3. We've added the [ItoratorAssembler](https://github.com/phpro/soap-client/blob/master/docs/code-generation/assemblers.md#iteratorassembler) so that you can tell which class is an iterator in the soap generator config. I've used this one before and it works pretty good. The downside: you'll have to configure it yourself in the generator.

**Comment by veewee** [comment]
I moved some comments from unrelated tickets to this one:

Feedback @HKandulla 
> I was thinking about adding support for sequences as in:
```xml
<s:complexType name="ArrayOfSyncCustomerRecord">
  <s:sequence>
    <s:element minOccurs="0" maxOccurs="unbounded" name="SyncCustomerRecord" nillable="true" type="tns:SyncCustomerRecord"/>
  </s:sequence>
</s:complexType>
```
> But I need to investigate a little more. And maybe the IteratorInterface is a good enough solution. If you have an idea of what is needed as far as support for sequences/arrays goes, please let me know.

Feedback from me:
> For sequences, I always use the Iterator. It works well and you can just iterate over the results as you probably always want to do. Let's continue the discussion in #34.

Feedback @HKandulla 
> yes, the iterator is good for parsing the result. But what about creating an object that has an array. In my case I generated the model manually and added a add* method:
```php
/**
 * @var AdDisplayBookRecord
 */
protected $AdDisplayBookRecord = [];

/**
 * @param AdDisplayBookRecord $AdDisplayBookRecord
 * @return $this
 */
public function addAdDisplayBookRecord($AdDisplayBookRecord)
{
    $this->AdDisplayBookRecord[] = $AdDisplayBookRecord;
    return $this;
}
```

**Comment by veewee** [comment]
Hi @HKandulla,

I took the liberty of moving some comments around so that the context is clear to me again and reopend this issue for further discussion.
As you mentioned: the iterator is meant for results so you probably don't need it on request objects.
What is it you would like to achieve? 

As far as I can tell, you want to:
- define default values for properties (e.g. an empty array in this case?)
- make it possible to generate add* methods on an object?

Is this correct? For me this is OK, but I am not sure what the rules should look like to make this possible. E.g: You must know somehow that the array is a list of AdDisplayBookRecords somehow.

**Comment by HKandulla** [comment]
Hi @veewee, thanks for cleaning up the comments. 
Yes, that is exactly what I want to achive.
At the moment this would just make it more convenient and safer to work with sequences but it will propably become a necessarity when you implement strict type hints.
I will try to experiment a little and see, if I come up with somthing.

**Comment by veewee** [comment]
@HKandulla, I bumped against a project we created some time ago. It might also be an idea to add the `\ArrayAccess` interface to the `ArrayOfSyncCustomerRecord` type. That way you can handle it like an array. (More info: http://php.net/manual/en/class.arrayaccess.php)

We used this trait in a project I was working on in combination with the IteratorAssembler.
Since I am not really fond of traits, I did not add it to this package. Maybe the methods beneath could be placed in another code generator.

```php
trait ArrayAccessableIteratorAggregateTrait
{
    /**
     * {@inheritdoc}
     */
    public function offsetExists($offset)
    {
        return $this->getIterator()->offsetExists($offset);
    }

    /**
     * {@inheritdoc}
     */
    public function offsetGet($offset)
    {
        return $this->getIterator()->offsetGet($offset);
    }

    /**
     * {@inheritdoc}
     */
    public function offsetSet($offset, $value)
    {
        return $this->getIterator()->offsetSet($offset, $value);
    }

    /**
     * ({@inheritdoc}
     */
    public function offsetUnset($offset)
    {
        return $this->getIterator()->offsetUnset($offset);
    }
}
```

Now you can use the class as an array and will it that way. Is this something that could work for you?

**Comment by janvernieuwe** [comment]
I had a similar scenario where i have ArrayOfParticularObject strings and created a custom assembler for these methods.

First I created an assembler to make ArrayOf* types extend ArrayObject:
```
<?php

namespace Sanoma\Intersolve\Assembler;

use Phpro\SoapClient\CodeGenerator\Assembler\AssemblerInterface;
use Phpro\SoapClient\CodeGenerator\Context\ContextInterface;
use Phpro\SoapClient\CodeGenerator\Context\TypeContext;

/**
 * Class ArrayObjectAssembler
 * @package Sanoma\Intersolve\Assembler
 */
class ArrayObjectAssembler implements AssemblerInterface
{
    /**
     * @param ContextInterface|TypeContext $context
     *
     * @return bool
     */
    public function canAssemble(ContextInterface $context)
    {
        return $context instanceof TypeContext;
    }

    /**
     * Assembles pieces of code.
     *
     * @param ContextInterface|TypeContext $context
     * @throws \Phpro\SoapClient\Exception\AssemblerException
     */
    public function assemble(ContextInterface $context)
    {
        if (strpos($context->getClass()->getName(), 'ArrayOf') !== 0) {
            return;
        }

        $context->getClass()
            ->setExtendedClass(\ArrayObject::class)
            ->addUse(\ArrayObject::class);
    }
}
```

Internally it should still be an array though, so I also created a setterAssembler on ArrayOf* setters.
This way, when setting an ArrayOf, it is converted into a simple array:

´´´
<?php

namespace Sanoma\Intersolve\Assembler;

use Phpro\SoapClient\CodeGenerator\Assembler\SetterAssembler;
use Phpro\SoapClient\CodeGenerator\Context\ContextInterface;
use Phpro\SoapClient\CodeGenerator\Context\PropertyContext;
use Phpro\SoapClient\CodeGenerator\Context\TypeContext;
use Phpro\SoapClient\CodeGenerator\Util\Normalizer;
use Phpro\SoapClient\Exception\AssemblerException;
use Zend\Code\Generator\DocBlockGenerator;
use Zend\Code\Generator\MethodGenerator;

/**
 * Class ArraySetterAssembler
 * @package Sanoma\Intersolve\Assembler
 */
class ArraySetterAssembler extends SetterAssembler
{

    /**
     * @param ContextInterface|TypeContext $context
     *
     * @return bool
     */
    public function canAssemble(ContextInterface $context)
    {
        return $context instanceof PropertyContext;
    }

    /**
     * Assembles pieces of code.
     *
     * @param ContextInterface|PropertyContext $context
     * @throws \Phpro\SoapClient\Exception\AssemblerException
     */
    public function assemble(ContextInterface $context)
    {
        if (strpos($context->getProperty()->getType(), 'ArrayOf') !== 0) {
            parent::assemble($context);

            return;
        }

        $class = $context->getClass();
        $property = $context->getProperty();
        try {
            $methodName = Normalizer::generatePropertyMethod('set', $property->getName());
            $class->removeMethod($methodName);
            $class->addMethodFromGenerator(
                MethodGenerator::fromArray(
                    [
                        'name'       => $methodName,
                        'parameters' => [$property->getName()],
                        'visibility' => MethodGenerator::VISIBILITY_PUBLIC,
                        'body'       => sprintf('$this->%1$s = (array)$%1$s;', $property->getName()),
                        'docblock'   => DocBlockGenerator::fromArray(
                            [
                                'tags' => [
                                    [
                                        'name'        => 'param',
                                        'description' => sprintf('%s $%s', $property->getType(), $property->getName()),
                                    ],
                                ],
                            ]
                        ),
                    ]
                )
            );
        } catch (\Exception $e) {
            throw AssemblerException::fromException($e);
        }
    }
}
´´´

This way you can use it like this: 

```
$items = new Type\ArrayOfItems();
$items->append(new Type\Item());
```

This way you wont need traits either.
I think you can probably generate add methods in the same way.

**Comment by aderuwe** [comment]
@janvernieuwe @veewee Is the "simpleTypes are ignored" issue another one that should be handled by Assemblers? I'm struggling with this in the EWS API.

**Comment by HKandulla** [comment]
Hi @veewee,

I came across this requirement again, so I followed @janvernieuwe example and created a "FluentAdderAssembler". It's a propertyAssembler that checks the classname for a certain beginning and ads a addProperty.
If you think this is valuable for others, I would create a PR. Let me know.
Below is my current implementation. If you welcome a PR, I would clean it up and provide tests.

Best, Hannes

`<?php

namespace App\Adpoint\Soap\Assembler;

use Phpro\SoapClient\CodeGenerator\Assembler\AssemblerInterface;
use Phpro\SoapClient\CodeGenerator\Context\ContextInterface;
use Phpro\SoapClient\CodeGenerator\Context\PropertyContext;
use Phpro\SoapClient\CodeGenerator\Util\Normalizer;
use Phpro\SoapClient\Exception\AssemblerException;
use Zend\Code\Generator\DocBlockGenerator;
use Zend\Code\Generator\MethodGenerator;

/**
 * Class AdderAssembler
 *
 * @package Phpro\SoapClient\CodeGenerator\Assembler
 */
class FluentAdderAssembler implements AssemblerInterface
{
    /**
     * @var FluentAdderAssemblerOptions
     */
    private $options;

    /**
     * AdderAssembler constructor.
     *
     * @param FluentAdderAssemblerOptions $options
     */
    public function __construct(FluentAdderAssemblerOptions $options)
    {
        $this->options = $options;
    }

    /**
     * {@inheritdoc}
     */
    public function canAssemble(ContextInterface $context): bool
    {
        return $context instanceof PropertyContext;
    }

    /**
     * @param ContextInterface|PropertyContext $context
     *
     * @throws AssemblerException
     */
    public function assemble(ContextInterface $context)
    {
        $class = $context->getClass();
        $properties = $context->getType()->getProperties();

        // only assemble adder-method if className corresponds to given scheme
        if (strpos($context->getClass()->getName(), $this->options->getClassName()) !== 0) {
            return;
        }

        // only assemble adder-method if className contains exactly one property
        if (count($properties) !== 1) {
            return;
        }

        $property = $context->getProperty();
        try {
            $parameterOptions = ['name' => $property->getName()];
            if ($this->options->useTypeHints()) {
                $parameterOptions['type'] = $property->getType();
            }
            $methodName = Normalizer::generatePropertyMethod('add', $property->getName());
            $class->removeMethod($methodName);
            $class->addMethodFromGenerator(
                MethodGenerator::fromArray(
                    [
                        'name' => $methodName,
                        'parameters' => [$parameterOptions],
                        'visibility' => MethodGenerator::VISIBILITY_PUBLIC,
                        'body' => sprintf(
                            '$this->%1$s = is_array($this->%1$s) ? $this->%1$s : [];%2$s$this->%1$s[] = $%1$s;%2$sreturn $this;',
                            $property->getName(),
                            $class::LINE_FEED
                        ),
                        'docblock' => DocBlockGenerator::fromArray(
                            [
                                'tags' => [
                                    [
                                        'name' => 'param',
                                        'description' => sprintf('%s $%s', $property->getType(), $property->getName()),
                                    ],
                                    [
                                        'name'        => 'return',
                                        'description' => '$this',
                                    ],
                                ],
                            ]
                        ),
                    ]
                )
            );
        } catch (\Exception $e) {
            throw AssemblerException::fromException($e);
        }
    }
}
`


`<?php

namespace App\Adpoint\Soap\Assembler;

/**
 * Class AdderAssemblerOptions
 */
class FluentAdderAssemblerOptions
{
    /**
     * @var bool
     */
    private $typeHints = false;

    /**
     * @var string
     */
    private $className = 'ArrayOf';

    /**
     * @return FluentAdderAssemblerOptions
     */
    public static function create(): FluentAdderAssemblerOptions
    {
        return new self();
    }

    /**
     * @param bool $typeHints
     *
     * @return FluentAdderAssemblerOptions
     */
    public function withTypeHints(bool $typeHints = true): FluentAdderAssemblerOptions
    {
        $new = clone $this;
        $new->typeHints = $typeHints;

        return $new;
    }

    /**
     * @param string $className
     *
     * @return FluentAdderAssemblerOptions
     */
    public function setClassName(string $className): FluentAdderAssemblerOptions
    {
        $new = clone $this;
        $this->className = $className;

        return $new;
    }

    /**
     * @return bool
     */
    public function useTypeHints(): bool
    {
        return $this->typeHints;
    }

    /**
     * @return string
     */
    public function getClassName(): string
    {
        return $this->className;
    }
}
`

**Comment by janvernieuwe** [comment]
Hi @HKandulla,

That looks pretty neat!

I would be willing to accept a PR for that, but i'd change the `str_pos` match to a regex, so you can easily check endswith or startswith (or whatever exotic regex you can imagine).

If you create a PR, please also add a little documentation for this, so people know how to use it.

**Comment by HKandulla** [comment]
Hi @janvernieuwe,
great. I will prepare a PR in the next days.
Are you happy with the naming, FluentAdderAssembler?
Best, Hannes

P.S.: What do think about having a BasePropertyAssembler- and a BasePropertyAssemblerOption-class that provide the following options and corresponding methods:
- useTypeHints
- useNullableTypeHints
- useReturnTypes
- useNullableReturnTypes
- maybe even a makeFluent option

That way you could eliminate a lot of duplicate code in final property assembler and make all property assemblers provide the same base options. If you want, I could create these base classes and make the FluentAdderAssembler the first to use these base classes. The other property assembler could be rewritten to use these base classes bit by bit. Let me know, if you like the idea.

**Comment by janvernieuwe** [comment]
Hi @HKandulla ,

Maybe something like `ArrayAddMethodAssembler` covers it more?

We're not entirely sure about the base assemblers, enough components would need common settings, and we also want to watch out to not lock ourselves out of the options zend-code offers.

But we'll take a look at some possibilities to make life a little easier when making assemblers.
