### ISSUE TITLE
RemoveEmptyNodesMiddleware removes root node

### ISSUE THREAD

**Issue by ro0NL** [phpro/soap-client#286]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 1.1.2

#### Summary

`RemoveEmptyNodesMiddleware` is great, however when sending an "unfilled object" (e.g. all properties are null), the node removal bubbles up to the root node.

This breaks the soap format in general, and produces an application error during `Client::call()`:

```
Warning: DOMDocument::loadXML(): Start tag expected, '&lt;' not found in Entity, line: 2
```

I think we should always send an "empty soap envelope" , thus preserving `<SOAP-ENV:Envelope /`> and perhaps an empty body/method node as well?

Input xml:

```
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://method" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
   <SOAP-ENV:Body>
      <ns1:method>
         <arg xsi:nil="true" />
      </ns1:method>
   </SOAP-ENV:Body>
</SOAP-ENV:Envelope>
```

Output xml:

```
<?xml version="1.0" encoding="UTF-8"?>
```

Expected output XML:

```
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://method" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" />
```

or

```
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://method" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
   <SOAP-ENV:Body />
</SOAP-ENV:Envelope>
```

or

```
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://method" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
   <SOAP-ENV:Body>
      <ns1:method />
   </SOAP-ENV:Body>
</SOAP-ENV:Envelope>
```

Thoughts? This should improve debugging as well :)

**Comment by veewee** [comment]
Hi @ro0NL,

That's an interesting case.
The answer depends on what the server accepts though.
I would assume you at least need the envelope but prefer to stop at the method tag.

We could change the xpath in the middleware to something like `//soap:Body/*//*[not(node())]` ?

**Comment by ro0NL** [comment]
That seems to improve thing yes :+1: 

Before: `Warning: DOMDocument::loadXML():`
After: a soap response with the expected `<s:Fault>` in its envelope body

the actual xml going down the wire is now:

```
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://method" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
   <SOAP-ENV:Body>
      <ns1:method />
   </SOAP-ENV:Body>
</SOAP-ENV:Envelope>
```

Im not a SOAP expert (yet), but i believe this change is actually required to call argument-less methods, isnt it?

**Comment by veewee** [comment]
Why are you retreiving the soap fault?
Is this expected behaviour in the implementation you are writing?
Does the soap server accept argument-less methods?
Another option might be to disable the middleware for this specific request?

**Comment by ro0NL** [comment]
> Why are you retreiving the soap fault?

i figure we dont send all required attributes :) however, the backend doesnt expect/support "nil" nodes. So they do need to be left out for sure, in case we dont have a value.

> Is this expected behaviour in the implementation you are writing?

nope :) but nor was `Warning: DOMDocument::loadXML(): Start tag expected`

in practice this is not a real issue for us, as we do need to specify some required arguments.

i discoverd this behavior after chaning the generated constructor to setters.

Our code still used the constrcutor like `$r = new MethodRequest('arg')` which is now ignored, leaving us with an "unfilled object".

> Does the soap server accept argument-less methods?

in our case it's not relevant, but it could be an issue for anyone trying legitimate to do something like

```php
$request = new Method();
$client->method($request);
```

if i understand correctly.

**Comment by veewee** [comment]
Based on your information, it might make more sense to change the xpath to: `//*[@xsi:nil and not(node())]`.
(in that case we also need to register xsi to `http://www.w3.org/2001/XMLSchema-instance`)
However, that won't result in an incremental parent tag cleanup. Would that be an issue?

In the case of an invalid request, the SoapFault that's being triggered should be sufficient.

**Comment by ro0NL** [comment]
@veewee not sure. In our case, using native ext-soap, the xsi namespace is already in place.

Updating the xpath generally spoken works.. but now emptyt nodes without a nil attribute are preserved.. we dont expect this either :)

overall, i think the best general purpose fix is to reduce the XML to:

```
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns1="http://custom"><SOAP-ENV:Body/></SOAP-ENV:Envelope
```

thus `//soap:Envelope/*//*[not(node())]`

**Comment by ro0NL** [comment]
In our case we get `The body of the message cannot be read because it is empty.`

Which is the expected soapfoalt for an unfilled request.

**Comment by veewee** [comment]
`//soap:Envelope/*//*[not(node())]` looks good as well. Feel free to provide a PR.
