### ISSUE TITLE
Client.php may return MixedResponse, but the generated client never expects it, thus causing a PHP error

### ISSUE THREAD

**Issue by rimas-kudelis** [phpro/soap-client#289]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no?
| Version     | 1.1.2

#### Summary

In some cases (I haven't debugged this yet, but invalid response maybe?), Phpro\SoapClient\Client returns a MixedResponse object:
https://github.com/phpro/soap-client/blob/390acc42bb70e7d7bf7cc543beb81524fa322ab4/src/Phpro/SoapClient/Client.php#L109-L111 

However, the generated Client class typehints return types of all its methods the respective response class:
https://github.com/phpro/soap-client/blob/ca17617f765f0f6cf9fd02b231731d27b16cf0bc/src/Phpro/SoapClient/CodeGenerator/Assembler/ClientMethodAssembler.php#L49-L64

This causes PHP errors like this:
Error: "Return value of App\Client\MyClient::getSomething() must be an instance of App\Client\Type\SomethingResponse, instance of Phpro\SoapClient\Type\MixedResult returned."

I surely hope that this not the expected behavior? :)

**Comment by veewee** [comment]
Hello @rimas-kudelis,

What is in the MixedResponse?
It looks like the wrapped object does not have a `ResponseInterface` class.
Therefor it is being wrapped in a MixedResponse.

If it is a scalar type, the WSDL might be incorrect.

**Comment by rimas-kudelis** [comment]
I haven't yet managed to see what's in the response. I'm performing hundreds of requests and I guess I'm just getting throttled, and the WSDL might indeed not account for that case, but still I don't feel like returning something else than the method is supposed to according to its own typehint is the right thing to do. I suppose a proper way would be throwing a specific exception maybe? That would be easier to debug (assuming it would contain response data) and handle (since it wouldn't just be a generic TypeError anymore) I think.

**Comment by veewee** [comment]
The generated client is an easy to use access-point to tie it all together.
We don't know what the ext-soap driver is actually returning at that moment.
What you can do is improve your code generation:

* Load all methods from the metadata
* Do a distinct response type lookup
* Make sure that the generated types that match the lookup contain `ResponseInterface`

That should most likely fix your issue.

We could indeed add complexity by throwing an exception, but now php throws a TypeError which basically is an exception.
Another option would make the strict return types optional in the generator.

Feel free to provide some detailed information if you do feel that this is a bug after investigation.

**Comment by rimas-kudelis** [comment]
I'm not sure I follow you with regard to improving code generation: the `soap-client` script from this package was used to generate the code in question, and the TypeError is triggered in that generated code. All our code is placed in a separate service class, which makes calls to the generated client class.
Regarding TypeError, the inconvenient thing about it is that it's just too generic. Having a specific exception class denoting that a bad response was received would just make it easier to debug and handle this particular case.

**Comment by rimas-kudelis** [comment]
Oh, I forgot, I already had a `dump()` call placed before the `$result = new MixedResult($result);` line. It just dumps a `null`. :(

**Comment by veewee** [comment]
Which HTTP handler are you using?
The default ext-soap handler has some limitations which might result in a `null`  response (e.g. when the server returns Chunked content).
In that case: can you try using this one?
https://github.com/phpro/soap-client/blob/master/docs/handlers/httplug.md

**Comment by rimas-kudelis** [comment]
Yes, I'm using the default one at the moment. I've added a `dump()` call to `Phpro\SoapClient\Soap\Engine\Engine` just to see what the driver returns, but this hasn't been triggered yet. I'll try the alternative handler, thanks!
How come you don't have a Guzzle handler though? :)

**Comment by rimas-kudelis** [comment]
Erm, but would you consider a PR which throws an custom exception instead of creating a MixedResult?

**Comment by veewee** [comment]
Current implementation has its reason: there are soap servers that return scalar types. Therefore the mixed result was added.
I don't think it's a good idea to break this functionality.

However, you can add a custom assembler to overwrite the generated method bodies in your codebase.
More Info:
* https://github.com/phpro/soap-client/blob/master/docs/code-generation/assemblers.md#creating-your-own-assembler
* https://github.com/phpro/soap-client/blob/master/src/Phpro/SoapClient/CodeGenerator/Assembler/ClientMethodAssembler.php

**Comment by rimas-kudelis** [comment]
I see, thanks for the info. I wasn't aware that this might be intended.
Changing the backend to HttPlug seems to have worked, so I guess I can live with this. :)
