### ISSUE TITLE
Examples exclude use statements

### ISSUE THREAD

**Issue by chrissound** [phpro/soap-client#29]
On this page: https://github.com/phpro/soap-client/blob/master/docs/usage.md

It is not import the classes `Logger`?

**Comment by veewee** [comment]
You can use any psr-3 compatible browser. E.g. monolog.
Maybe we could add some additional info at this page:
https://github.com/phpro/soap-client/blob/master/docs/plugins/logger.md

**Comment by chrissound** [comment]
My point is , the missing `use` statements. If you put that code in a test PHP file you'll have to in addition figure out / automagically import those classes.

**Comment by veewee** [comment]
There is no logger class available by default. You'll always have to import it manually.

**Comment by chrissound** [comment]
Can that be mentioned in the example then? I think ideally you want examples to be as functional as possible.
