### ISSUE TITLE
Generate public properties for type classes

### ISSUE THREAD

**Issue by ro0NL** [phpro/soap-client#294]
(follow up issue of https://github.com/phpro/soap-client/issues/291)

I'd like to replace private properties with getters and setters by public properties instead.

I tried

```diff
-    ->addRule(new Rules\AssembleRule(new Assembler\GetterAssembler()))
-    ->addRule(new Rules\AssembleRule(new Assembler\SetterAssembler()))
+    ->addRule(new Rules\AssembleRule(new Assembler\PropertyAssembler('public')))
```

The getters/setters were removed, but properties remain private. As such i invoke `sed -i 's/private \$/public \$/' src/Sdk/*.php` right after, to workaround.

I figured it's probably a new feature, as i dont have time to debug the current code generation flow.

Of course, i may be missing it :)

**Comment by veewee** [comment]
Hello,

It's because you add the assembler.
The config comes shipped with the private properties assembler.
If you add the public one, the assembler skips that one since the property is already known.
Instead, you need to overwrite the configuration ruleset.

**Comment by ro0NL** [comment]
Clear. Thanks for the insight.

For future reference, it works like:

```php
    ->setRuleSet(new Rules\RuleSet([
        new Rules\AssembleRule(new Assembler\PropertyAssembler('public')),
        new Rules\AssembleRule(new Assembler\ClassMapAssembler()),
        new Rules\AssembleRule(new Assembler\ClientMethodAssembler()),
        // ...
    ]))
```
