### ISSUE TITLE
Add return to generate:classmaps

### ISSUE THREAD

**Issue by GaryJones** [phpro/soap-client#30]
Currently the `generate:classmap` command produces:

```php
<?php

use Phpro\SoapClient\Soap\ClassMap\ClassMapCollection;
use Phpro\SoapClient\Soap\ClassMap\ClassMap;

new ClassMapCollection([
...
]);
```

If this is intended to be dropped into a standalone file (evidenced by the opening delimiter and `use` statements, and then used with the ClientBuilder `withClassmaps()`, then it would be handier to include the `return` in it too:

```php
<?php

use Phpro\SoapClient\Soap\ClassMap\ClassMapCollection;
use Phpro\SoapClient\Soap\ClassMap\ClassMap;

return new ClassMapCollection([
...
]);
```

**Comment by veewee** [comment]
We currently always paste it in a factory class like the one beneath. Maybe it's better to generate something like that?
The command can surely get improvements.

```php
declare(strict_types = 1);

namespace Some\Soap;

use Phpro\SoapClient\Soap\ClassMap\ClassMapCollection;
use Phpro\SoapClient\Soap\ClassMap\ClassMap;

class ClassMapFactory
{
    /**
     * @return ClassMapCollection
     */
    public function factory() : ClassMapCollection
    {
        return new ClassMapCollection([
            // ClassMaps
        ]);
    }
}
```

**Comment by GaryJones** [comment]
> We currently always paste it in a factory class like the one beneath.

The current documentation doesn't make that specifically clear, but +1 for adding more of the boilerplate to command output - it's easier to stripe out / just copy and paste certain bits if someone wants to implement this in a different way.

**Comment by snc** [comment]
You can simply append `| sed 's/new ClassMapCollection/return new ClassMapCollection/'` to the `generate:classmap` command.

**Comment by veewee** [comment]
The command will be changed so that the code is actually written to a file instead.
This way, we can create a "wizzard" command to get you up and running with this project in no time.

**Comment by GaryJones** [comment]
FWIW, my Composer script happens to copy what @snc had posted:

```json
"soap-client generate:classmap --config config/generate.php | sed -e 's/^new/return new/' > config/classmaps.php",
```

The full Composer script:

```json
"generate-classmaps": [
      "soap-client generate:classmap --config config/generate.php | sed -e 's/^new/return new/' > config/classmaps.php",
      "phpcbf -q config/classmaps.php > /dev/null || true",
      "echo \"Classmaps saved to config/classmaps.php.\""
    ],
```

**Comment by veewee** [comment]
The command will be improved in #105.
