### ISSUE TITLE
SoapClient with authentication

### ISSUE THREAD

**Issue by devsimo** [phpro/soap-client#303]
Hi,

For the example: https://github.com/phpro/soap-client/blob/master/docs/usage.md

How can I use the SoapClient with authentication? 

Gives the following header XML:

   <SOAP-ENV: Header>
     <ns1: Auth>
       <ns1: UserName> USERNAME </ ns1: UserName>
       <ns1: Password> PASSWORD </ ns1: Password>
     </ ns1: Auth>
   </ SOAP-ENV: Header>

Thanks,
Best Regards.

**Comment by bucari** [comment]
Hi, did you find how use the SoapClient with authentication?

**Comment by veewee** [comment]
Hello,

You can do this by adding soap headers
https://github.com/php-soap/xml#soapheaders

Ideally, you put this logic in a http Middleware.
https://github.com/php-soap/psr18-transport#usage
