### ISSUE TITLE
Problem with type Object in wsdl ( Cannot use 'Acme\Object' as class name as it is reserved )

### ISSUE THREAD

**Issue by gitlog** [phpro/soap-client#308]
|    Q        |   A
|------------ | -----
| Version     | 1.2.0

### Problem with type Object in wsdl

Error:
>Trying to patch ... PHP Fatal error: Cannot use 'Acme\Object' as class name as it is reserved

The base type Object is described in wsdl (this is a third-party service), how to make alias for it since it is reserved in php.
I wanted to do it through type-converter, but in the documentation there is no example on custom types https://github.com/phpro/soap-client/blob/master/docs/type-converter.md

**Comment by veewee** [comment]
This error only occurs if there are multiple "object" types inside your WSDL.
You might also want to use the logic from #302 to intersect many object types into 1 object type.

**Comment by gitlog** [comment]
> This error only occurs if there are multiple "object" types inside your WSDL.
> You might also want to use the logic from #302 to intersect many object types into 1 object type.

So the solution is #309 or #302?
How soon will the new next release be?

**Comment by veewee** [comment]
#309 fixes the fatal error
#302 allows that the file doesn't need patching


Hopefully we'll release soon. There is no deadline at the moment.

**Comment by gitlog** [comment]
@veewee Thanks for the help, I forked, I will wait for the release.
