### ISSUE TITLE
How to connect to SOAP server

### ISSUE THREAD

**Issue by Droutin** [phpro/soap-client#313]
Hi, How can I connect to SOAP server with this repo? I want to connect to this server http://test-api.xml.agency/SiteCity

**Comment by janvernieuwe** [comment]
Hi,

Have you checked the steps in the documentation [here](https://github.com/phpro/soap-client#getting-your-soap-integration-up-and-running)?

**Comment by Droutin** [comment]
It is all about "YOUR" soap client.

**Comment by janvernieuwe** [comment]
Your refers to the client you can create, using our package.
I hope that clears things up?

**Comment by janvernieuwe** [comment]
Closing this issue, if documentation update is needed, you can still reply.
