### ISSUE TITLE
debugLastSoapRequest fails when using php-http/message 1.9.0

### ISSUE THREAD

**Issue by tm1000** [phpro/soap-client#317]
### Bug Report

This is actually partially related to #314. Specifically https://github.com/php-http/message/blob/9af3759d32a2cc6d91141c1cf1ed1cc32dd867ef/CHANGELOG.md#190---2020-08-17

> Omitted binary body in FullHttpMessageFormatter. `[binary stream omitted]` will be shown instead.

```
PHP Warning:  DOMDocument::loadXML(): Start tag expected, '<' not found in Entity, line: 1 in /usr/src/lib/vendor/phpro/soap-client/src/Phpro/SoapClient/Util/XmlFormatter.php on line 15
```

The reasoning is because https://github.com/phpro/soap-client/blob/717b1bf7476b9a225656c3e02d5835ea80699b38/src/Phpro/SoapClient/Client.php#L66 treats the string it gets as XML but `[binary stream omitted]` is returned.

Downgrading php-http/message to 1.8.0 works. I'm not sure how to fix this without digging in deeper.

**Comment by janvernieuwe** [comment]
Hi @tm1000 ,

Could you try using `dev-master`?
If this fixes if for you we'll tag a new release to roll out the fix.

**Comment by janvernieuwe** [comment]
Fix is in new release https://github.com/phpro/soap-client/releases/tag/v1.3.1
I'm closing this issue, if you still have issues after updating feel free to reopen this issue.

**Comment by tm1000** [comment]
I don't see a recent commit for this? Unless it's somewhere else?

**Comment by janvernieuwe** [comment]
Hi @tm1000 

It is related to [this commit](https://github.com/phpro/soap-client/commit/9b4849776200f9575f4ac2fc8efce06086b8030f) .
