### ISSUE TITLE
easiest way to encode request with security (wss) header

### ISSUE THREAD

**Issue by ulfw** [phpro/soap-client#318]
I´m looking for a way to extend the generated soapclient to accept a username and password to create a soap wss header.
Do I have to create an own driver or an own engine and modify the generated client factory ? Is there an example?

**Comment by veewee** [comment]
Depending on what you want to do exactly, you might want to use the wsse Middleware for that:
https://github.com/phpro/soap-client/blob/master/docs/middlewares.md#wssemiddleware

If you only want to add a soap header, you can create a custom middleware for that:
https://github.com/phpro/soap-client/blob/master/docs/middlewares.md#creating-your-own-middleware

The way to go here is middleware imo

**Comment by ulfw** [comment]
If I understand correctly I have to use HTTPlug for using middleware. I currently dont do that and to be honest I dont want to because its increasing the complexity to me.

**Comment by veewee** [comment]
So what do you want? :)

Another option is to create your own handler based on the `ExtSoapClientHandle` and add the [WSS specific stuff](https://github.com/robrichards/wse-php) in there.
However, WSSE can be [quite complex](https://github.com/phpro/soap-client/blob/master/test/fixtures/soap/reference/wsse-encrypted-request.xml). So I doubt that writing your own handler is less complex than requiring some composer packages.

Besides that: the ext-soap HTTP layer has it's own limitations as well.

**Comment by ulfw** [comment]
Ok, thanks for pointing to httplug, it was not that difficult that I thought.
I created an own middlware class based on [wss middleware](https://github.com/robrichards/wse-php), but without encryption and a new factory to configure my client.
