### ISSUE TITLE
batch client creation

### ISSUE THREAD

**Issue by ulfw** [phpro/soap-client#319]
I have a (larger) list of webservices and want to batch create the clients.

So I put them in an array ['ServiceName' => 'WSDL', 'AnotherService' => 'AnotherWSDL', ...]

How can I configure the wizard or use the classes to generate all clients with classmap and factory?
I want to set TypeDestination, output directory and namespace to 'ServiceName'

Any advice to handle this?

**Comment by veewee** [comment]
Currently you require a config file for every service.
You could however, create a file with the base config and only overwrite the changing part.
