### ISSUE TITLE
Create generate:types destination if it doesn't exist

### ISSUE THREAD

**Issue by GaryJones** [phpro/soap-client#32]
If one runs `soap-client generate-types --config=...`, but the `setDestination` key in the config doesn't exist, it will generate misleading information:

```
PHP Warning:  file_put_contents(src/SoapTypes/GetContracts.php): failed to open stream: No such file or directory in /path/to/vendor/phpro/soap-client/src/Phpro/SoapClient/Util/Filesystem.php on line 55

Warning: file_put_contents(src/SoapTypes/GetContracts.php): failed to open stream: No such file or directory in /path/to/phpro/soap-client/src/Phpro/SoapClient/Util/Filesystem.php on line 55
Generated class GAA\CorpManagerApi\SoapTypes\GetContracts to src/SoapTypes/GetContracts.php

{repeat for each class}
```

That's two warnings, and then an incorrect success message, per class, since the file is never saved.

Once the destination folder (empty) is manually created, then the files are generated as intended.

Could the `generate:type` command at least try and create the destination directory if it doesn't exist, or give a more helpful warning and die immediately, if it can't?

**Comment by janvernieuwe** [comment]
I think this issue can be closed.
PR https://github.com/phpro/soap-client/pull/71 added a line ( src/Phpro/SoapClient/Console/Command/GenerateTypesCommand.php:120 ) to ensure the directory exists, and if not attempts to create it.
When it fails, it throws useful exceptions.
