### ISSUE TITLE
Invalidating permanent location with CachedWsdlProvider

### ISSUE THREAD

**Issue by ro0NL** [phpro/soap-client#320]
Hi,

`CachedWsdlProvider` seems rather useful, however we were unable to invalidate the local file to our needs (e.g. when the http cache invalidates in redis), to enforce a fresh load.

I've created this variant, you may want to consider it here too:

```php
<?php

declare(strict_types=1);

namespace App\Soap;

use Phpro\SoapClient\Wsdl\Loader\WsdlLoaderInterface;
use Phpro\SoapClient\Wsdl\Provider\WsdlProviderInterface;
use Psr\Cache\CacheItemPoolInterface;
use Symfony\Component\Filesystem\Filesystem;

class CachedWsdlProvider implements WsdlProviderInterface
{
    protected WsdlLoaderInterface $loader;
    protected CacheItemPoolInterface $wsdlCache;
    protected Filesystem $filesystem;
    protected string $wsdlCacheDir;
    protected array $localCache = [];

    public function __construct(
        WsdlLoaderInterface $loader,
        CacheItemPoolInterface $wsdlCache,
        Filesystem $filesystem,
        string $wsdlCacheDir
    ) {
        $this->loader = $loader;
        $this->wsdlCache = $wsdlCache;
        $this->filesystem = $filesystem;
        $this->wsdlCacheDir = $wsdlCacheDir;
    }

    public function provide(string $source): string
    {
        if (isset($this->localCache[$source])) {
            return $this->localCache[$source];
        }

        $cacheKey = md5($source);
        $cacheFile = $this->wsdlCacheDir.'/'.$cacheKey.'.wsdl';

        if (!$this->filesystem->exists($cacheFile) || !$this->wsdlCache->hasItem($cacheKey)) {
            $wsdl = $this->wsdlCache->getItem($cacheKey);
            if (!$wsdl->isHit()) {
                $wsdl->set($this->loader->load($source));
                $this->wsdlCache->save($wsdl);
            }

            $this->filesystem->dumpFile($cacheFile, $wsdl->get());
        }

        return $this->localCache[$source] = $cacheFile;
    }
}
```

This could be further enhanced with some sort of debug flag (`%kernel.debug%` in Symfony) to avoid e.g. the redis check.

**Comment by veewee** [comment]
In this case you store the wsdl twice + you fill your redis with the WSDL, which can be rather big.

Is there a specific reason why you want to periodically invalidate the cache?
Most of the time, the service doesnt really change (which is what those services should strive for anyways)

This is how I use the CachedWsdlProvider:

The project contains a "cache:wsdl" command which is triggered during build.
This means the cache stays filled untill next release or the next time we call the script manually.

If the soap service changes, that would mean our client should change as well => release.
You can always build a new cache by triggering the cache command.

**Comment by ro0NL** [comment]
hm, that's an interesting thought. However, this could also well involve schema bugfixes upstream (let's not take semver/api versioning into account plz :grin: )

So i started to mimic PHP's default behavior, soley for decouping purposes given its defaults of `WSDL_CACHE_DISK` for a day (86400).

**Comment by ro0NL** [comment]
I also aimed for not involving external steps, nor additional commands.

**Comment by veewee** [comment]
If the service changes - it might as well break something. That's another reason why the cached version is most likely better than the upstream one. But that is indeed another discussion.

I wouldn't call PHPs ext-soap default behaviour that super awesome ...

If you really need to invalidate intermediately, you can indeed use your own provider or just ... `rm` in a cronjob ;p
For now I'dd say what we have is good enough.

**Comment by ro0NL** [comment]
@veewee fair enough. If i understand well, `CachedWsdlProvider` requires 2 steps?

It always writes to tempoary/ location, but the read checks the permanent location. To write into permanent/ i need to force downloads ... totally defeating the cached http call.

**Comment by veewee** [comment]
Not really, there are 2 different modes:

By default, it downloads the WSDL to a temporary location and uses that to configure the soap-client.
Meaning that it will always download a new version as long as there is no permanent cache.

If you don't want to spam the server (mostly on prod / acc environments - but can as well be used for you develop environment), you can build a permanent cache using the `forcePermanentDownloads`. From that point on it will always use that cache untill you remove or force an overwrite again.

**Comment by ro0NL** [comment]
My app has a single `CachedWsdlProvider` service (without calling `forcePermanentDownloads()`)

i never hit this line: https://github.com/phpro/soap-client/blob/df5d3af128e0758269cc773b11a5d5e1757016d1/src/Phpro/SoapClient/Wsdl/Provider/CachedWsdlProvider.php#L63 because it checks the permanent location, while it writes to temporary.

if if enable `forcePermanentDownloads` i never hit that line too, because now `forceDownload = true` :) so again it invokes the loader each time.

i ended up with a simple

```php
<?php

declare(strict_types=1);

namespace App\Soap;

use Phpro\SoapClient\Wsdl\Loader\WsdlLoaderInterface;
use Phpro\SoapClient\Wsdl\Provider\WsdlProviderInterface;
use Symfony\Component\Filesystem\Filesystem;

class CachedWsdlProvider implements WsdlProviderInterface
{
    protected WsdlLoaderInterface $loader;
    protected Filesystem $filesystem;
    protected string $wsdlCacheDir;

    public function __construct(
        WsdlLoaderInterface $loader,
        Filesystem $filesystem,
        string $wsdlCacheDir
    ) {
        $this->loader = $loader;
        $this->filesystem = $filesystem;
        $this->wsdlCacheDir = $wsdlCacheDir;
    }

    public function provide(string $source): string
    {
        $cacheFile = $this->wsdlCacheDir.'/'.md5($source).'.wsdl';

        if (!$this->filesystem->exists($cacheFile)) {
            $this->filesystem->dumpFile($cacheFile, $this->loader->load($source));
        }

        return $cacheFile;
    }
}
```

:sweat_smile:

**Comment by ro0NL** [comment]
At this point we can also just as well commit the permanent location, to be used in prod. I figured that's the approach implied here.

**Comment by veewee** [comment]
Hmm strange... It works on my project but I might have a slightly different version. Will have to take a second look to make sure it works as intended.

You could commit the cache, bit you'might use different services on different environments.

**Comment by ro0NL** [comment]
@veewee cool :) to summarize, we concluded the external URI is a cacheable (e.g. `$source`). We can argue about its TTL :)

We dont want to copy it in VCS, neither ensure availability via 2-step process, etc. Except maybe for regular cache warmup, which assumes we know all the URIs upfront, which i like to avoid for now.

So, the first proposal enables invalidating local file based on redis TTL (it's implemented as default lifetime of the given `CacheItemPoolInterface`).

The last proposal is straigtforward lazy loader.

Both potentially leverage warmed up cache files.

Both still seem more useful than the currently built-in provider :)

**Comment by veewee** [comment]
The current provider might be doing too much.
Maybe better to split it up in 2 different once:

- PermanentlyDownloadingWsdlProvider
- DownloadingWsdlProvider

(naming is a wip 😃  )

That way you can choose based on e.g. a debug flag or env var which one to use, making it very verbosy in what it does as well.
If you want a TTL (which doesn't make much sense to me personally), you could always create a provider that fits that specific need. All the tools are there to create it in an acceptable amount of time.

**Comment by ro0NL** [comment]
I think it's a doc issue mostly

https://github.com/phpro/soap-client/blob/master/docs/wsdl-providers.md#cachedwsdlprovider

here i would clarify by default a temporary wsdl is downloaded each time, **until** `$provider->forcePermanentDownloads()->provide('http://somehost/service.wsdl');` is invoked _somewhere_ (i.e. from a CLI command during a build step), which then triggers permanent loading.

i wouldnt call this a "cached" indeed, as i discovered, it doesnt recompute the cache at runtime in case of a miss. That was unexpected to me at least.
