### ISSUE TITLE
The classmap already exists and missing interfaces

### ISSUE THREAD

**Issue by zagrad** [phpro/soap-client#321]
|    Q        |   A
|------------ | -----
| Version     | 1.0.5
| PHP          | 7.1.3

### Support Question

Today I started using this project for the first time and all went well as for using the wizard. It nicely generated all classes, the client, clientfactory, and class-mapping.

Then I started implementing it in my code like so:
(Note that I renamed many parts of my code here to "example" in order to keep out my client's company name and such).

    ...
    $client = ExampleClientFactory::factory(__DIR__ . '/../../wsdl/example.wsdl');

    $example = (new Example())
      ->withSomeProperty(123);

    $saveExample = (new SaveExample())
      ->withExample($example);

    $response = $client->saveExample($saveExample);
    $result = $response->getSaveExampleResult();

    dump($result);

Now the problems occurred one after another.
Please note that I am on version `1.0.5`, because the project I am currently working on runs on PHP 7.1.
The conclusion of all my question may simply be that the version I am running is indeed very buggy, in which case I simply can't make use of this project.
However, ofcourse I hope I am simply making a big mistake somewhere and all my issues can be fixed easily.

The first problem occurs immediately when initializing the client on the first line.
The error that shows up:

    In ClassMapCollection.php line 39:
    The classmap already exists!

I really don't understand why this error would show up, since I'm not generating a classmap at this point.
Could anyone help?

Then as a quickfix I removed the line that adds the classmap:

    class ExampleClientFactory
    {

        public static function factory(string $wsdl) : \My\NameSpace\ExampleClient
        {
            $engine = ExtSoapEngineFactory::fromOptions(
                ExtSoapOptions::defaults($wsdl, [])
                // DISABLE THIS ->withClassMap(ExampleClassmap::getCollection())
            );
            $eventDispatcher = new EventDispatcher();
    
            return new ExampleClient($engine, $eventDispatcher);
        }
     }

Now the code continues, but immediately fails again with this error:

    Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 2 passed to Phpro\SoapClient\Client::call() must be an instance of Phpro\SoapClient\Type\RequestInterface, instance of My\NameSpace\Type\SaveExample given, called in .....My/NameSpace/ExampleClient.php

So the soap-client expects an object that implements the RequestInterface. However none of the generated classes extend either a RequestInterface nor a ResponseInterface. Should I do that by hand?

Thanks in advance for this nice project. Hope I can get it to work.

**Comment by veewee** [comment]
Hello @zagrad,

Can you please update to the latest soap-client version? This issue has been resolved in 1.3.0.
https://github.com/phpro/soap-client/releases/tag/v1.3.0
