### ISSUE TITLE
"No class is set" when generating types or client (laminas-code 3.5.0 BC break)

### ISSUE THREAD

**Issue by edudobay** [phpro/soap-client#323]
Hello! When generating the types and the client class for a SOAP service (with the command `soap-client generate:types` or `soap-client generate:client`), I got error messages and the code generation didn't go through.

When generating types, I would get repeated instances of the error message `No class is set` and no type file was generated. The client generation failed in the same way with the same message, additionally referencing the line where the error was thrown (`FileGenerator.php:350`). With the help of a debugger I traced the problem to these lines up the call stack:

https://github.com/phpro/soap-client/blob/df5d3af128e0758269cc773b11a5d5e1757016d1/src/Phpro/SoapClient/CodeGenerator/TypeGenerator.php#L42

https://github.com/phpro/soap-client/blob/df5d3af128e0758269cc773b11a5d5e1757016d1/src/Phpro/SoapClient/CodeGenerator/ClientGenerator.php#L44

I came up with a dirty workaround and managed to get my types and client generated:

```diff
+        try {
            $class = $file->getClass() ?: new ClassGenerator();
+        } catch (ClassNotFoundException $exception) {
+            $class = new ClassGenerator();
+        }
```

Here are the [WSDL](https://github.com/phpro/soap-client/files/5534067/wsdl.txt) and [soap-client.php](https://github.com/phpro/soap-client/files/5534068/soap-client.php.txt) that I used for reproducing this issue. Note: this is a random WSDL I found on the internet (https://tomd.xyz/wsdl/). Originally I had this issue with another WSDL (that I'm not sure would be ok for publicly sharing).

Also, this is the output for `composer show`: [composer_show.txt](https://github.com/phpro/soap-client/files/5534084/composer_show.txt) (should be mostly latest stable releases, as this was a fresh project).

**Comment by edudobay** [comment]
Update: this change in laminas-code changes the behavior for `FileGenerator::getClass()`, introducing that exception: https://github.com/laminas/laminas-code/commit/cc2adf24d3dac4bca644c5f872c40c01840929e9. This is the corresponding PR: https://github.com/laminas/laminas-code/pull/43

Downgrading to laminas-code 3.4.1 fixes the issue. So this seems to be a BC break introduced by laminas-code 3.5.0.

**Comment by veewee** [comment]
@janvernieuwe : doh! :)


The fix you provided looks like the right way to go. Would you care to create a PR @edudobay?

**Comment by janvernieuwe** [comment]
Lol yeah, this was an expected break (I didn't choose myself to do it so, but yeah).
This is indeed the right way to go.

**Comment by edudobay** [comment]
@veewee Sure! I'll be shortly opening a PR.

**Comment by veewee** [comment]
Continuing the discussion in the PR.
