### ISSUE TITLE
Error during generation

### ISSUE THREAD

**Issue by etcware** [phpro/soap-client#326]
### Bug Report

```
# vendor/bin/soap-client -vvv generate config/config.yml src/Service/Container --dest-class=Service/Container/SoapContainer


PHP Fatal error:  Uncaught TypeError: Argument 1 passed to GoetasWebservices\Xsd\XsdToPhp\Php\PhpConverter::visitElementDef() must be an instance of GoetasWebservices\XML\XSDReader\Schema\Element\ElementDef, null given, called in .../my-soap-client-2/vendor/goetas-webservices/soap-client/src/StubGeneration/ClientStubGenerator.php on line 184 and defined in .../my-soap-client-2/vendor/goetas-webservices/xsd2php/src/Php/PhpConverter.php:148
...
```
I receive this error, probably due to wrong data, but it is a robustness problem because the server is not under my control. 

#### How to reproduce

I don't know how to reproduce because it happen during generation and I don't know all data coming from server.

#### Patch
I tried to patch code, but I don't know if it is correct. After this generation seems to go ok.

ClientStubGenerator.php line 172

```
if ($class != null) {
  if ($t = $class->isSimpleType()) {
      return [$t->getType()->getPhpType()];
  }
  return [$class->getPhpType()];
}
```
ClientStubGenerator.php line 180

```
private function getClassFromPart(Part $part)
{
    if ($part->getType()) {
        return $this->phpConverter->visitType($part->getType());
    } else if ($part->getElement()!=null){
        return $this->phpConverter->visitElementDef($part->getElement());
    }
    return null;
}
```

**Comment by veewee** [comment]
Hello, 

Thanks for your question.
However, you should be reporting this issue in the  soap-client you are using:
https://github.com/goetas-webservices/soap-client


Feel free to reach out for questions on this package.
