### ISSUE TITLE
Support strict types declare in generate:types

### ISSUE THREAD

**Issue by GaryJones** [phpro/soap-client#33]
Like the `Config::create()` can fluently `setNamespace(...)`, it would be nice to be able to optionally state that each of the generated classes also had `declare(strict_types=1);` at the top of the files too.

**Comment by veewee** [comment]
I would prefer to create a generator for that purpose. That way, there is one clear way of configuring the generated code.

**Comment by GaryJones** [comment]
I couldn't see anything suitable in the underlying zend-code, so I created an [issue](https://github.com/zendframework/zend-code/issues/102).

**Comment by nikola-stojiljkovic-constup** [comment]
Just a workaround if anyone needs it. You can iterate over generated files and add strict type declaration with bash:
`for f in $(find . -name "*.php" -type f); do sed -i '/<?php/a \\ndeclare(strict_types = 1);' "$f"; done`

**Comment by veewee** [comment]
You could also run php-cs-fixer over the generated code with the `declare_strict_types` option enabled. This way you can configure additional code style rules as well.

**Comment by janvernieuwe** [comment]
Using php-cs-fixer is a good enough option, the generated code will never be 100% clean anyways.
Closing this issue for cleanup, feel free to create a new one if you still have an issue.
