### ISSUE TITLE
How to send an xml to server soap?

### ISSUE THREAD

**Issue by Maxcrazy1** [phpro/soap-client#330]
Hello I am using the latest version of the library, in addition to that I followed the installation steps recommended in the documentation, however I cannot find the way to after the library is installed to make a simple query to the soap server by sending an xml to get a response. 

I need help..

**Comment by veewee** [comment]
Sorry, but this is not a support forum. All the information is available in the documentation.
Feel free to log another issue if you have a more concrete question.
