### ISSUE TITLE
Soap method error when queried

### ISSUE THREAD

**Issue by Maxcrazy1** [phpro/soap-client#332]
|    Q        |   A
|------------ | -----
| Version     | 1.4.0

### Support Question

I made a query for the wdsl server methods that I am sending requests, to validate that I am calling the appropriate methods, some of the available methods are: 

- **EFACRECEPCIONSOBRE($parameters)**
- **EFACRECEPCIONREPORTE(parameters)**

However when I make the call from my client it returns that 

**No SOAP method found with name EFACRECEPCIONSOBRE** 

When I look the map that same method is there, but can't send requests to it.. 

`new ClassMap('WS_eFactura.EFACRECEPCIONSOBRE', Type\WSEFacturaEFACRECEPCIONSOBRE::class),`

I've tried diferents ways of write method name as WS_eFactura.EFACRECEPCIONSOBRE or WSEFacturaEFACRECEPCIONSOBRE but nothing works.

**Comment by veewee** [comment]
Hello @Maxcrazy1 

You can list all methods by looking at the metadata that is available inside the `DriverInterface::getMetadata()`.
However, you shouldn't really have to care about that if you are using this package the way it should be used.
Methods don't have to do anything with the classmap. The classmap is used to map php types to soap types.

I consider this question answered. If you do have additional questions, please provide some more usefull details like how you've set up your project, what specific parts you are using, some code samples, ... The question above is quite confusing and missing a lot of helpfull details.
