### ISSUE TITLE
Undefined type 'Laminas\Code\Generator\Exception\ClassNotFoundException'.intelephense (1009)

### ISSUE THREAD

**Issue by gurevich-agency** [phpro/soap-client#334]
Hi.
I have problems in time of wizard work.
I tried to install and generate classes, like here https://github.com/phpro/soap-client.

My composer.json:
```
{
    "name": "evgeny/public_html",
    "require": {
        "phpro/soap-client": "^1.3"
    },
    "require-dev": {
        "laminas/laminas-code": "^3.1.0"
    },
    "autoload": {
        "psr-4": {
            "App\\" : "."
        }
    }
}
```
What I did http://i.imgur.com/5nU3Ogs.png
WSDL, that I used http://webservices.gama-system.com/exchangerates.asmx?WSDL 
What I found in code http://i.imgur.com/4Vmds8J.png

What do I do wrong?
Thx.

**Comment by veewee** [comment]
Thanks for reporting, looks like latest release introduced this bug.

https://github.com/phpro/soap-client/pull/324/files#diff-522d2004fba798397424d69a90007c3c0929d2cd90bced3688e24e456285f1ae

If possible, you can upgrade laminas-code or downgrade this package to previous version.
