### ISSUE TITLE
Client wizard error couldn't load

### ISSUE THREAD

**Issue by viduc** [phpro/soap-client#336]
|    Q        |   A
|------------ | -----
| Version     | 1.4.1

### Support Question

Hi,
I try to use your librairy, i use soap-client wizard with this url: http://www.zimbra.com/wsdl/ZimbraService.wsdl and with our url wsdl too, but i have this message:

SOAP-ERROR: Parsing WSDL: Couldn't load from 'http://www.zimbra.com/wsdl/ZimbraService.wsdl' : failed to load external entity "http://www.zimbra.com/wsdl/ZimbraService.wsdl" 

I dont know what i can do ... ?

**Comment by veewee** [comment]
The URL results in a 404 HTTP Not found error. Might this be the reason why you get this error?

**Comment by viduc** [comment]
i use this url :https://zm-logger.u-ga.fr:7071/service/wsdl/ZimbraAdminService.wsdl, its our url with vpn acces. I have access when i try in browser, but same error with wizard. So i try with other url but yes this one dont work...

**Comment by veewee** [comment]
As the error states : it cannot download the external file. So it's up to you to get the connection going.
You might want to use httplug for downloading WSDLs as well to overcome some known http issues with ext-soap.

More info: https://github.com/phpro/soap-client/blob/master/docs/wsdl-providers.md#cachedwsdlprovider

**Comment by viduc** [comment]
Thanks,
i found what is the problem... our serveur has a certica ssl auto signed, and we must send option ssl' => array(
                                                                  'verify_peer' => false,
                                                                  'verify_peer_name' => false,
                                                                  'allow_self_signed' => true
                                                              ) to access it...
thanks for your help.

**Comment by Vallevard** [comment]
@viduc Hello, Where did you put the code? I'm having the same issue. Thanks

**Comment by viduc** [comment]
Hi, this my method to create client:
```
    /**
     * Créer le client soap
     * @throws ZimbraException
     * @test testCreerLeCLient()
     */
    final public function creerLeClient() : void
    {
        try {
            $soapOptionsSSL = array(
                'trace'=>0,
                'keep_alive' => 0,
                'stream_context' => stream_context_create(
                    array(
                        'ssl' => array(
                            'verify_peer' => false,
                            'verify_peer_name' => false,
                            'allow_self_signed' => true
                        )
                    )
                )
            );
            $options = $soapOptionsSSL;
            if ($this->config !== null) {
                $options = array_merge($soapOptionsSSL, $this->config);
            }
            $this->client = new SoapClient($this->wsdl, $options);
        } catch (SoapFault $ex) {
            throw new ZimbraException('Impossible de charger le client');
        }
    }
```
array config contains all parameters for connexion and i merge with soapOptionsSSL array. I hope that help you
