### ISSUE TITLE
Question: should the passing of data declared as attributes in XSD work?

### ISSUE THREAD

**Issue by ducdebreme** [phpro/soap-client#337]
If I have a XSD type definition like this ...

        <xsd:complexType name="myElement">
            <xsd:attribute name="myValue" type="Text_an56" use="required" form="unqualified">
            </xsd:attribute>
            ...
        </xsd:complexType>

I would expect that the declared attribute is sent with the SOAP request, so if I I pass `myValue` in a request, I would expect to see this:

      <myElement myValue="any cool value"/>

but in my failing request I see 

      <myElement />

Question: should the passing of data declared as attributes via XSD work?

**Comment by veewee** [comment]
Yes it should work.
Can you elaborate on your setup?

**Comment by ducdebreme** [comment]
In the end I spotted what the issue was: my WSDL had many nested includes of XSD files. As a result some schemas were not correctly included and as a result disregarded.
To fix it I used the schema lightener (https://github.com/pkielgithub/SchemaLightener), which allows as well to combine all files into a single WSDL file.

**Comment by veewee** [comment]
Thanks for mentioning! We are planning to include a flattener at some point as well, making is easier for everybody.
