### ISSUE TITLE
Ignoring null values when XML is created?

### ISSUE THREAD

**Issue by HKandulla** [phpro/soap-client#34]
Hi,

is it possible to make the generated xml not include any properties that are null?
Can I create a TypeConverter to accomplish this?

Thanks, Hannes

**Comment by veewee** [comment]
Can you provide some additional information about what you are trying to do?
Maybe a code sample would be handy :)

**Comment by HKandulla** [comment]
Sure. The Service I send my requests to allows me to send:
1. <ns1:DoNotCall>true</ns1:DoNotCall>
2. leave it out completely. 
But I am not allowed to send a null value in the form:
3. <ns1:DoNotCall xsi:nil="true“/>

**Comment by veewee** [comment]
This can be done with a type converter, but then you'll have to add a converter for every type you want to convert this way. In this case: ns1:DoNotCall.

**Comment by HKandulla** [comment]
first of all, tahnks for your quick response!
I created the type converter and used and defined:

`

    public function convertPhpToXml($php)
    {
        return !is_null($php)
            ?
            sprintf('<%1$s>%2$s</%1$s>', $this->getTypeName(), $php)
            :
            ''
            ;
    }
`

But the generated XML still contains `<ns1:CustomerID/>`

Any idea how I can eliminate the creation of the tag completely?

Thanks, Hannes

**Comment by faibl** [comment]
Hi @veewee,

I figured that the type converter only allows to alter the content and not the tag itself. But I solved it by creating a middleware that removes all empty tags:

`

    public function beforeRequest(callable $handler, RequestInterface $request, array $options)
    {
        $xml = SoapXml::fromStream($request->getBody());

        // remove all empty nodes
        while (($notNodes = $xml->xpath('//*[not(node())]')) && ($notNodes->length)) {
            foreach($notNodes as $node) {
                $node->parentNode->removeChild($node);
            }
        }

        return $handler(new Request(
            $request->getMethod(),
            $request->getUri(),
            $request->getHeaders(),
            $xml->toStream()
        ), $options);
    }
`

Thanks for your help and a great library.

Best, Hannes

**Comment by veewee** [comment]
No problem! Do you mind adding the Middleware to the package? I am pretty sure it will come in handy for other people as well. Since you already have the code, you'll only have to add some tests and some documentation.

Also, this might be a bit shorter then creating a new request manually:

```php
$request = $request->withBody($xml->toStream());
```

Thanks!

**Comment by faibl** [comment]
sure, I am happy to contribute!
I prepare a PR later tonight.
And thanks for the improvement.

Best, Hannes

**Comment by HKandulla** [comment]
Hi @veewee, just to let you know, I havn't forgotten about this. As soon as I have a little time to write the tests, I create a PR. Best, Hannes

**Comment by veewee** [comment]
Super, take all the time you need :)

**Comment by HKandulla** [comment]
yes, the iterator is good for parsing the result. But what about creating an object that has an array. In my case I generated the model manually and added a add* method:

    /**
     * @var AdDisplayBookRecord
     */
    protected $AdDisplayBookRecord = [];

    /**
     * @param AdDisplayBookRecord $AdDisplayBookRecord
     * @return $this
     */
    public function addAdDisplayBookRecord($AdDisplayBookRecord)
    {
        $this->AdDisplayBookRecord[] = $AdDisplayBookRecord;
        return $this;
    }

**Comment by veewee** [comment]
Are you talking about a request or response object?
For requests: How does this affect nullable tags? You define what is in the XML yourself.
For responses: The add* method is never called by ext-soap.

I currently do not understand how this is related to the nullable tags. Can you maybe try to tell me what it is you are trying to achieve?

**Comment by HKandulla** [comment]
This is not related to the nullable tags at all, I just followed your "Let's continue the discussion in #34".. Shall we open a ticket for this and discuss it there? Or discuss it here #28?

I am talking about a request object.

**Comment by veewee** [comment]
Feedback @HKandulla 
> I am still busy with the tests on #34. I want to add proper tests that make sure that even nodes with empty child nodes are removed by my middleware. But I definetely do this this week..

**Comment by HKandulla** [comment]
Hi @veewee, finally the PR https://github.com/phpro/soap-client/pull/39
Best, Hannes

**Comment by veewee** [comment]
Fixed in #39.

**Comment by Pton** [comment]
@HKandulla I just wanted to let you know that I am having the exact same use case as you had. PR #39 saved me from having to build it myself, great work 👍

**Comment by HKandulla** [comment]
@Pton Thanks:-)

**Comment by ro0NL** [comment]
@HKandulla :100: soap is great now :D

**Comment by HKandulla** [comment]
@ro0NL Thanks, glad I could contribute a little.
