### ISSUE TITLE
Another array question

### ISSUE THREAD

**Issue by amazium** [phpro/soap-client#344]
In a wsdl (out of my control, so cannot be changed) I have following complex type:

```
<complexType name="contract">
   <sequence>
      <!-- ... -->
      <element maxOccurs="1" minOccurs="0" name="start_date" type="date"/>
      <element maxOccurs="1" minOccurs="0" name="end_date" type="date"/>
      <element maxOccurs="999" minOccurs="0" name="card" type="tns:card"/>
      <element maxOccurs="999" minOccurs="0" name="service" type="tns:service"/>
      <element maxOccurs="999" minOccurs="0" name="account" type="tns:account"/>
      <element maxOccurs="999" minOccurs="0" name="document" type="tns:document"/>
      <element maxOccurs="unbounded" minOccurs="0" name="error" type="tns:error"/>
      <!-- ... -->
   </sequence>
</complexType>
```

So the way this is used is you get a structure like:

```
<contract>
    <!-- ... -->
    <card />
    <card />
    <service />
    <service />
    <service />
    <!-- ... -->
</contract>
```

So there is no `<ArrayOfServices>` wrapped around `<service>` on which I can place an `IteratorAssembler` as a rule as suggested.

As far as I can see in related issues, there is no solution for such a case yet. Is that correct?

**Comment by veewee** [comment]
The iterator assembler can be used to iterate over 1 single repeated item.
In this case, you generate a class that looks like:

```php
class Contract
{
// ...
    private $card;
    private $service;
// ...
}
```

Currently, code generation will think that the property is a tns:card or tns:service type, even though it's an array of that type.
So in this case, you won't be able to use strict types for the generated code and the typehint will fail.
That's indeed a big limitation which we won't be able to really overcome as long as we don't parse the WSDL files manually.

More info:
https://github.com/phpro/soap-client/blob/master/docs/known-issues/ext-soap.md#occurs

Linked issues: #282, #231

You might be able to do something smart with [Type manipulators](https://github.com/phpro/soap-client/blob/master/src/Phpro/SoapClient/Soap/Engine/Metadata/Manipulators/TypesManipulatorInterface.php).
See https://github.com/phpro/soap-client/blob/master/docs/drivers/metadata.md#manipulatedmetadata

**Comment by veewee** [comment]
Hello,

We noticed this issue got reported many times and want to tackle it at its core!
Therefore, we've planned a [project that will work on better types support](https://github.com/php-soap/.github/blob/main/PROJECTS.md#better-types).
It’s going to be a huge project, so we are looking for ways to make development possible during our business hours instead of in our developers precious spare time.

In case you want this feature as badly as us: **[find out how you can support this project here 💚](https://github.com/php-soap/.github/blob/main/HELPING_OUT.md)**!
