### ISSUE TITLE
Invalid return value MixedResult

### ISSUE THREAD

**Issue by pimreijersen** [phpro/soap-client#345]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | unknown
| Version     | 1.3.1

#### Summary

Incidental failure calling SubscriptionCreate.
https://api.perfectview.nl/perfectview.asmx?op=SubscriptionCreate

#### Current behavior

`Return value of PerfectView\Gen\PVClient::subscriptionCreate() must be an instance of PerfectView\Gen\Type\SubscriptionCreateResponse, instance of Phpro\SoapClient\Type\MixedResult returned`

#### How to reproduce

```php
$this->client = PVClientFactory::factory(
    'https://api.perfectview.nl/PerfectView.asmx?WSDL'
);

$response = $this->client->subscriptionCreate(
    new SubscriptionCreate(
        $this->credentials,
        $settings,
        $followUp,
        [
            (new PvFieldValueData())
                ->withId('ec7276ce-36b7-46b7-b97c-a486b462b3f6')
                ->withValue($typeValue)
        ],
        null,
        $productID,
        1,
        null,
        null,
        null,
        null,
        null
    )
);
```

#### Expected behavior

Instance of PerfectView\Gen\Type\SubscriptionCreateResponse.

**Comment by veewee** [comment]
Hello @pimreijersen ,

Did you make sure that you've added the classmap to de client?
This is the part that links the response to a PHP object.
If you did so, what is inside the mixedresult?

**Comment by pimreijersen** [comment]
**MixedResult**
```
object(Phpro\SoapClient\Type\MixedResult)#16430 (1) {
  ["result":"Phpro\SoapClient\Type\MixedResult":private]=
  NULL
}
```

**Classmap**
The PVClassmap.php is huge, I think these are the most important lines for this use case:
```php 
new ClassMap('SubscriptionCreate', Type\SubscriptionCreate::class),
new ClassMap('SubscriptionCreateResponse', Type\SubscriptionCreateResponse::class),
new ClassMap('SubscriptionCreateResult', Type\SubscriptionCreateResult::class),
```

**Client configuration**
```php
return Config::create()
    ->setEngine($engine = ExtSoapEngineFactory::fromOptions(
        ExtSoapOptions::defaults('https://api.perfectview.nl/PerfectView.asmx?WSDL', [])
            ->disableWsdlCache()
    ))
    ->setTypeDestination('gen/Type')
    ->setTypeNamespace('PerfectView/Gen\Type')
    ->setClientDestination('gen')
    ->setClientName('PVClient')
    ->setClientNamespace('PerfectView\\Gen')
    ->setClassMapDestination('gen')
    ->setClassMapName('PVClassmap')
    ->setClassMapNamespace('PerfectView\\Gen')
    ->addRule(new Rules\AssembleRule(new Assembler\GetterAssembler(new Assembler\GetterAssemblerOptions())))
    ->addRule(new Rules\AssembleRule(new Assembler\ImmutableSetterAssembler()))
    ->addRule(
        new Rules\IsRequestRule(
            $engine->getMetadata(),
            new Rules\MultiRule([
                new Rules\AssembleRule(new Assembler\RequestAssembler()),
                new Rules\AssembleRule(new Assembler\ConstructorAssembler(new Assembler\ConstructorAssemblerOptions())),
            ])
        )
    )
    ->addRule(
        new Rules\IsResultRule(
            $engine->getMetadata(),
            new Rules\MultiRule([
                new Rules\AssembleRule(new Assembler\ResultAssembler()),
            ])
        )
    )
;
```

**Comment by veewee** [comment]
Hello @pimreijersen 

The important part is in the client factory here; Can you paste that one?
Since you are receiving null, I am assuming that there is an HTTP related issues.
Are you using the [HTTPlug](https://github.com/phpro/soap-client/blob/master/docs/handlers/httplug.md) handle already? It solves some common known issues in ext-soap.

**Comment by pimreijersen** [comment]
Hello @veewee,

We do not use HTTPlug yet.

**PVClientFactory**
```php
class PVClientFactory
{

    public static function factory(string $wsdl) : \PerfectView\Gen\PVClient
    {
        $engine = ExtSoapEngineFactory::fromOptions(
            ExtSoapOptions::defaults($wsdl, [])
                ->withClassMap(PVClassmap::getCollection())
        );
        $eventDispatcher = new EventDispatcher();

        return new PVClient($engine, $eventDispatcher);
    }


}
```

**Comment by veewee** [comment]
You can inspect the request / response, but I am pretty sure the response is NULL instead of a soap envelope.
Can you try using the HTTPlug handle instead?

**Comment by pimreijersen** [comment]
Hello @veewee,

2 weeks ago we setup HTTPlug with Guzzle6 and added a logger. Using HTTPlug seems to have resolved the issue. Thank you for the support.

**Comment by veewee** [comment]
Good to hear!

**Comment by rauanmayemir** [comment]
Is there a way to debug this?
I've started having this issue _all of a sudden_. I can see correct responses in my VCR records, but it's doesn't look like SOAP's picking up the classmap.

**Comment by rauanmayemir** [comment]
There was an odd issue where my composer vendor cache or autoload classmap was borked, so everything related to soap was failing. Installing from scratch helped it.
