### ISSUE TITLE
Log/Output of request and response XMLs

### ISSUE THREAD

**Issue by barreirinha** [phpro/soap-client#348]
|    Q        |   A
|------------ | -----
| Version     | 1.4

### Support Question

My App works fine, but to homologate access on the SOAP service I need to send them a copy of Request and Response XLMs.

I read the **soap-client/docs/event-subscribers/logger.md** instructions, but I go no success yet:

```php
use Phpro\SoapClient\Event\Subscriber\LogSubscriber;

$eventDispatcher->addSubscriber(new LogSubscriber($logger));
```
My questions are:

1. Where should the above code be placed? In what file? Where this **$logger** variable is declared?
2. Is there any other easy way to record the XMLs (request and response) in a .txt file?

**Comment by barreirinha** [comment]
I got it by MySelf, and is easy. 

```php
$result = $client->debugLastSoapRequest();
```
The above code returns an array with request and response datais, including the XMLs.

**Comment by xcy7e** [comment]
This is not possible anymore. For anyone who stumbles upon this, `UPGRADING.md` says:

> We removed the debugging method from the soap-client.
Instead, you can either debug the request or result directly.
If you want to have access to the HTTP SOAP payload, we suggest adding a logger plugin to the HTTP client.
There is also a `TraceableTransport` available that can be used to detect the last SOAP request and response like you would in the old client.
