### ISSUE TITLE
CachedWsdlProvider with http-basic auth protected wsdl

### ISSUE THREAD

**Issue by staabm** [phpro/soap-client#349]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes/no
| Version     | 1.4.1

#### Summary

when requesting a wsdl via http url behind a auth using wrong credentials, the CachedWsdlProvider  stores the http response of the backend (which is not a wsdl) and errors on each request afterwards with `SOAP-ERROR: Parsing WSDL: Couldn't load from '/tmp/soap-test-/temporary/b1a0fc4d434c24991071837386a4058f.wsdl' : Input is not proper UTF-8, indicate encoding ! Bytes: 0xFC 0x6C 0x74 0x69 ` because it is trying to interpret the saved http-response as a wsdl

#### How to reproduce

use a config like

```
        $engine = ExtSoapEngineFactory::fromOptions(
            ExtSoapOptions::defaults($wsdl, [])
                ->withClassMap(CustomerClassmap::getCollection())
                ->withWsdlProvider(new CachedWsdlProvider(new HttpWsdlLoader(
                    new Client([
                        'verify' => false /*disable ssl cert validation*/,
                        'auth' => ['myauth', 'awrongpassword'],
                    ]),
                    Psr17FactoryDiscovery::findRequestFactory()
                ), new Filesystem(),
                    sys_get_temp_dir().DIRECTORY_SEPARATOR.'soap-test-'))
```

#### Expected behavior

a non-xml non-http-200 request should not be persisted by the CachedWsdlProvider

**Comment by veewee** [comment]
Based on the client configuration I assume you use guzzle as HTTP client?
Normally it should throw an exception by default when the error is in the 4XX or 5XX range.
(See https://docs.guzzlephp.org/en/stable/request-options.html#http-errors)

What HTTP status code do you receive with that html response?

**Comment by staabm** [comment]
thx for your reply.

> Based on the client configuration I assume you use guzzle as HTTP client?

correct - sorry for the missing information.

> Normally it should throw an exception by default when the error is in the 4XX or 5XX range.

I feel like the webservice backend I am connecting with just returns a "html-error page" with a http 200 instead of a proper http-status code

**Comment by veewee** [comment]
In that case, it feels like a server issue.
You can fix this by detecting HTML yourself in a custom HTTP client plugin.
