### ISSUE TITLE
Drop property default value if it is null

### ISSUE THREAD

**Issue by GaryJones** [phpro/soap-client#35]
A property created with `generate:types` can be like:

```
    /**
     * @var string
     */
    protected $NewUsername = null;
```

The `= null` bit is completely redundant and could be removed if the default value is === `null`.

**Comment by janvernieuwe** [comment]
Seems like this is not possible yet with zend code, see https://github.com/zendframework/zend-code/issues/28
If that is implemented, we can fix this.

**Comment by makoru-hikage** [comment]
It's already implemented: https://github.com/zendframework/zend-code/pull/131

**Comment by janvernieuwe** [comment]
Ah, the guy who did that the best! 
*Cough*

I'm waiting on the next release to pick this issue up.
