### ISSUE TITLE
IteratorAssembler rule is not applied on generation

### ISSUE THREAD

**Issue by fbecker-complex** [phpro/soap-client#366]
|    Q        |   A
|------------ | -----
| Version     | 1.6.0

### Support Question
I'm having trouble to add the `IteratorAssembler` to files on generation.
I added the rule in my soap client and regenerated my files, but the assembler is not added to any of them.

Code for my rule:
`->addRule(new Rules\TypenameMatchesRule(
        new Rules\AssembleRule(new Assembler\IteratorAssembler()),
        '/^(?!(PaymentTerms\.php))(.*)s\.php$/'
    ))`

The corresponding wsdl: http://webconnector.tso.de/api/wsdl/OutboundMasterDataIISWebService.wsdl

## Expectation:
The assembler should be added to all plural classes except `PaymentTerms.php`.

**Comment by veewee** [comment]
The regex is wrong. You need to provide a regex that matches on the type name instead of the file name.

**Comment by fbecker-complex** [comment]
Thanks for the quick reply :)

> The regex is wrong. You need to provide a regex that matches on the type name instead of the file name.
Those should be identical in my case.

Let me show you what I need in an example:

Another soap-client of mine applies this rule:
`->addRule(new Rules\TypenameMatchesRule(
        new Rules\AssembleRule(new Assembler\IteratorAssembler()),
        '/^ArrayOf(.*)$/'
    ))`

On this wsdl: http://webconnector.tso.de/api/wsdl/ContactIISWebService.wsdl
which leads to this generated class:

`class ArrayOfContact implements IteratorAggregate
{

    /**
     * @var \WebConnector\Contact\Type\Contact
     */
    private $Contact;

    /**
     * @return \ArrayIterator
     */
    public function getIterator()
    {
        return new \ArrayIterator(is_array($this->Contact) ? $this->Contact : []);
    }

    /**
     * @return \WebConnector\Contact\Type\Contact
     */
    public function getContact()
    {
        return $this->Contact;
    }

    /**
     * @param \WebConnector\Contact\Type\Contact $Contact
     * @return ArrayOfContact
     */
    public function withContact($Contact)
    {
        $new = clone $this;
        $new->Contact = $Contact;

        return $new;
    }`

Is there a way to do this in the same way for my new wsdl?
For example on the class below: 

`class Countries
{

    /**
     * @var \WebConnector\MasterData\Type\Country
     */
    private $Country;

    /**
     * @return \WebConnector\MasterData\Type\Country
     */
    public function getCountry()
    {
        return $this->Country;
    }

    /**
     * @param \WebConnector\MasterData\Type\Country $Country
     * @return Countries
     */
    public function withCountry($Country)
    {
        $new = clone $this;
        $new->Country = $Country;

        return $new;
    }


}`

This is the list of all generated types:
![image](https://user-images.githubusercontent.com/71324952/118778408-5a9a6e80-b88a-11eb-8ff7-dad05c5b325f.png)

**Comment by veewee** [comment]
Yes, it Is possible.
You can either use the TypenameMatchesRule with a valid tegen or you can use a TypeMapRule and provide it with a list of types you want to apply the assembler on.

Alternatively, you can create your own rule to check for very specific things on your types and/or properties.

**Comment by fbecker-complex** [comment]
> Yes, it Is possible.
> You can either use the TypenameMatchesRule with a valid tegen or you can use a TypeMapRule and provide it with a list of types you want to apply the assembler on.
> 
> Alternatively, you can create your own rule to check for very specific things on your types and/or properties.

Thanks, I'm going to look into this 👍🏼

**Comment by fbecker-complex** [comment]
Work's like a charm after I removed the `.php`-ending in the regex.
