### ISSUE TITLE
need help with type

### ISSUE THREAD

**Issue by xloroff** [phpro/soap-client#369]
|    Q        |   A
|------------ | -----
| Version     | x.y.z

### Support Question

Hello.
I need to set the type of the parameter - "mixed".
  /**
     * @var mixed
     */
    private $filterValue;

in standart soap i use
$wrapper->filterValue = new SoapVar($filterValue, XSD_STRING, "string", "http://www.w3.org/2001/XMLSchema", "filterValue", "ns1");

how to call type paremeter in autogenereted lib?

**Comment by veewee** [comment]
The mixed is there because the type cannot be determined from the wsdl.
Since it is a regular xs:string, you can fill it with any string value.
Optionally, you can also bind the SoapVar to the value since you are not using strict types.

**Comment by veewee** [comment]
The question has been answered. Closing this issue.
Feel free to reopen or create a new one if your issue is not solved.
