### ISSUE TITLE
set Timeout for the http client

### ISSUE THREAD

**Issue by staabm** [phpro/soap-client#370]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | no
| RFC         | yes
| BC Break    | no

using 1.6.0

#### Summary

we are running into timeout exceptions for some slow operations.

```
Uncaught exception: 'Phpro\SoapClient\Exception\SoapException' with message 'Maximum execution time of 10 seconds exceeded' (0)
> in /cluster/www/www/www/philipp/vendor/phpro/soap-client/src/Phpro/SoapClient/Exception/SoapException.php:19
Caused by 'SoapFault' with message 'Maximum execution time of 10 seconds exceeded' (0)
> in /cluster/www/www/www/philipp/vendor/phpro/soap-client/src/Phpro/SoapClient/Soap/Driver/ExtSoap/ExtSoapOptionsResolverFactory.php:131
Stack trace:
#0 /cluster/www/www/www/philipp/vendor/phpro/soap-client/src/Phpro/SoapClient/Client.php(117): Phpro\SoapClient\Exception\SoapException::fromThrowable()
#1 /cluster/www/www/www/philipp/soap/item/generated/ItemClient.php(40): Phpro\SoapClient\Client->call()
...
```

I did not found a way on how to increase the timeout for certain calls. is there an api for that, which I wasn't able to find?

**Comment by veewee** [comment]
Hello @staabm 

It depends on your configuration. If you are using the ext-soap handler, you'll neet to define the [default_socket_timeout](https://www.php.net/manual/en/filesystem.configuration.php#ini.default-socket-timeout) ini setting.

If you are using httplug, you'll need to define the timeout in the API provided by the HTTP client.

If the connection timeout is set on the server, you'll have to ask the system admin.

**Comment by veewee** [comment]
The question has been answered. Closing this issue.
Feel free to reopen or create a new one if your issue is not solved.
