### ISSUE TITLE
Docblock return and param types of arrays are incorrect

### ISSUE THREAD

**Issue by menno-ll** [phpro/soap-client#371]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 1.6.0

#### Summary

Getter (getXxx) functions that should return Array's of a named-objects are generated with a docblock returning that named-object, but not as an array.
The same happens for setter (withXxxx) functions docblocks with the function parameter.

#### Current behavior

When you have the WSDL as below, 

```xml
<s:complexType name="ArrayOfPvRelationData">
    <s:sequence>
        <s:element minOccurs="0" maxOccurs="unbounded" name="PvRelationData" nillable="true" type="tns:PvRelationData"/>
    </s:sequence>
</s:complexType>
```

This generates an `ArrayOfPvRelationData` class.
The `getPvRelationData` function inside that class, has a return type declared in the docblock of `\ThemeName\Connectors\PerfectView\Client\Type\PvRelationData`, instead of `\ThemeName\Connectors\PerfectView\Client\Type\PvRelationData[]`

The `withPvRelationData` function inside that class, has a parameter type declared in the docblock of `\ThemeName\Connectors\PerfectView\Client\Type\PvRelationData`, instead of `\ThemeName\Connectors\PerfectView\Client\Type\PvRelationData[]`

Currently generated code:
``` php
<?php

namespace ThemeName\Connectors\PerfectView\Client\Type;

class ArrayOfPvFieldValueData
{
    /**
     * @var \ThemeName\Connectors\PerfectView\Client\Type\PvFieldValueData
     */
    private $PvFieldValueData;

    /**
     * @return \ThemeName\Connectors\PerfectView\Client\Type\PvFieldValueData
     */
    public function getPvFieldValueData()
    {
        return $this->PvFieldValueData;
    }

    /**
     * @param \ThemeName\Connectors\PerfectView\Client\Type\PvFieldValueData $PvFieldValueData
     * @return ArrayOfPvFieldValueData
     */
    public function withPvFieldValueData($PvFieldValueData)
    {
        $new = clone $this;
        $new->PvFieldValueData = $PvFieldValueData;

        return $new;
    }
}


```

#### How to reproduce

Generate the types with `soap-client generate:types`.

WSDL: https://api.perfectview.nl/perfectview.asmx?WSDL

My configuration is just as it was simply generated with the wizard:

```php
use Phpro\SoapClient\CodeGenerator\Assembler;
use Phpro\SoapClient\CodeGenerator\Rules;
use Phpro\SoapClient\CodeGenerator\Config\Config;
use Phpro\SoapClient\Soap\Driver\ExtSoap\ExtSoapOptions;
use Phpro\SoapClient\Soap\Driver\ExtSoap\ExtSoapEngineFactory;

return Config::create()
    ->setEngine($engine = ExtSoapEngineFactory::fromOptions(
        ExtSoapOptions::defaults('https://api.perfectview.nl/perfectview.asmx?WSDL', [])
            ->disableWsdlCache()
    ))
    ->setTypeDestination('themes/theme-name/_generated/PerfectView/Type')
    ->setTypeNamespace('ThemeName\Connectors\PerfectView\Client\Type')
    ->setClientDestination('themes/theme-name/_generated/PerfectView')
    ->setClientName('PerfectViewClient')
    ->setClientNamespace('ThemeName\Connectors\PerfectView\Client')
    ->setClassMapDestination('themes/theme-name/_generated/PerfectView')
    ->setClassMapName('PerfectViewClassmap')
    ->setClassMapNamespace('ThemeName\Connectors\PerfectView\Client')
    ->addRule(new Rules\AssembleRule(new Assembler\GetterAssembler(new Assembler\GetterAssemblerOptions())))
    ->addRule(new Rules\AssembleRule(new Assembler\ImmutableSetterAssembler(
        new Assembler\ImmutableSetterAssemblerOptions()
    )))
    ->addRule(
        new Rules\IsRequestRule(
            $engine->getMetadata(),
            new Rules\MultiRule([
                new Rules\AssembleRule(new Assembler\RequestAssembler()),
                new Rules\AssembleRule(new Assembler\ConstructorAssembler(new Assembler\ConstructorAssemblerOptions())),
            ])
        )
    )
    ->addRule(
        new Rules\IsResultRule(
            $engine->getMetadata(),
            new Rules\MultiRule([
                new Rules\AssembleRule(new Assembler\ResultAssembler()),
            ])
        )
    )
;

```

#### Expected behavior

```xml
<s:complexType name="ArrayOfPvRelationData">
    <s:sequence>
        <s:element minOccurs="0" maxOccurs="unbounded" name="PvRelationData" nillable="true" type="tns:PvRelationData"/>
    </s:sequence>
</s:complexType>
```

This generates an `ArrayOfPvRelationData` class.
The `getPvRelationData` function inside that class, has a return type declared in the docblock of `\ThemeName\Connectors\PerfectView\Client\Type\PvRelationData[]`

The `withPvRelationData` function inside that class, has a parameter type declared in the docblock of `\ThemeName\Connectors\PerfectView\Client\Type\PvRelationData[]`

Code that should be generated:

```php
<?php

namespace ThemeName\Connectors\PerfectView\Client\Type;

class ArrayOfPvFieldValueData
{
    /**
     * @var \ThemeName\Connectors\PerfectView\Client\Type\PvFieldValueData[]
     */
    private $PvFieldValueData;

    /**
     * @return \ThemeName\Connectors\PerfectView\Client\Type\PvFieldValueData[]
     */
    public function getPvFieldValueData()
    {
        return $this->PvFieldValueData;
    }

    /**
     * @param \ThemeName\Connectors\PerfectView\Client\Type\PvFieldValueData $PvFieldValueData[]
     * @return ArrayOfPvFieldValueData
     */
    public function withPvFieldValueData($PvFieldValueData)
    {
        $new = clone $this;
        $new->PvFieldValueData = $PvFieldValueData;

        return $new;
    }
}


```

**Comment by veewee** [comment]
Ext-soap does not provide that information.
https://github.com/phpro/soap-client/blob/master/docs/known-issues/ext-soap.md#occurs

Currently, this issue can be avoided by not generating too strict types in the soap-client and optionally by using the [IteratorAssembler](https://github.com/phpro/soap-client/blob/master/docs/code-generation/assemblers.md#iteratorassembler).

This issue has been reported a few times: #346, #231, #282, #344,  ...

Until we have a better way of getting the data back from the WSDL, there is no simple solution for this.

**Comment by menno-ll** [comment]
Hi @veewee ,
Thank you for the response.
I will attempt to use the iteratorassembler to fix the docblock types.
Have a great day!

**Comment by veewee** [comment]
Hello,

We noticed this issue got reported many times and want to tackle it at its core!
Therefore, we've planned a [project that will work on better types support](https://github.com/php-soap/.github/blob/main/PROJECTS.md#better-types).
It’s going to be a huge project, so we are looking for ways to make development possible during our business hours instead of in our developers precious spare time.

In case you want this feature as badly as us: **[find out how you can support this project here 💚](https://github.com/php-soap/.github/blob/main/HELPING_OUT.md)**!
