### ISSUE TITLE
better static analysis support

### ISSUE THREAD

**Issue by staabm** [phpro/soap-client#379]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

while class-generation classes implementing `IteratorAggregate` should get a few annotations, to make php static analysis tools (psalm, phpstan,..) aware of the actual types beeing wrapped.

as is the generator, produces code like

```
class ArrayOfSalesOrderLinesWS implements IteratorAggregate
{

    /**
     * @var \WebConnector\Order\Type\SalesOrderLinesWS
     */
    private $Sales_Order_Lines_WS;

    /**
     * @return \ArrayIterator
     */
    public function getIterator()
    {
        return new \ArrayIterator(is_array($this->Sales_Order_Lines_WS) ? $this->Sales_Order_Lines_WS : []);
    }
```

for static analysis tools, this construct hides the actual types beeing wrapped behind the `IteratorAggregate`.

if the code beeing generated would look like e.g.
```
/**
 * @phpstan-implements IteratorAggregate<int, SalesOrderLinesWS>
 */
class ArrayOfSalesOrderLinesWS implements IteratorAggregate
{

    /**
     * @var \WebConnector\Order\Type\SalesOrderLinesWS
     */
    private $Sales_Order_Lines_WS;

    /**
     * @return \ArrayIterator
     */
    public function getIterator()
    {
        return new \ArrayIterator(is_array($this->Sales_Order_Lines_WS) ? $this->Sales_Order_Lines_WS : []);
    }
``` 

phpstan could make use of this additional knowledge, see https://phpstan.org/r/337a116c-75c2-4ba1-abf8-3b3f04424d0d

**Comment by staabm** [comment]
example of how it is right now, and how it could be:

https://phpstan.org/r/a539bc17-e946-4df0-939a-083eba57237f

**Comment by clxmstaab** [comment]
after a bit of research, I guess the class which needs tweaking is https://github.com/phpro/soap-client/blob/master/src/Phpro/SoapClient/CodeGenerator/Assembler/IteratorAssembler.php

**Comment by veewee** [comment]
Sounds nice. One of the issues is that we are currently not able to detect if a type is an array or a single occurence.
See: https://github.com/phpro/soap-client/blob/master/docs/known-issues/ext-soap.md#occurs

The properties are generated seperately from the iterator.
So it is possible to add an `@implements` attribute on the iterator, but it might not be possibly to type the property in a correct way. This will still result in static analyzer complaints.

I'dd also rather add a generic annotation than a psalm and/or phpstan specific one.
Normally they both accept `@implements`.

Feel free to provide a PR.

**Comment by staabm** [comment]
moving this discussion into the PR
