### ISSUE TITLE
testsuite isn't green on windows

### ISSUE THREAD

**Issue by staabm** [phpro/soap-client#381]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes/no
| Version     | a91e2fe

#### Summary

seems there is some expect vs. actual mismatches because of windows specifics

#### Current behavior

e.g.

![grafik](https://user-images.githubusercontent.com/120441/123601471-02934800-d7f8-11eb-8891-194c4b2703ab.png)

![grafik](https://user-images.githubusercontent.com/120441/123601564-1c348f80-d7f8-11eb-9296-3fb410e3c748.png)

#### How to reproduce

just run `vendor/bin/phpunit` in the the project root on windows

#### Expected behavior

at best the suite should be green

**Comment by veewee** [comment]
Can you tell me what version of laminas-code you are using?
Since it should be hardcoded to `\n`:

https://github.com/laminas/laminas-code/blob/b549b70c0bb6e935d497f84f750c82653326ac77/src/Generator/AbstractGenerator.php#L25

**Comment by staabm** [comment]
I am on
```
             "name": "laminas/laminas-code",
            "version": "3.5.1",
```

I guess the problem is git turning line endings into \r\n because auf auto-crlf

**Comment by veewee** [comment]
Ah yes, that shall be the issue indeed!
Not sure if it's a good idea to disable auto-crlf?

**Comment by staabm** [comment]
> Not sure if it's a good idea to disable auto-crlf?

I think this is the way to go, in case the unit tests pass on windows then

**Comment by clxmstaab** [comment]
setting auto-crlf fixes most but not all problems, see https://github.com/phpro/soap-client/pull/383 

will investigate further
