### ISSUE TITLE
GrumPHP commit hook makes it "impossible" to contribute from windows

### ISSUE THREAD

**Issue by staabm** [phpro/soap-client#382]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes/no
| Version     | a91e2fe

#### Summary

because of the [non-green test-suite on windows](https://github.com/phpro/soap-client/issues/381), it is really hard to contribute when using windows

#### Current behavior

the commit hook errors

![grafik](https://user-images.githubusercontent.com/120441/123602061-a8df4d80-d7f8-11eb-995a-0b6e4a734e84.png)

#### How to reproduce

change code and try to commit

#### Expected behavior

it should be easy to contribute, without hurdles

**Comment by staabm** [comment]
for now I use a workaround described in https://ma.ttias.be/git-commit-without-pre-commit-hook/

**Comment by veewee** [comment]
Thanks for reporting.
For now we'll keep using grumphp, since it is our internal policy. You can indeed skip the checks by using the `-n` option during commit.

The issue here is that the tests are not green on windows. Lets fix that in issue #381.
