### ISSUE TITLE
Deprecated dependecy with guzzle

### ISSUE THREAD

**Issue by fbecker-complex** [phpro/soap-client#385]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 1.7.0

#### Summary

Since I updated https://github.com/guzzle/guzzle to  `v7.3.0` and https://github.com/guzzle/psr7 to `v2.0.0`, I get the following error message on soap-requests:
```
'Error' with message 'Call to undefined function GuzzleHttp\Psr7\stream_for()' (0)
> in .../vendor/php-http/message/src/StreamFactory/GuzzleStreamFactory.php:21
```
The given class is deprecated:
![image](https://user-images.githubusercontent.com/71324952/127137501-213f2ba4-6297-40aa-8b3f-1e0bb4725716.png)

The function used to set a StreamFactory, ` StreamFactoryDiscovery::find()` in `HttPlugHandle.php`(l.63), is also deprecated:
![image](https://user-images.githubusercontent.com/71324952/127135924-4b20ebe9-4966-488a-8245-fdacf2adeeee.png)

### Solution
I fixed it for my project by limiting `guzzlehttp/psr7` to `v1.7.0`, but that's not a permanent solution

### Question
Would you consider exchanging the deprecated methods, so we can remove the fixed version workaround?

**Comment by veewee** [comment]
This looks like an issue in one of the httplug packages rather than this package..
Did you tried upgrading php-http/message as well?

**Comment by fbecker-complex** [comment]
> This looks like an issue in one of the httplug packages rather than this package..
> Did you tried upgrading php-http/message as well?

Thanks for the quick reply!
I tried including all php-http/* dependencies directly, but still got the same result.
I'm gonna investigate a further tomorrow and tell you about my findings.

**Comment by fbecker-complex** [comment]
> This looks like an issue in one of the httplug packages rather than this package..
> Did you tried upgrading php-http/message as well?

You were right, the error was in the `php-http/message`. A colleague of mine already developed a fix, which will be merged shortly: https://github.com/php-http/message/pull/141

I am going to close this issue.
