### ISSUE TITLE
Backport the fix onto v1.3.2

### ISSUE THREAD

**Issue by hgraca** [phpro/soap-client#393]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | no
| RFC         | no
| BC Break    | no

#### Summary

I would like to backport the fix made by @veewee , namely this one: https://github.com/phpro/soap-client/pull/335 to the version 1.3.2. I have it cherry picked in a fork, but in order to make a PR, I think I need a branch for it in this repository so that, if approved, you can make a new tag (v1.3.3).

How should we do this?

Tkx.

**Comment by veewee** [comment]
Hello,

Any specific reason you want to backport a 1 year old version with a 1 year old bugfix instead of using a more battle tested newer version of this package?

**Comment by hgraca** [comment]
Unfortunately, a legacy codebase landed on my lap, it uses PHP 7.2, so... Can't use a more recent version of this library :(

**Comment by veewee** [comment]
Hello @hgraca,

Sorry but I don't see the value into backporting that specific issue in an older version.
The PHP core team isn't supporting that version for almost 2 years now, so I don't really see why we should be spending our time on this.

Feel free to use your own patch.
You can also include it in your codebase or in a separate repo by using https://github.com/cweagans/composer-patches e.g.

**Comment by hgraca** [comment]
Hah!! I never heard about that package, that is great!! 

Tkx for taking time to make the suggestion, it will work perfectly until we get our codebase out of the swamp!

Keep up the good work!
