### ISSUE TITLE
Empty SOAPAction header

### ISSUE THREAD

**Issue by ro0NL** [phpro/soap-client#398]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no?
| Version     | 1.7

#### Summary

After swithcing an implementatin from native `\SoapClient` to this library, i noticed some issues.

Natively a `SOAPAction: ""` header is sent (which maybe is a bug :shrug:), but the library sends `SOAPAction: `

As such we now get a 400 bad request :joy: 

```
The HTTP request was missing the SOAPAction header
```

Causing the library to crash ... :(

#### How to reproduce

Maybe it's WSDL specific ..., but a regular request based on HTTPlug transport should do.

#### Expected behavior

Same as native.

Perhaps related to #195

**Comment by ro0NL** [comment]
Btw, im totally hacking my way around things:

```php
public function callSimple(string $method, array $arguments)
{
    $request = new class($arguments) implements MultiArgumentRequestInterface {
        private array $arguments;

        public function __construct(array $arguments)
        {
            $this->arguments = $arguments;
        }

        public function getArguments(): array
        {
            return $this->arguments;
        }
    };

    return $this->call($method, $request);
}
```

So perhaps, it causes a compatibilty issue with your library.

**Comment by ro0NL** [comment]
Fix

```
        $handlerStack->push(Middleware::mapRequest(function (RequestInterface $request) {
            // @see https://github.com/phpro/soap-client/issues/398
            if ([''] === $request->getHeader('SOAPAction')) {
                $request = $request->withHeader('SOAPAction', "''");
            }

            return $request;
        }));
```

**Comment by veewee** [comment]
Have you tried using this plugin?

https://github.com/php-soap/psr18-transport#wsicompliancequotedsoapactionmiddleware

**Comment by ro0NL** [comment]
Sorry for my bad SOAP protocol knowledge :}

`QuotedSoapActionMiddleware` looks generally usefull :+1:

I figured i could leverage `HttPlugHandle::addMiddleware`, rather than `$handlerStack->push(` :+1: 

> But we might add it

You mean register it by default in 2.x? If _"guarantee compatibility with the WS-I basic profile"_ is the goal, then yes?

However, i'm not sure what can be done from `ExtSoapEngineFactory` POV ...

IIUC, custom handlers behave different compared to `ExtSoapClientHandle` (but this might only be relevant for ExtSoapDriver?)

I will update to v2, once we've updated to php8 :')

**Comment by veewee** [comment]
I rather meant adding a '' case when the soap action is empty whilst building the psr-7 request:

https://github.com/php-soap/psr18-transport/blob/main/src/HttpBinding/Psr7RequestBuilder.php#L152

As you mentioned in your initial comment, it works this way by default internally in the \SoapClient.
So we only need to change the psr-7 request builder.

**Comment by ro0NL** [comment]
in that sense, im not sure \SoapClient conditionally quotes $action. I can check some other implementations tomorrow.

**Comment by ro0NL** [comment]
@veewee another implentation sets an URI for $action, at this point \SoapClient always quotes.

This other implementation would also crash if $action is an empty string, either quoted on unquoted.

I still tend to believe quoting is tied to ExtSoap, and could be done by default. I leave this up to you for 2.x

`QuotedSoapActionMiddleware` solves our issue on 1.7 :+1: 

If anything, users may struggle during migrating (as i ended up here as well), but perhaps it's out-of-scope from this library POV.

Thanks :+1:
