### ISSUE TITLE
PHP 8.1 Compatibility

### ISSUE THREAD

**Issue by veewee** [phpro/soap-client#399]
Making this package compatible with PHP 8.1 has some upstream deps that are not compatible yet:

- [x] https://github.com/laminas/laminas-code -> v4.5  (Validated in #405)
- [x] phpspec: https://github.com/phpspec/phpspec/pull/1397

**Comment by pottink** [comment]
I bumped the version of the laminas-code package in https://github.com/phpro/soap-client/pull/405

**Comment by jdreesen** [comment]
> I bumped the version of the laminas-code package in #405

I don't think that's necessary, as installing v4.5 is already allowed and composer will choose this if you're installing on PHP 8.1.

**Comment by janvernieuwe** [comment]
I've checked this, still need to wait on phpspec fix.
Development workaround is to install with `--ignore-platform-reqs` until phpspec is ready (remeber to install all required ext-* first!).

**Comment by NielsdeBlaauw** [comment]
PHPSpec 7.2.0 with php8.1 support has been released yesterday: https://github.com/phpspec/phpspec/releases/tag/7.2.0

**Comment by veewee** [comment]
Thanks for reporting. Will have to find some time to test it out in here - unless someone else beats me to it :)
