### ISSUE TITLE
Segmentation fault in wizard ($client->__getTypes() causing segmentation fault)

### ISSUE THREAD

**Issue by abbajbryant** [phpro/soap-client#402]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes/no
|Version     | 2.0

#### Summary

Using the following wsdl and xsd document causes the wizard to segmentation fault. This happens when using the soap client directly as well when calling __getTypes(). Is it possible to identify what about this wsdl file is causing the issue?

.wsdl: https://gist.github.com/abbajbryant/b33701b27869ab659ed95921671c92fc
.xsd: https://gist.github.com/abbajbryant/ff5d8845048ac8e0fa7e6270f0e60645

#### Current behavior
`./vendor/bin/soap-client wizard

 Where would you like to store your config file? [config/soap-client.php]:
 > 

 Wsdl location (URL or path to file):
 > wsdl/AirPricing.wsdl

 Should methods be generated with docblocks? (yes/no) [yes]:
 > 

 Generic name used to name this client (Results in <name>Client <name>Classmap etc.):
 > AirPricing

 Directory where the client should be generated in:
 > src

 Namespace for your client:
 > App

                                                                                                                        
 [OK] Config has been written to config/soap-client.php                                                                 
                                                                                                                        

Segmentation fault (core dumped)
`

#### How to reproduce
run the wizard or instantiate a SoapClient with the provided wsdl. Any calls to $client->__getTypes() will fail with a segmentation fault.

#### Expected behavior
it should generate type objects.

**Comment by veewee** [comment]
This is probably something for the people of php internals to investigate on bugs.php.net.

I've seen an issue in here that might be related:

- https://github.com/phpro/soap-client/issues/373
- https://bugs.php.net/bug.php?id=81154

**Comment by veewee** [comment]
Closing this one for now. Feel free to reopen if you have more information or questions regarding this issue.

**Comment by veewee** [comment]
I just noticed this is the same WSDL as in #373. Maybe @arno14 found a solution?

**Comment by arno14** [comment]
I did not find any solution using php Soap Extension or phpro/soap-client.

So I requested the Soap Server with Guzzle Http Client 
and parsed the xml HTTP Body with DomDocument to extract the datas I needed.

**Comment by apausepi** [comment]
Hello I have the same issue.
Is it from you this issue https://bugs.php.net/bug.php?id=81154
Doesn't work with Protel WSDL (OTA XSD Files). I suppose because there is an infinite loop inside the xsd files. OTA_Reservation (importSchema).

Do you use SoapServer to send data (if your case) or you use GuzzleHttpClient too ? 

I'm searching a solution too.
