### ISSUE TITLE
How to throw SoapException for http errors?

### ISSUE THREAD

**Issue by tgerakitis** [phpro/soap-client#404]
|    Q        |   A
|------------ | -----
| Version     | 1.7.1

### Support Question

Instantiating everything using `ExtSoapOptions::defaults` I assumed `SoapFaults` would be thrown and caught via a `SoapException` as described in the docs [here](https://github.com/phpro/soap-client/blob/662dce2fa88ecb061c22b4b459bb738ff9bbbc17/docs/client.md#creating-your-custom-client). 

In my case, the server was gone and responded with a `403`:
![image](https://user-images.githubusercontent.com/34158395/146170434-a97b7aa7-9751-4cf3-b4f3-c5249cedf110.png)
![image](https://user-images.githubusercontent.com/34158395/146171657-56384154-2639-4766-a7da-fa873344ee5f.png)

I'm probably just using it wrong, but how can I make these cases throw a `SoapException`?

**Comment by veewee** [comment]
Can you show me how you configure the client?
A SoapException will be triggered in https://github.com/phpro/soap-client/blob/master/src/Phpro/SoapClient/Caller/EngineCaller.php#L37 if it receives an exception.

It is possible that your HTTP client does not trigger an exception with error codes like 4xx / 5xx. That is something that needs to be configured in the HTTP client.

**Comment by veewee** [comment]
Can you show me your configuration?

**Comment by tgerakitis** [comment]
thank you @veewee

<?php

use Phpro\SoapClient\CodeGenerator\Assembler;
use Phpro\SoapClient\CodeGenerator\Rules;
use Phpro\SoapClient\CodeGenerator\Config\Config;
use Phpro\SoapClient\Soap\Driver\ExtSoap\ExtSoapOptions;
use Phpro\SoapClient\Soap\Driver\ExtSoap\ExtSoapEngineFactory;

My config for generating the stubs:
```
<?php
return Config::create()
    ->setEngine($engine = ExtSoapEngineFactory::fromOptions(
        ExtSoapOptions::defaults(__DIR__ . '/hidden-wsdls/hidden_2_0.wsdl', [])
            ->disableWsdlCache()
    ))
    ->setTypeDestination(__DIR__ . '/stubs/hidden2/Type')
    ->setTypeNamespace('app\config\events\ctiscca\stubs\hidden2\Type')
    ->setClientDestination(__DIR__ . '/stubs/hidden2/')
    ->setClientName('hidden2Client')
    ->setClientNamespace('app\config\events\ctiscca\stubs\hidden2')
    ->setClassMapDestination(__DIR__ . '/stubs/hidden2/')
    ->setClassMapName('hidden2Classmap')
    ->setClassMapNamespace('app\config\events\ctiscca\stubs\hidden2')
    ->addRule(new Rules\AssembleRule(new Assembler\GetterAssembler(
        (new Assembler\GetterAssemblerOptions())
            ->withReturnType(false)
    )))
    ->addRule(new Rules\AssembleRule(new Assembler\ImmutableSetterAssembler(
        new Assembler\ImmutableSetterAssemblerOptions()
    )))
    ->addRule(
        new Rules\IsRequestRule(
            $engine->getMetadata(),
            new Rules\MultiRule([
                new Rules\AssembleRule(new Assembler\RequestAssembler()),
                new Rules\AssembleRule(new Assembler\ConstructorAssembler(new Assembler\ConstructorAssemblerOptions())),
            ])
        )
    )
    ->addRule(
        new Rules\IsResultRule(
            $engine->getMetadata(),
            new Rules\MultiRule([
                new Rules\AssembleRule(new Assembler\ResultAssembler()),
            ])
        )
    );
```

My client config:
```
<?php
$engine = ExtSoapEngineFactory::fromOptions(
            ExtSoapOptions::defaults(__DIR__ . '/hidden-wsdls/hidden_2_0.wsdl', [
                'location' => 'https://custom.location.com/',

            ])
                ->withClassMap(hidden2Classmap::getCollection())
        );
        $eventDispatcher = new EventDispatcher();

        return new hidden2Client($engine, $eventDispatcher);
```

**Comment by veewee** [comment]
The configuration looks ok. I assume you use the client to perform the calls.
A SoapFault should be caught right here:

https://github.com/phpro/soap-client/blob/ff6fd43cb8ab80aa88dedb4c4870942102134b83/src/Phpro/SoapClient/Client.php#L116-L119

**Comment by tgerakitis** [comment]
@veewee I don't really need a specific exception, just anykind of exception. 
Currently, in my example a `MixedResult` is returned here https://github.com/phpro/soap-client/blob/ff6fd43cb8ab80aa88dedb4c4870942102134b83/src/Phpro/SoapClient/Client.php#L114

**Comment by tgerakitis** [comment]
@veewee it is empty, in my case the `$result` was just `null`, I see so ext-soap only throws on errors that are in `xml`.

So how would I use an httplug to react to HTTP status codes that are `>=400`?

**Comment by veewee** [comment]
Ah yes, it does that sadly indeed.
Might be a better idea to throw errors on null responses from ext-soap on our side as well. But will have to investigate if null always means "error".

See https://github.com/phpro/soap-client/blob/v1.7.x/docs/handlers/httplug.md

You can use any http client, like guzzle or symfony/http-client.
On both, you can configure that it throws exceptions on invalid status codes.

**Comment by tgerakitis** [comment]
> Ah yes, it does that sadly indeed. Might be a better idea to throw errors on null responses from ext-soap on our side as well. But will have to investigate if null always means "error".

Not sure if there are situations where a healthy soap service responds with an empty body... 
Maybe it would be more robust throwing errors depending on the server HTTP response code? e.g. if it is a `>=400` in the `AbusedClient` directly or by parsing the `$this->engine->collectLastRequestInfo()->getLastResponseHeaders()` in the `Client` next to the other Exceptions?

**Comment by veewee** [comment]
This is exactly one of the reasons why we are pushing a userland HTTP client by default in version 2 of this package...
There are a lot of known errors with SoapClient's internal HTTP implementation, which we don't have to deal with if you use a decent HTTP client :)

**Comment by tgerakitis** [comment]
> This is exactly one of the reasons why we are pushing a userland HTTP client by default in version 2 of this package... There are a lot of known errors with SoapClient's internal HTTP implementation, which we don't have to deal with if you use a decent HTTP client :)

fully understood, thank you @veewee ! :)
