### ISSUE TITLE
Traversable is implemented but never used for ArrayOf types when re-generating classes

### ISSUE THREAD

**Issue by sippsolutions** [phpro/soap-client#411]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 1.7.2

#### How to reproduce

Generate classes and use the IteratorAssembler for ArrayOf types as mentioned in https://github.com/phpro/soap-client/issues/231#issuecomment-549674310
Be sure to use a SOAP Service with ArrayOf types.
When you generate the classes for the first time, everything is fine.
When you execute the generation again, the files get patched:

    Generated class Xyz\Type\ArrayOfXyz to src/Type/ArrayOfXyz.php
    Type ArrayOfXyz exists. Trying to patch ...Patched!

But the patch results in implementing Traversable:

    -class ArrayOfXyz implements IteratorAggregate
    +class ArrayOfXyz implements IteratorAggregate, Traversable

but Traversable is never used, only IteratorAggregate:

    use IteratorAggregate;

which results in not finding the class:

    Fatal error:  Uncaught Error: Interface 'Xyz\Type\Traversable' not found in ...

Even if we import Traversable, this results in a fatal error as well:

    Class cannot implement previously implemented interface

A workaround is to delete the classes before generating them again.

#### Current behavior

Traversable is implemented.

#### Expected behavior

Traversable should not be implemented.

**Comment by veewee** [comment]
The patching logic got removed in v2 since it results in this kind of bugs. We decided to go for a regenerate all types from scratch approach.
For V1, this means you'll need to remove the old type files first.
