### ISSUE TITLE
Caching / Build SOAP response objects with a stored XML

### ISSUE THREAD

**Issue by sippsolutions** [phpro/soap-client#412]
Is there any documentation in how to implement a file based caching (so when the same request should be sent and this exact request was sent less than 1 minute ago, just return the cached result)?
Is it possible to create the SOAP types from a response XML string without actually calling the SOAP service?

`$typeInstance = $xyz->decode($xml)`

Thanks in advance.

**Comment by veewee** [comment]
Caching is not part of this package and not documented either.
There are various ways to do so:

- Add caching middleware on the HTTP layer
- Decorate the `Caller` with your own CachingCaller
- Decorate the client with a caching client
- Decorate your own code where needed
- ...


It is possible to run the `decode()` method with any xml string without actually performing the soap call.
We use this technique to mock soap responses in some of our application's testsuite.
