### ISSUE TITLE
Soap Header in Request possible?

### ISSUE THREAD

**Issue by ynnoig** [phpro/soap-client#413]
|    Q        |   A
|------------ | -----
| Version     | 1.7.2 or 2.1.0

### Support Question

Hi phpro Team, we use in our project your library with success since some years to communicate via soap with an ftp service. Now we have to integrate another Soap client to communicate with another service and this one requires in its WSDL a Soap-Header to be sent at each request for authentication. How is it possible to do this with this library since the soap client only allows to send a Soap-Body? Do I need some Middleware to inject in the soap factory or something similar?

The WSDL of the service is the following:
https://www.elgate.biz/Elgate/ElgateService.asmx?WSDL

and as you can see each operation has a soap:body and a soap:header and what I can't understand is how to send the soap:header part through this library.

Thank you in advance for your support!

**Comment by veewee** [comment]
Hello there,

Glad to hear you are successfully using this library!

The suggested way is indeed to use a HTTP middleware for that.
We currently don't have a default middleware for this, but it might make sense to add it.

It would look like this:

```php
<?php

use Http\Client\Common\Plugin;
use Http\Promise\Promise;
use Psr\Http\Message\RequestInterface;
use Soap\Psr18Transport\Xml\XmlMessageManipulator;
use Soap\Xml\Builder\SoapHeaders;
use Soap\Xml\Manipulator\PrependSoapHeaders;
use VeeWee\Xml\Dom\Document;
use function VeeWee\Xml\Dom\Builder\element;
use function VeeWee\Xml\Dom\Builder\value;

class SoapHeaderMiddleware implements Plugin
{
    public function handleRequest(RequestInterface $request, callable $next, callable $first): Promise
    {
        return $next((new XmlMessageManipulator)(
            $request,
            function (Document $document) {
                $headers = $document->build(new SoapHeaders(
                    element('Username', value('veewee')),
                    element('Password', value('xxx')),
                ))[0];

                return $document->manipulate(new PrependSoapHeaders($headers));
            }
        ));
    }
}
```

A less recommended way to add headers, is by adding them directly on the `AbusedClient`:

```php

$engine = new SimpleEngine(
    ExtSoapDriver::createFromClient(
        $client = AbusedClient::createFromOptions(
            ExtSoapOptions::defaults($wsdl, [])
        )
    ),
    $transport
);

$client->__setSoapHeaders(...);
```

**Comment by ynnoig** [comment]
Thanks for the quick response and your support.

Yes I had thought about Middleware but had no idea how to integrate it. I will definitely start from your example to create my middleware and then I will leave you a Feedback as soon as possible.

Thanks again and best regards

**Comment by veewee** [comment]
FYI : This became a default middleware (https://github.com/php-soap/psr18-transport/releases/tag/v1.2.0)
