### ISSUE TITLE
Let final client decide content-length

### ISSUE THREAD

**Issue by ro0NL** [phpro/soap-client#416]
Hi,

This line: https://github.com/phpro/soap-client/blob/c6e16145515fd08d5ca57339c2fcdb38189cd70b/src/Phpro/SoapClient/Soap/HttpBinding/Builder/Psr7RequestBuilder.php#L213

caused some serious debugging on our side, in a case where an auth header was added to the body at plugin level.

httplug happily ignores it: https://github.com/php-http/curl-client/blob/2ed4245a817d859dd0c1d51c7078cdb343cf5233/src/Client.php#L346

but when switching to sf/http-client it broke our call, because the endpoint did not expect it to be invalid.

Would you consider removing it, and let the final client deal with it.

In our case a request without content-length header still passes, so the workaround _eventually_ was fixing the auth plugin:

```diff
-            return $next($request->withBody($xml->toStream()));
+            return $next($request->withBody($xml->toStream())->withoutHeader('content-length'));
```

And then it started working with Symfony Psr18 client :tada: 

I will create a feature request also for Symfony, to set a default content-length either way :angel:

**Comment by veewee** [comment]
Awtsch ... Yes, let's drop that content-length header calculation alltogether in here. Otherwise you'll need to recalculate on every body change.
If a specific HTTP client requires it, it can be calculated by a plugin (which might also be a temporary fix for you)
https://docs.php-http.org/en/latest/plugins/content-length.html

Care to create a PR?

**Comment by ro0NL** [comment]
@veewee im not sure about 1.7 btw ...maybe we should sell it as new feature, eg. to be replaced with `ContentLengthPlugin` for an upgrade.

Symfony (https://github.com/symfony/symfony/pull/45261) and [httplug](https://github.com/php-http/curl-client/blob/2ed4245a817d859dd0c1d51c7078cdb343cf5233/src/Client.php#L343-L346) will only alter "submitted" headers. Removing the initial header now breaks that IIUC.

**Comment by veewee** [comment]
@ro0NL : if no content-length header is provided, curl sets one internally IIRC. 
This works similar as a regular http requests directly on the client: if you don't provide any content-length, the HTTP client still knows what to do.
If that's the case, then I don't see any benefit from setting it from within the soap-client.

If this solves anyone from having to debug issues like that, then I am willing to backport it to 1.7.
