### ISSUE TITLE
Support newer versions of psr/log 

### ISSUE THREAD

**Issue by rimas-kudelis** [phpro/soap-client#429]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | no
| RFC         | no
| BC Break    | no

#### Summary

This package currently requires `"psr/log": "^1.0"`, while version 3 is already available. It would be nice if it accepted other versions as well, e.g. `"^1.0 || ^2.0 || ^3.0"`.

**Comment by veewee** [comment]
Thanks for reporting @rimas-kudelis.
Care to make a PR for that?

**Comment by rimas-kudelis** [comment]
@veewee could you tag new releases with this functionality?
I was quite certain I saw something about that in the notification emails I received, but now I don't see any new tags here nor new versions in Packagist.

**Comment by veewee** [comment]
It wasn't tagged yet. Now it is :)

https://github.com/phpro/soap-client/releases/tag/v2.2.1
https://github.com/phpro/soap-client/releases/tag/v1.7.4
