### ISSUE TITLE
Generating PHP classes and class map

### ISSUE THREAD

**Issue by rps-repo** [phpro/soap-client#43]
Where is soap-client generate:types supposed to be executed from?

**Comment by veewee** [comment]
Hi @rps-repo,

You can execute it from where you want. Are you facing any issues with the command?
Do note that you'll have to require zend-code as specified in the docs before you can use the command:

```
composer require --dev zendframework/zend-code:^3.0.4
```

**Comment by rps-repo** [comment]
I figured it out.  The docs do not say where soap-client is located.  In my case I needed to execute:
`./application/vendor/phpro/soap-client/bin/soap-client generate:types --config=config.php`

**Comment by tknuppe** [comment]
Thanks @rps-repo . I searched for it a couple of minutes. Just found out that a symlink is available in vendor/bin, too.

**Comment by veewee** [comment]
The documentation has been improved by @tknuppe. I am closing this one.
