### ISSUE TITLE
How to parse SOAP error responses

### ISSUE THREAD

**Issue by kinglozzer** [phpro/soap-client#440]
|    Q        |   A
|------------ | -----
| Version     | 1.7.4

### Support Question

Hi,

I’m using a SOAP API that can issue errors like this:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
    <soapenv:Header/>
    <soapenv:Body>
        <soapenv:Fault>
            <faultcode>soapenv:Client</faultcode>
            <faultstring xml:lang="en">Validation error</faultstring>
            <detail>
                <ns2:searchFault xmlns:ns2="http://serviceurl.com">
                    <code>ABCD1234</code>
                    <message>Fault message goes here</message>
                </ns2:searchFault>
            </detail>
        </soapenv:Fault>
    </soapenv:Body>
</soapenv:Envelope>
```

In the event of an error, a `Phpro\SoapClient\Exception\SoapException` is thrown. There is a PHP class generated for this type, is there any way to automatically instantiate & populate it with error details?

I assume it’s being detected as an error because the API server issues a 500 response code.

I’m currently adding an event listener for `Phpro\SoapClient\Events::FAULT`, and I think my backup plan is to use `Client::debugLastSoapRequest()` to grab the raw response and parse the error out manually.

Thanks!

**Comment by veewee** [comment]
Hello,

I think the proper approach is to indeed use the fault event, or to catch the exception and transform that one.
But it essentially the same as catching the exception and to deal with it in the way you want.

The SoapException contains the SoapFault (previousException()) on which you can grab the faultcode, string and detail
