### ISSUE TITLE
Add check for available classes

### ISSUE THREAD

**Issue by yenyasinn** [phpro/soap-client#446]
There is todo in TypeChecker::isClassType() https://github.com/phpro/soap-client/blob/master/src/Phpro/SoapClient/CodeGenerator/Util/TypeChecker.php#L46-L50 - "add check for available classes".

The aim of this ticket to implement this check.

**Comment by yenyasinn** [comment]
@veewee how did you plan to check if the class is available?

We can not use simple `class_exists()` since types that should be used in property description aren't generated yet.

**Comment by veewee** [comment]
It has been a long time since that code was created.
In an old version, it indeed checked if the class exists. Until we noticed this did not work because the code was not generated yet.

I don't see an easy solution ATM, since it all are static functions.
Will have to go through some code to see where and how it is used and how it is supposed to work.
Since it is like this for about 5 years, de might as well drop that function if we don't find a better solution

**Comment by yenyasinn** [comment]
PR https://github.com/phpro/soap-client/pull/447 has been opened.

I have not found a way how to check whether classes exists or not, since classes aren't existed during generation. 
Added a regular expression to check that provided string is a class name.
Actually not sure that we need `TypeChecker` at all. It is used in `FluentSetterAssembler` assembler only and actually `Normalizer` provide us already prepared types. Might be solution https://github.com/phpro/soap-client/pull/307#issuecomment-652787375 isn't so bad?

**Comment by veewee** [comment]
thanks @yenyasinn,

Hmm good find!
If it is only being used in `FluentSetterAssembler`, we should probably nuke the whole `TypeChecker` class.
Can we generate the parameters like we do it in `SetterAssembler` instead?
That one indeed uses the normalizer through `\Phpro\SoapClient\CodeGenerator\Model\Property::getCodeReturnType()`

https://github.com/phpro/soap-client/blob/9c616b677df4c7038a17a5c5390becadf3f7b55e/src/Phpro/SoapClient/CodeGenerator/Assembler/SetterAssembler.php#L52-L55

This way, it works the same over all setters.

**Comment by yenyasinn** [comment]
Updated PR https://github.com/phpro/soap-client/pull/447 - expanded regular expression to validate class name.

Created PR https://github.com/phpro/soap-client/pull/448 - TypeChecker has been removed completely. IMHO this solution looks better than in PR 447 with regexp.

**Comment by veewee** [comment]
Closing this one - it will be dealt with in https://github.com/phpro/soap-client/issues/464
