### ISSUE TITLE
How can I get the XML being sent to the SOAP API?

### ISSUE THREAD

**Issue by danr1979** [phpro/soap-client#451]
|    Q        |   A
|------------ | -----
| Version     | 2.2.1

### Support Question

Hi.

I've been through all the docs and support tickets I can find but I still can't find a way of seeing the XML that is being generated by the library to send to the SOAP API.  I just want to see a string representation of the XML.

Is anyone able to help me?

Thank you.

Dan

**Comment by veewee** [comment]
You can either:

* Use the Httplug logger plugin. Example see docs : https://github.com/php-soap/psr18-transport#httplug-middleware
* Use the TracableTransport. Example see docs : https://github.com/php-soap/ext-soap-engine/#example-usage

**Comment by danr1979** [comment]
Thanks @veewee.
