### ISSUE TITLE
fixed version of laminas/laminas-code

### ISSUE THREAD

**Issue by eremin** [phpro/soap-client#462]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | ^2.3.0

#### Summary

`laminas/laminas-code` is now fixed to version 4.8.0 that conflicts with the in project installed version 4.10.0

#### Current behavior

i have described it already in summary

#### How to reproduce

look at `composer.json` file

#### Expected behavior

Unlock the version upwarts ('^4.8.0' sounds good)

**Comment by veewee** [comment]
Hello,

I'm not sure why it was set to fixed, but allowing `^4.8.0` seems about right.
Care to create a PR for this?

**Comment by veewee** [comment]
Fixed in v3 branch - feel free to create a pr if you need it in v2 as well.

**Comment by lkck24** [comment]
I'll create a PR for v2.

**Comment by lkck24** [comment]
I'll create a PR for v2.
