### ISSUE TITLE
Detected type object is bad, must be an array

### ISSUE THREAD

**Issue by h4kuna** [phpro/soap-client#469]
### Bug Report

Hello, i implement this [wsdl](https://immobinetagenzie.immobinet.it/webservices/webservicemodagenzia/service.wsdl) and here is graphical [view](https://immobinetagenzie.immobinet.it/webservice.wsdl#op.id15) where is method **getImmobili** and return object is **getImmobiliResponse** with property **immobili**. This property is returned like array but soap-client represent like object 

#### Current behavior

```php
    /**
     * @return \App\ChannelManager\ImmobiNet\Soap\Agenzia\Type\ArrayOfImmobile
     */
    public function getImmobili()
    {
        return $this->immobili;
    }
```
if i generate by typehint like 
```php
    public function getImmobili() : \App\ChannelManager\ImmobiNet\Soap\Agenzia\Type\ArrayOfImmobile
    {
        return $this->immobili;
    }
```
I get message **Agenzia\Type\ArrayOfImmobile::getImmobile(): Return value must be of type App\ChannelManager\ImmobiNet\Soap\Agenzia\Type\Immobile, array returned**

#### How to reproduce

You can see in you generated class.

#### Expected behavior

```php
    /**
     * @return array<\App\ChannelManager\ImmobiNet\Soap\Agenzia\Type\ArrayOfImmobile
>
     */
    public function getImmobili() : array
    {
        return $this->immobili ?? [];
    }
```

**Comment by veewee** [comment]
Thanks for reporting!
This will be fixed in 3.0. feel free to test out the pre-release:
https://github.com/phpro/soap-client/discussions/466

All feedback is welcome :)

**Comment by h4kuna** [comment]
Is this same case, for the input parameters? In example is paramter immobili descripbed like
```
immobili - optional ; type ArrayOfString
```

But generated code is:
```
class ArrayOfString
{
    /**
     * @var string
     */
    private $string;

    /**
     * @return string
     */
    public function getString()
    {
        return $this->string;
    }

    /**
     * @param string $string
     *
     * @return ArrayOfString
     */
    public function withString($string)
    {
        $new = clone $this;
        $new->string = $string;

        return $new;
    }
}
```

**Comment by veewee** [comment]
Hello,

Yes it is.
The behavior and problem space is described here:
https://github.com/phpro/soap-client/blob/master/docs/known-issues/ext-soap.md#occurs

It's just missing information in ext-soap, which has been reported many many times.

As mentioned in previous comment: we are working on fixing the occurs-related problems, together with enums, unions, extends, abstract,more advanced simple types ... issues based on missing informating. This will be done in v3:
https://github.com/phpro/soap-client/issues/464

You can already play around with the alpha or the v3 branch - but everything in there is still highly experimental.
It now works based on manually parsed WSDL information, based on this new package:
https://github.com/php-soap/wsdl-reader

If you do want to be using v2, I'dd suggest not to generate PHP type hints - but use the docblocks instead.
That way you can still cast to the expected types, by for example [using type casters](https://github.com/azjezz/psl/tree/next/src/Psl/Type).
