### ISSUE TITLE
Implement ImmutableSetterAssembler

### ISSUE THREAD

**Issue by veewee** [phpro/soap-client#47]
If your SOAP requests has a lot of optional parameters, it might be handy to skip the constructor and use immutable setters instead. The idea is to create an immutable setter assembler which generates PSR-7 like immutable `with*()` methods. (More info: http://www.php-fig.org/psr/psr-7/)

Example of generated code:
```php
class MyRequest implements RequestInterface
{
    /**
     * @var string
     */
    private $someFilter;

    /**
     * @param string $someFilter
     * @return MyRequest
     */
    public function withSomeFilter(string $someFilter): MyRequest
    {
        $new = clone $this;
        $new->someFilter = $someFilter;

        return $new;
    }
}
```

Usage:
```php
$request = (new MyRequest)->withSomeFilter('myfilter');
```

**Comment by janvernieuwe** [comment]
See PR https://github.com/phpro/soap-client/pull/51
