### ISSUE TITLE
Authentication with UserName & Password

### ISSUE THREAD

**Issue by StanBarrows** [phpro/soap-client#474]
|    Q        |   A
|------------ | -----
| Version     | 2.4

### Support Question

Hey there! I came across your great package and would like to use it for a project where I need to fetch invoices from a SOAP-Service. 

Their Service documentation shows examples of how you can establish connections only for .NET and Java. 

![CleanShot 2023-05-27 at 01 09 06@2x](https://github.com/phpro/soap-client/assets/10268813/f7e607ab-a67d-487e-8dbf-bd3dbbe209d3)

Can I specify UserName & Password for Authentication within this package they describe within their documentation?

```
client.ClientCredentials.UserName.UserName = "XXX";
client.ClientCredentials.UserName.Password = "YYY";
```

I'm happy to pay for any help or support during integration.

--- Link to the Implementation Documentation --- 
[460_109_en.pdf](https://github.com/phpro/soap-client/files/11580428/460_109_en.pdf)

**Comment by veewee** [comment]
Hello 

From looking at the docs, it seems like you need WSSE authentication.

You can find examples on how to do it here:
https://github.com/php-soap/psr18-wsse-middleware#wssemiddleware

The package supports both credentials and certificate authentication.

If those examples are  out sufficient, we can provide paid support by invoicing on an hourly rate.
If the examples are sufficient, we always accept donations: https://opencollective.com/php-soap

**Comment by StanBarrows** [comment]
Hey @veewee 

Thanks for the fast reply. I'm happy to get some paid support for setting up the two functions I need. I'll contact you shortly via E-Mail.

Cheers
Sebastian
