### ISSUE TITLE
Support laminas/laminas-code:^4.8.0

### ISSUE THREAD

**Issue by lkck24** [phpro/soap-client#475]
### Feature Request

Currently laminas/laminas-code is pinned to the exact version 4.8.0.

Is there a specific reason why ^4.8.0 is not allowed? So we could also use a newer version of laminas/laminas-code.

**Comment by veewee** [comment]
Duplicate of https://github.com/phpro/soap-client/issues/462
This is currently fixed for v3. Feel free to provide a PR for v2.
