### ISSUE TITLE
How to implement credentials in the SOAP client?

### ISSUE THREAD

**Issue by Dropelikeit** [phpro/soap-client#479]
|    Q        |   A
|------------ | -----
| Version     | 2.4.2

### Support Question

I have created the following ClientFactory using the wizard:
```php
<?php
declare(strict_types=1);

namespace App\Clients\Go;

use App\Clients\Go\GoClassmap;
use RuntimeException;
use Soap\Engine\SimpleEngine;
use Soap\ExtSoapEngine\AbusedClient;
use Soap\ExtSoapEngine\ExtSoapDriver;
use Soap\Psr18Transport\Psr18Transport;
use Symfony\Component\EventDispatcher\EventDispatcher;
use Phpro\SoapClient\Soap\DefaultEngineFactory;
use Soap\ExtSoapEngine\ExtSoapOptions;
use Phpro\SoapClient\Caller\EventDispatchingCaller;
use Phpro\SoapClient\Caller\EngineCaller;

final class GoClientFactory
{
    public static function factory(string $wsdl, string $login, string $password) : \App\Clients\Go\GoClient
    {
        $engine = DefaultEngineFactory::create(
            ExtSoapOptions::defaults($wsdl, [
                'login' => $login,
                'password' => $password,
            ])
                ->withClassMap(GoClassmap::getCollection())
        );

        $eventDispatcher = new EventDispatcher();
        $caller = new EventDispatchingCaller(new EngineCaller($engine), $eventDispatcher);

        return new GoClient($caller);
    }
}
```

As you can see, I try to insert my credentials into the ExtSoapOptions. Unfortunately I still get the message that I have not been authenfied, here is the error message: 
```json 
{"timestamp":"2023-08-06T21:40:46.887+00:00","status":401,"error":"Unauthorized","message":"Unauthorized","path":"/ws/4020/GOGenericWS/SendungsDaten"}
```

It's not because of the credentials themselves, as I tested them with the WSDL file via SOAPUi and I can successfully log in there.

I already debugged to take a closer look at sending the request, here I saw that no authentication header was created and sent along. Unfortunately I don't understand why the setting is ignored and how to do it correctly.

Could you help me?

**Comment by veewee** [comment]
Hello,

By default, this package now uses a custom PSR-18 based HTTP client.
All http related options from the SoapClient are currently not being applied to that client.

Instead, you'll have to configure it directly on the http client or by adding an [authentication middleware](https://docs.php-http.org/en/latest/plugins/authentication.html).

More info:
https://github.com/php-soap/psr18-transport

(`$transport` is the second parameter on ` DefaultEngineFactory::create()`)

**Comment by Dropelikeit** [comment]
@veewee Thank you for your quick reply, now it works!

Thank you for your beautiful package! :)
