### ISSUE TITLE
Upgrading from 1.7 to 2.x breaks soap requests

### ISSUE THREAD

**Issue by JoppeDC** [phpro/soap-client#483]
|    Q        |   A
|------------ | -----
| Version     | 2.4.2

### Support Question

After upgrading the package from 1.7 to 2.x (2.4.2), our soap requests are broken.
The body of the request is somehow filtered out, and not sent to the endpoint. The only contents in the body is the root tag of the soap request and the xml tag.

For the upgrade, i adjusted the classmap and client/factory. Besides that, there were no code changes.
The upgrade guide also doesnt mention anything specific.

Any clue where this issue might be?

**Comment by veewee** [comment]
Hello,

It's hard to tell you the exact problem with the given information.
First thing that comes to mind is that you need to apply the HTTP settings that were previously provided in the soap options on the PSR-18 HTTP client instead.

If that's not the case, feel free to provide additional information.

**Comment by JoppeDC** [comment]
I was able to resolve the issue by making a change to the WSDL. The WSDL had an endpoint with `http`, instead of `https`. This returns a 302 response, and subsequently when the call was made to the correct endpoint (following the 302), i'm guessing this was seen as invalid and therefore dropped the request body. Not sure where this issue might be related to internally, but i'm guessing its not related directly to the package, rather to the change of the HTTP client. So for me, this issue can be closed.
