### ISSUE TITLE
Nullable types does not generate

### ISSUE THREAD

**Issue by h4kuna** [phpro/soap-client#495]
Hello, I found the generated files does not contains nullable types, but returned values, can be. The provider of wsdl has defined like:
```
<xsd:element name="telefono" type="xsd:string" maxOccurs="1" minOccurs="0"></xsd:element>
```

If attribute minOccurs is "0" it means null.

Result is:
```php
public function getTelefono(): string
{
    return $this->telefono;
}
```

but i expect
```php
public function getTelefono(): ?string
{
    return $this->telefono;
}
```

1. Is possible change behavior on my side?
2. What is right enrollment for nullable type? `xsi:nil="true"`

EDIT:
I try v2.4 and v3.1.1

**Comment by veewee** [comment]
Hello @h4kuna,

You'll need to use version 3 in order for this to work. (version 2 does not support nullable types).
Also make sure that you enabled the `CodeGeneratorEngineFactory` as described in https://github.com/phpro/soap-client/blob/v3.x/UPGRADING.md#v2-to-v3

According to the xsd signature, It should be nullable indeed.
Can you debug what is coming out the WSDL-reader for that specific type?
You can use a CLI command for that:
https://github.com/php-soap/wsdl-reader#console

If the above does not fix your issue, feel free to provide the WSDL and some more information about your code generation configuration. If that's not possible, you can provide the complete complexType that is surrounding this element so that I can check if it's a bug in the wsdl-reader or in this package.

**Comment by h4kuna** [comment]
The [wsdl](https://immobinetagenzie.immobinet.it/webservices/webservicemodagenzia/service.wsdl) is public.
I updated config with `CodeGeneratorEngineFactory` and use version 3.1.1.

Now I get
```
In SchemaReader.php line 1049:
                                                                                                                           
  Can't find type named {http://www.immobinet.it/schema/WebserviceGruppiBundle}#string, at line 157 in https://immobineta  
  genzie.immobinet.it/webservices/webservicegruppi/service.wsdl
```
I don't understand what is wrong...

Here are an optional parameters in stucture `getPrenotazioniResponse`
https://immobinetagenzie.immobinet.it/webservices/webservicemodagenzia/service.wsdl#op.id11

My config file looks like:
```php
$config = [
    "wsdl" => "https://immobinetagenzie.immobinet.it/webservices/webservicemodagenzia/service.wsdl",
    "name" => "Agenzia",
    "namespace" => "App\ChannelManager\ImmobiNet\Soap\Agenzia",
    "documentRoot" => "app/ChannelManager/ImmobiNet/Soap/Agenzia",
];

Config::create()
    ->setEngine($engine = CodeGeneratorEngineFactory::create(
        $config['wsdl'],
        new FlatteningLoader(new StreamWrapperLoader()),
    ))
    ->setTypeDestination($config['documentRoot'] . '/Type')
    ->setTypeNamespace($config['namespace'] . '\\Type')
    ->setClientName($config['name'] . 'Client')
    ->setClientDestination($config['documentRoot'])
    ->setClientNamespace($config['namespace'])
    ->setClassMapDestination($config['documentRoot'] . '/ClassMap')
    ->setClassMapName($config['name'] . 'Classmap')
    ->setClassMapNamespace($config['namespace'] . '\\ClassMap')
    ->addRule(
        new Rules\AssembleRule(
            new Assembler\GetterAssembler(
                new Assembler\GetterAssemblerOptions(),
//                        ->withDocBlocks(false)
//                        ->withReturnType()
            ),
        ),
    )
    ->addRule(
        new Rules\AssembleRule(
            new Assembler\ImmutableSetterAssembler(
                new Assembler\ImmutableSetterAssemblerOptions(),
//                        ->withReturnTypes()
//                        ->withTypeHints()
//                        ->withDocBlocks(false)
            ),
        ),
    )
    ->addRule(
        new Rules\IsRequestRule(
            $engine->getMetadata(),
            new Rules\MultiRule([
                new Rules\AssembleRule(new Assembler\RequestAssembler()),
                new Rules\AssembleRule(
                    new Assembler\ConstructorAssembler(
                        new Assembler\ConstructorAssemblerOptions(),
//                                ->withDocBlocks(false)
//                                ->withTypeHints()
                    ),
                ),
            ]),
        ),
    )
    ->addRule(
        new Rules\IsResultRule(
            $engine->getMetadata(),
            new Rules\MultiRule([
                new Rules\AssembleRule(new Assembler\ResultAssembler()),
            ]),
        ),
    );
```

Thank you for your help

**Comment by veewee** [comment]
Hello @h4kuna,

This seems like a bug in the flattening process. I've created an issue in that repo:
https://github.com/php-soap/wsdl/issues/15

It's gonna take me some time before I can try to provide a fix for this cause of regular work. So feel free to give it a try yourself.

**Comment by veewee** [comment]
@h4kuna I've released a fix for the wsdl package.
Can you try again with the new version?

https://github.com/php-soap/wsdl/releases/tag/1.7.0

I'm able to read the flattened WSDL file with the wsdl-reader package, so the generated code should be spot on!

**Comment by h4kuna** [comment]
Hello, 
the bug `Can't find type named ...` is fixed. 

My question: `Nullable types does not generate` is resolved.

Thank you.

I will create new issue. Because many methods is missing.
