### ISSUE TITLE
Accessing WSDL with port

### ISSUE THREAD

**Issue by arifinreinaldo** [phpro/soap-client#497]
|    Q        |   A
|------------ | -----
| Version     | 3.1.1

Using the factory to pass the WSDL http://example.com:1212/flap/service.asmx?wsdl

### Support Question

When tried to get access the client it keeps accessing to port 80 not the port 1212.

**Comment by veewee** [comment]
@arifinreinaldo Can you give me some more feedback on what you are trying to do code-wise and at which point it fails exactly? 
If you could provide the real WSDL, that would be nice - but I get that some of them are not meant to be shared.

**Comment by arifinreinaldo** [comment]
Hi @veewee , 
currently I manage to to generate the wsdl from the url that is provided by the vendor. In this WSDL they are spesifically using port that is allowed to be accessed. e;g http://example.com:1212/flap/service.asmx?wsdl with port 1212 as the available port. From the documentation I'm following, I call the FlapBarrierClientFactory::factory($wsdl); with the provided url that they gave to me. But when it is time to call the function the wsdl suddenly not calling the example.com:1212 but instead calling the example.com:80.

Phpro\SoapClient\Exception\SoapException: cURL error 28: Failed to connect to example.com port 80 after 75002 ms: Couldn't connect to server (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://example.com/flap/service.asmx in file SoapException.php on line 19

I think maybe the url that is accessed in the function is using the port 80 not the one provided in the WSDL. 
Thank you

Sorry cant provide the wsdl at the moment

**Comment by veewee** [comment]
I understand.
Sadly, I can't do much with the given information. So I guess you'll need to dive into the issue yourself.

**Comment by arifinreinaldo** [comment]
Hi @veewee , 
I have done some reading in the options documentation, turns out i can do with the additional option 
$target_url = example.com:1212?wsdl
$engine = DefaultEngineFactory::create(
            ExtSoapOptions::defaults('target/location/0cc11ad5f73764af932cae46649949d8.wsdl', ['location' => $target_url])
                ->withClassMap(Classmap::getCollection())
        );
        Turns out I can do with this setup, and it accessed the expected URL. If there is other method please let me know. Thanks for creating an intuitive SOAP helper

**Comment by veewee** [comment]
Great that you found a solution.

That sure is an option, but it also means that the endpoint specified in the WSDL is most likely not valid.
Another alternative is to override the host with [an HTTP plugin](https://docs.php-http.org/en/latest/plugins/request-uri-manipulations.html). The end result will be the same though.
