### ISSUE TITLE
Using GuzzleHttp with the plugin

### ISSUE THREAD

**Issue by Olakouns** [phpro/soap-client#511]
|    Q        |   A
|------------ | -----
| Version     | 3.1.2

### Support Question

Hello. 
I'm trying to use the GuzzleHttp client with the plugin. I followed the documentation for the implementation but it doesn't work. I want to add an NTLM authentication layer. Here is the content of my code. If I have misconfigured something, please let me know. thanks

`

        $client = new \GuzzleHttp\Client([
                    'curl' => [
                        CURLOPT_HTTPAUTH => CURLAUTH_NTLM,
                        CURLOPT_USERPWD => 'user:pass'
                    ]
                ]);

        $transport = Psr18Transport::createForClient(new PluginClient($client));

        $engine = DefaultEngineFactory::create(
            ExtSoapOptions::defaults($wsdl, [])
                ->withClassMap(MafSoapClientClassmap::getCollection()),
            $transport
        );

        $eventDispatcher = new EventDispatcher();
        $caller = new EventDispatchingCaller(new EngineCaller($engine), $eventDispatcher);

        return new MafSoapClient($caller);`

**Comment by veewee** [comment]
Can you specify "it does not work"?

**Comment by Olakouns** [comment]
Yes . 
the integration of GuzzleHttp work perfectly with the plugin. But that’s not talking NTLM information account. 
I already try Guzzle separately and it works fine with the same configuration.

**Comment by veewee** [comment]
Not sure what is going wrong exactly : The configuration sure looks right... 
Can you specify where it goes wrong exactly? 

If you are loading a remote WSDL file that is also behind NTLM protection, you might need to configure this as well:
https://github.com/php-soap/psr18-transport?tab=readme-ov-file#psr18loader
https://github.com/php-soap/ext-soap-engine?tab=readme-ov-file#extsoapoptions

(You'll need to combine the psr18 WSDL loader with an ext-soap WSDL provider - which are 2 related but different things; The last link contains an example to do that)

**Comment by Olakouns** [comment]
Hello. I followed the instructions and it works very well. Thank you very much and thank you for developing the plugin.  :star_struck:

Here is the code: 

`            
           

            $client = new \GuzzleHttp\Client([
                'curl' => [
                    CURLOPT_HTTPAUTH => CURLAUTH_NTLM,
                    CURLOPT_USERPWD => 'user:pass'
                ]
            ]);

            $transport = Psr18Transport::createForClient(new PluginClient($client));

            $engine = DefaultEngineFactory::create(
                ExtSoapOptions::defaults($wsdl, [])
                    ->disableWsdlCache()
                    ->withClassMap(MafSoapClientClassmap::getCollection())
                    ->withWsdlProvider(new TemporaryWsdlLoaderProvider(
                        new FlatteningLoader(Psr18Loader::createForClient(new PluginClient($client))),
                        new Md5Strategy()
                    )),
                $transport
            );

            $eventDispatcher = new EventDispatcher();
            $caller = new EventDispatchingCaller(new EngineCaller($engine), $eventDispatcher);`

**Comment by veewee** [comment]
No problem :)

---

If you like the work we provide here: [feel free to sponsor us](https://opencollective.com/php-soap).
