### ISSUE TITLE
Typed property ... must not be accessed before initialization

### ISSUE THREAD

**Issue by RiseAndCry** [phpro/soap-client#513]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 3.1.2

#### Summary

When using auto generated classes for response handling, i get this error:
`Typed property ...\BaseReturnType::$ReturnCode must not be accessed before initialization`

#### Current behavior

Accessing property which has a value set does not work.

#### How to reproduce

Response class (auto generated):
```
<?php
declare(strict_types=1);

namespace ...\Type;

abstract class BaseReturnType
{
    private bool $IsOk;

    private bool $IsWarninig;

    private bool $IsError;

    private int $ReturnCode;

    private ?string $ReturnText = null;

    public function getIsOk(): bool
    {
        return $this->IsOk;
    }

    public function withIsOk(bool $IsOk): static
    {
        $new = clone $this;
        $new->IsOk = $IsOk;

        return $new;
    }

    public function getIsWarninig(): bool
    {
        return $this->IsWarninig;
    }

    public function withIsWarninig(bool $IsWarninig): static
    {
        $new = clone $this;
        $new->IsWarninig = $IsWarninig;

        return $new;
    }

    public function getIsError(): bool
    {
        return $this->IsError;
    }

    public function withIsError(bool $IsError): static
    {
        $new = clone $this;
        $new->IsError = $IsError;

        return $new;
    }

    public function getReturnCode(): int
    {
        return $this->ReturnCode;
    }

    public function withReturnCode(int $ReturnCode): static
    {
        $new = clone $this;
        $new->ReturnCode = $ReturnCode;

        return $new;
    }

    public function getReturnText(): ?string
    {
        return $this->ReturnText;
    }

    public function withReturnText(?string $ReturnText): static
    {
        $new = clone $this;
        $new->ReturnText = $ReturnText;

        return $new;
    }
}
```

1. Call soap client that will return the aforementioned response
2. Try calling `getReturnCode()` on it - it throws `Typed property ...\BaseReturnType::$ReturnCode must not be accessed before initialization` error.

When i debug this BaseReturnType (after executing request), i get such a response (partial):
<img width="152" alt="Screenshot 2024-05-07 at 18 14 52" src="https://github.com/phpro/soap-client/assets/11545302/8ab8c9d7-497d-47fd-86c1-be25611eafa8">
(Bankruptcies comes from SubClass)

which means the values have been set (as expected). 

#### Expected behavior

Calling `getReturnCode()` should return the value instead of throwing an error:

___

I noticed a few weird things though:
1. if instead of calling `getReturnCode()` i directly access the property via `$returnType->ReturnCode` - it works. But it's a private variable, so... ehh ??? no `Cannot access private property ...` error ? i'm really confused.
2. if i add a default value to `ReturnCode` (999) - it shows up as an additional variable (both in BaseReturnType and in SubClass) ???
<img width="151" alt="Screenshot 2024-05-07 at 18 12 45" src="https://github.com/phpro/soap-client/assets/11545302/fce3b07b-c84b-4ed8-ab41-466558467692">

**Comment by veewee** [comment]
Hello There,

Can you validate if the error still exists when you change the property visibility to `protected` on all classes?

I have a gut feeling it is related to the behaviour decribed here:
https://github.com/veewee/reflecta/issues/5

SInce the property is declared private in a child-class, PHP's soap-client will set a public property on the parent type instead. In that case, the error makes sense.

**Comment by RiseAndCry** [comment]
Yeap, `protected` properties work !
Thank you very much, this saved me quite a bit of time troubleshooting :)

And thanks for your contributions and such a fast response !

**Comment by veewee** [comment]
No problem :)

---

If you like the work we provide here: [consider sponsoring us](https://opencollective.com/php-soap).

**Comment by veewee** [comment]
Hello there @RiseAndCry ,

I wanted to get back to this issue:
We are finishing up v4 of the soap-client package which uses a new encoding system internally.
With this new system, you should be able to get around this issue more easily.

We are eager to receive some early feedback on this new release.
If you got some time, feel free to play around with the alpha version:


* Release: https://github.com/phpro/soap-client/releases/tag/4.0.0-alpha1
* Discussion: https://github.com/phpro/soap-client/discussions/527
