### ISSUE TITLE
Issue when I'm trying to execute the wizzard - error of Allowed memory. Size

### ISSUE THREAD

**Issue by ccievoiceoks** [phpro/soap-client#517]
|    Q        |   A
|------------ | -----
| Version     | 3.2

### Support Question

Hello ,

I have discovered your package to play with SOAP API .
I want to test it with the Cisco CUCM AXL SOAP message .

so I have installed it for the first time and I have launched the wizzard to follow the documentation. 
But after the  creation soap-client.php file , I'm receiving a Fatal Error 

Here is the message that I'm receiving
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 4096 bytes) in /Users/xxx/Herd/trial/vendor/veewee/xml/src/Xml/Dom/Xpath/Locator/query.php on line 26

Don't know what I missed

Many thanks

**Comment by veewee** [comment]
Hello,

Could you provide the WSDL to me?
You might need to increase PHP's memory limit though:

https://www.php.net/manual/en/ini.core.php#ini.memory-limit

**Comment by ccievoiceoks** [comment]
Hi

Thanks I will check this evening by increasing  the memory limit.

Here are my files with the schema
[axlsqltoolkit.zip](https://github.com/phpro/soap-client/files/15337708/axlsqltoolkit.zip)
You can found it in the schema folder 

Thanks

**Comment by ccievoiceoks** [comment]
Many thanks :)

By increasing the memory , it has worked .

It has generated the classmap,the client and the ClientFactory . So now I need to continue to read the documentation to see how to use it effectively in my project .
Thank you so much for pointing me in the good direction
👍

**Comment by veewee** [comment]
Glad you got it working.

Just wanted to let you know:

I've quickly looked at the WSDL and it looks like the WSDL flattening loader is not able to import the XSD types correctly.
Therefore, no types will be generated at this moment - which is a bug.

Reported it here:
https://github.com/php-soap/wsdl/issues/19

Until this is fixed, you won't be able to get the types generated.

**Comment by veewee** [comment]
Just a small update : it should be fixed right now:

https://github.com/php-soap/wsdl/releases/tag/1.9.0

```
 [INFO] Loading "cisco-axl-api.wsdl"...

 [INFO] Types:


  > http://www.cisco.com/AXL/API/15.0:AXLError
  > http://www.cisco.com/AXL/API/15.0:XSipProfile
  > http://www.cisco.com/AXL/API/15.0:externalPresentationInfo
  > http://www.cisco.com/AXL/API/15.0:presentationInfo
  > http://www.cisco.com/AXL/API/15.0:AddSipProfileReq
  > http://www.cisco.com/AXL/API/15.0:UpdateSipProfileReq
  > http://www.cisco.com/AXL/API/15.0:externalPresentationInfo
  > http://www.cisco.com/AXL/API/15.0:presentationInfo
  > http://www.cisco.com/AXL/API/15.0:GetSipProfileReq
  > http://www.cisco.com/AXL/API/15.0:GetSipProfileRes
  > http://www.cisco.com/AXL/API/15.0:return
  > http://www.cisco.com/AXL/API/15.0:ListSipProfileReq
  > http://www.cisco.com/AXL/API/15.0:searchCriteria
  > http://www.cisco.com/AXL/API/15.0:ListSipProfileRes
  > http://www.cisco.com/AXL/API/15.0:return
  > http://www.cisco.com/AXL/API/15.0:GetSipProfileOptionsReq
  > http://www.cisco.com/AXL/API/15.0:GetSipProfileOptionsRes
  > http://www.cisco.com/AXL/API/15.0:return
  > http://www.cisco.com/AXL/API/15.0:XSipTrunkSecurityProfile
  > http://www.cisco.com/AXL/API/15.0:AddSipTrunkSecurityProfileReq
  > http://www.cisco.com/AXL/API/15.0:UpdateSipTrunkSecurityProfileReq
  > http://www.cisco.com/AXL/API/15.0:GetSipTrunkSecurityProfileReq
  > http://www.cisco.com/AXL/API/15.0:GetSipTrunkSecurityProfileRes
  > http://www.cisco.com/AXL/API/15.0:return
  > http://www.cisco.com/AXL/API/15.0:ListSipTrunkSecurityProfileReq
  > http://www.cisco.com/AXL/API/15.0:searchCriteria
  > http://www.cisco.com/AXL/API/15.0:ListSipTrunkSecurityProfileRes
  > http://www.cisco.com/AXL/API/15.0:return
  > http://www.cisco.com/AXL/API/15.0:XTimePeriod
  > http://www.cisco.com/AXL/API/15.0:AddTimePeriodReq
  > http://www.cisco.com/AXL/API/15.0:UpdateTimePeriodReq
  > http://www.cisco.com/AXL/API/15.0:GetTimePeriodReq
  > http://www.cisco.com/AXL/API/15.0:GetTimePeriodRes
  > http://www.cisco.com/AXL/API/15.0:return
  > http://www.cisco.com/AXL/API/15.0:ListTimePeriodReq
  > http://www.cisco.com/AXL/API/15.0:searchCriteria
  > http://www.cisco.com/AXL/API/15.0:ListTimePeriodRes
  > http://www.cisco.com/AXL/API/15.0:return
  > http://www.cisco.com/AXL/API/15.0:XTimeSchedule
  > http://www.cisco.com/AXL/API/15.0:members
  > http://www.cisco.com/AXL/API/15.0:AddTimeScheduleReq
  > http://www.cisco.com/AXL/API/15.0:UpdateTimeScheduleReq

....
```
