### ISSUE TITLE
[Question] Is there a way to configure xmlns:SOAP-ENV? 

### ISSUE THREAD

**Issue by KDederichs** [phpro/soap-client#520]
|    Q        |   A
|------------ | -----
| Version     | 2.7.0

### Support Question

Is there a built in way to change the `xmlns:SOAP-ENV` namespace?
By default it generates with `http://schemas.xmlsoap.org/soap/envelope/` but the SOAP Server I talk to expects `http://www.w3.org/2003/05/soap-envelope` and is throwing errors when you do not use it.

So I was wondering if there's a convenient way to change this or if I need to build my own middleware to manipulate this :)

**Comment by veewee** [comment]
Hello there,

It seems like you are sending a SOAP 1.1 envelope to a SOAP 1.2 webservice.
You might need to specify the correct SOAP version you want to use.

Depending on your configuration, you might need to specify this in a few places:

In the generated client factory:

```php
ExtSoapOptions::defaults($wsdl, [
    'soap_version' => \SOAP_1_2,
])
```

In the code generator configuration:

```php
->setEngine($engine = CodeGeneratorEngineFactory::create(
    $wsdl,
    preferredSoapVersion: SoapVersion::SOAP_12
))
```

**Comment by KDederichs** [comment]
That did the trick, thanks!
