### ISSUE TITLE
customize clientfactory creation config

### ISSUE THREAD

**Issue by ulfw** [phpro/soap-client#521]
Hi, 

maybe I misunderstand the concept or just how to do it ;-)

I want to customize the generation of the Clientfactory the way, that I want to use a a wsdl provider.

example:

the provider:

        $options = [];
        if($_ENV['PROXY_HOST']) $options["CURLOPT_PROXY"] = $_ENV['PROXY_HOST'];
        if($_ENV['PROXY_USERPASS']) $options["CURLOPT_PROXYUSERPWD"] = $_ENV['PROXY_USERPASS'];
        $loader = new HttpWsdlLoader(
            new PluginClient( new Client(Psr17FactoryDiscovery::findResponseFactory(), Psr17FactoryDiscovery::findStreamFactory(), $options), []),
            Psr17FactoryDiscovery::findRequestFactory()
        );
        $provider = new CachedWsdlProvider($loader, new Filesystem(), sys_get_temp_dir());
        #$provider = $provider->forcePermanentDownloads();
        return $provider;

the context:

        return stream_context_create([
            'ssl' => [
                // set some SSL/TLS specific options
                'verify_peer' => false,
                'verify_peer_name' => false,
                'allow_self_signed' => true
            ]
        ]);

the to be generated clientfactory

    public static function factory(string $wsdl) : AccountServiceClient
    {
        $handler = someHowGetHandler();
        $provider = someHowGetProvider();
        $context = someHowGetContext();

        $engine = ExtSoapEngineFactory::fromOptionsWithHandler(
            ExtSoapOptions::defaults($wsdl, [
                'location' => $wsdl,
                'stream_context' => $context
            ])
                ->withClassMap(AccountServiceClassmap::getCollection())
                ->withWsdlProvider($provider),
            $handler
        );
        $eventDispatcher = new EventDispatcher();

        return new AccountServiceClient($engine, $eventDispatcher);
    }

How should my config file look like to generate the clientfactory like this

Thanks for help

**Comment by veewee** [comment]
Hello,

The generated factory is there to give you a starting point. It's not really meant to be regenerated but rather to be personalised with how you want to configure the client.

Do note that the stream-context won't be used if you are using a HTTP based transport.

**Comment by ulfw** [comment]
Thank you fo your fast reply.
So if I have to create - like in this case - 45 web service classes, I generate them and then modify to client factories all the same way.
Or do you have an advice how I can make this modification "more centralized" ?

**Comment by veewee** [comment]
You could always create your own code generator for this specific use-case.
The source can be found here:

* https://github.com/phpro/soap-client/blob/v3.x/src/Phpro/SoapClient/Console/Command/GenerateClientFactoryCommand.php
*  https://github.com/phpro/soap-client/blob/v3.x/src/Phpro/SoapClient/CodeGenerator/ClientFactoryGenerator.php
