### ISSUE TITLE
Generator doesn't initialise nullable values resulting in crash on access

### ISSUE THREAD

**Issue by KDederichs** [phpro/soap-client#522]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 3.3.0

#### Summary

The DTOs generated by the wizard don't initialise optional fields with null, resulting in errors when trying to access them.

#### Current behavior

Currently it will produce something like this:
```php
private ?array $foo;

public function getFoo(): ?array
{
   return $this->foo;
}
```

which will then crash while trying to call getFoo()

#### How to reproduce

Generate from any WSDL with optional response fields.

#### Expected behavior

It should generate something like this, with initialised values:
```php
private ?array $foo = null;

public function getFoo(): ?array
{
   return $this->foo;
}
```

That way calling getFoo() will not crash with an `Typed property App\Azh\Type\Bar::$foo must not be accessed before initialization` error.

**Comment by veewee** [comment]
Can you verify you are on the latest version?
This should be fixed in last release:

- https://github.com/phpro/soap-client/pull/516/files
- https://github.com/phpro/soap-client/releases/tag/3.3.0

**Comment by KDederichs** [comment]
Yup fixed it, sorry thought I did it with that already
