### ISSUE TITLE
Using different bindings

### ISSUE THREAD

**Issue by flodi** [phpro/soap-client#535]
### Support Question

I have WSDL like the one attached, and I have to use the operation on both binding. How can I specifiy the binding?
[wsAccesso.txt](https://github.com/user-attachments/files/16443368/wsAccesso.txt)

**Comment by veewee** [comment]
Hello @flodi,

I'm a bit confused about your question. Can you give me some more detail on what you are trying to achieve exactly?

**Comment by veewee** [comment]
Closing this for now. Feel free to provide additional details or reopen.
