### ISSUE TITLE
Empty namespace inside xml request

### ISSUE THREAD

**Issue by jjmonagas** [phpro/soap-client#54]
I need to add this code inside 'Phpro\SoapClient\Soap\SoapClient.php' to remove empty namesapaces like xmlns:ns1="" 

```
public function __doRequest($request, $location, $action, $version, $oneWay = 0)
    {
        //my code - begin
        if (preg_match('/xmlns:ns1=""/', $request)) {
            $request = preg_replace('/xmlns:ns1=""/', '', $request, 1);
            $request = preg_replace('/ns1:/', '', $request);
        }
        //my code - end
      $request = new SoapRequest($request, $location, $action, $version, $oneWay);
      $response = $this->handler->request($request);
      ...
```

Is it possible to make this in a proper way? Via configuration for example. I don't want to change the original code.

Thanks!

**Comment by veewee** [comment]
Hi @jjmonagas,

Thanks for the question. It is always possible to create your own Middleware to do this kind of things. More information: https://github.com/phpro/soap-client/blob/master/docs/middlewares.md#creating-your-own-middleware

Feel free to contribute if you think this is a general problem.

**Comment by jjmonagas** [comment]
Thanks @veewee 
I will create my own Middleware. I will let you know if it works.

**Comment by jjmonagas** [comment]
Finally, creating my own Middleware (EmptyNamespaceMiddleware) was the solution:

`
    public function beforeRequest(callable $handler, RequestInterface $request, array $options)
    {
        $content = $request->getBody()->getContents();

        if (preg_match('/xmlns:ns1=""/', $content)) {
            $content = preg_replace('/xmlns:ns1=""/', '', $content, 1);
            $content = preg_replace('/ns1:/', '', $content);
        }

        $xml = new \DOMDocument();
        $xml->loadXML($content);
        $xmlSoap = new SoapXml($xml);

        $request = $request->withBody($xmlSoap->toStream());

        return $handler($request, $options);
    }
`

And GuzzleHttp/Client configuration:

`
        $clientFactory = new ClientFactory('soapClientClass');
        $soapOptions = ['cache_wsdl' => WSDL_CACHE_NONE];
        $guzzleClient = new Client();
        $clientBuilder = new ClientBuilder($clientFactory, 'wsdl', $soapOptions);
        $clientBuilder->withHandler(GuzzleHandle::createForClient($guzzleClient));
        $clientBuilder->addClassMap(new ClassMap('Input', Input::class));
        $clientBuilder->addClassMap(new ClassMap('EX_MESSA', EX_MESSA::class));
        $clientBuilder->addClassMap(new ClassMap('Response', Response::class));
        $clientBuilder->addMiddleware(new EmptyNamespaceMiddleware());
        $clientBuilder->addMiddleware(new BasicAuthMiddleware('username', 'password'));

        $clientBuilder->build();
`

I don't know if it is a general problem, but I got this ERROR when I tried to 'loadXml($stream->getContents())' with empty namespace:

> Warning: DOMDocument::loadXML(): xmlns:ns1: Empty XML namespace is not allowed in Entity, line: 2

So I think that the problem is at the SOAP Service when they generate XML without namespace.

**Comment by veewee** [comment]
Hi @jjmonagas,

This is invalid XML being returned by the server and should be fixed on the server instead of the client.
I'll close this issue since this is working for you, but you might want to contact the SOAP service provider.

**Comment by jjmonagas** [comment]
Ok, Thanks again! I will contact the provider.
