### ISSUE TITLE
codegen: UseExtender namespace bug

### ISSUE THREAD

**Issue by rauanmayemir** [phpro/soap-client#544]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 4.0.0-alpha1

#### Summary

When generating type classes that extend others, `ExtendAssember` chains into `UseAssembler` to import the extending class.
`UseAssember` then checks if they are in the same namespace in `usesTheSameNamespace`. However, there is a bug that it doesn't 'normalize' classnames to get rid of trailing `\` comparing e.g `\Gen\Client\Type` and `Gen\Client\Type`. Because of that all of the generated type bindings currently have unnecessary import uses.

**Comment by veewee** [comment]
Fixed in https://github.com/phpro/soap-client/pull/547
