### ISSUE TITLE
Generate the same method names in v3 as in v2

### ISSUE THREAD

**Issue by BackEndTea** [phpro/soap-client#545]
|    Q        |   A
|------------ | -----
| Version     | 3.3.0

I'm not sure if this is possible (otherwise, please consider this a feature request).

### Support Question

I'm currently in the process of upgrading this library from v2 to v3. Unfortunately, in some places the resulting objects get passed around, without parameter/return types being used.
This means its hard to track where in the code base the generated classes are being called.

Is it possible to upgrade to v3, but keep all method names the same when generating the code? This would save me from having to manually figure out where these methods are being called.

e.g. in v2, a method would be present on a response class called `getList_GetByUserResult`. In v3 it is called `getListGetByUserResult`. (no underscores).

**Comment by veewee** [comment]
Hello,

It has been changed in v3 intentionally.
See the optimization in https://github.com/phpro/soap-client/pull/478

**Comment by BackEndTea** [comment]
Thats fair, i'll just manually search for these updated method calls then.
