### ISSUE TITLE
Dependencies are too restrictives

### ISSUE THREAD

**Issue by gsouf** [phpro/soap-client#6]
Hi,

Dependencies of the library are too restrictive.

For instance you restrict symfony/filesystem to version ~2.3. If someone already uses <2.3 or >2.3 (special mention for >=3.0) in it's project, it's not possible to use the soap client (it's my case).

Symfony versioning is smart enough and I recommend you to provide a wider version range for deps.

**Comment by veewee** [comment]
Hello @gsouf,

Thanks for reporting! I've updated the dependencies. Now all versions >2.3 are supported.
We are not planning to support older versions.

**Comment by gsouf** [comment]
👍
