### ISSUE TITLE
SoapClient::__setCookie

### ISSUE THREAD

**Issue by amaccis** [phpro/soap-client#69]
Hi guys.
Is there a way to set a cookie (http://php.net/manual/en/soapclient.setcookie.php)?
I guess so, since I did not find a method as applySoapHeaders().
Thanks,
A.

**Comment by veewee** [comment]
Hi @amaccis,

Since cookies are sent in the HTTP request headers, it's probably best to use an HTTP Middleware for that purpose instead of adding cookies to the client.

More info can be found here: https://github.com/phpro/soap-client/blob/master/docs/middlewares.md

**Comment by amaccis** [comment]
Thank you! I created a Middleware for cookies and I got what I needed.
