### ISSUE TITLE
Best practice for multiple WSDL files?

### ISSUE THREAD

**Issue by kostajh** [phpro/soap-client#81]
First, thanks for this amazing package and your hard work in putting it together!

Sorry if this is an obvious question, but I'm fairly new to the SOAP world. I am integrating with a service that has about 8 different WSDL files. What would be the best way to structure my client class? 

From the [usage doc](https://github.com/phpro/soap-client/blob/master/docs/usage.md) it seems like you'd want to have multiple clients, one per WSDL file, and have a wrapper client class that can make use of any of them.

**Comment by janvernieuwe** [comment]
Yes, when I work with multiple WDSL's in for the same service, I make multiple clients.

In my last use case they did quite different things, so creating a wrapper was not needed there for me.
But if they do, a wrapper class seems like a good idea to me.

**Comment by mheki** [comment]
Yeah, I'm also using multiple clients 👍

**Comment by kostajh** [comment]
Writing a wrapper class worked out well. I think this could be closed?

**Comment by veewee** [comment]
Hi @kostajh,

Lets keep this one open so that it can be used to add documentation about the issue.
