### ISSUE TITLE
Issues with PHP-VCR

### ISSUE THREAD

**Issue by kostajh** [phpro/soap-client#84]
I'm working on integrating php-vcr with my project, but running into difficulties. This is the message I get:

```
You can only add handlers if the SoapClientFactory is returning an instance of Phpro\SoapClient\Soap\SoapClient. Got: VCR\Util\SoapClient
 /Users/kostajh/src/example/drupal/sites/all/vendor/phpro/soap-client/src/Phpro/SoapClient/ClientBuilder.php:199
 /Users/kostajh/src/example/drupal/sites/all/modules/custom/example_integration/src/Api/Client/IntegrationClient.php:180
 /Users/kostajh/src/example/drupal/sites/all/modules/custom/example_integration/src/Api/Client/IntegrationClient.php:87
 /Users/kostajh/src/example/drupal/sites/all/modules/custom/example_integration/tests/src/IntegrationTestBase.php:51
 /Users/kostajh/src/example/drupal/sites/all/modules/custom/example_integration/tests/src/Integration/CodeUnitGuestInfoTest.php:22
```

I'm using PHPUnit 6 with the latest 3.0.0 release of php-vcr-listeners project. Line 180 of `IntegrationClient.php` is calling `$clientBuilder->build()` on a client object I've built up.

Any ideas?

**Comment by veewee** [comment]
Hi @kostajh,

The trick is to use the curl library hook instead of the soap hook if you are using the GuzzleClient.

```php
\VCR\VCR::configure()->enableLibraryHooks(['curl_rewrite']);
\VCR\VCR::turnOn();
```

**Comment by kostajh** [comment]
Hmm, so if I set it to `curl_rewrite` I get `PHP Fatal error:  Uncaught InvalidArgumentException: Library hooks don't exist: curl_rewrite`. Based on [the docs](http://php-vcr.github.io/documentation/libraryhooks/) it seems like just specifying `curl` should be enough. I'm wondering if it's an issue with the NTLM authentication on the server I'm interacting with. Debugging it now...

**Comment by veewee** [comment]
Oh yeah, I've must have copied it from an older package version of VCR :) it should do the trick ...

**Comment by kostajh** [comment]
`curl` isn't working though. It seems like the problem is that the NTLM middleware either isn't getting set for the Wsdl provider, or when the client is built. Here's what my code looks like, which works perfectly when not using PHP VCR:

``` php
  $clientFactory = new ClientFactory(GuestInfo::class);
    $wsdl = $this->baseUrl . 'Codeunit/GuestInfo';
    $clientBuilder = new ClientBuilder($clientFactory, $wsdl, $this->soapOptions);
    $class_map_collection = TRUNCATED;
    $clientBuilder->withClassMaps($class_map_collection);
    $dispatcher = new EventDispatcher();
    $dispatcher->addSubscriber(new LogPlugin($this->logger));
    $clientBuilder->withEventDispatcher($dispatcher);
    $ntlm_middleware = new NtlmMiddleware($this->user, $this->password);
    $clientBuilder->addMiddleware($ntlm_middleware);
    $guzzleClient = new GuzzleClient();
    $provider = new GuzzleWsdlProvider($guzzleClient, new Filesystem());
    $provider->addMiddleware($ntlm_middleware);
    $clientBuilder->withWsdlProvider($provider);
    $handler = new GuzzleHandle($guzzleClient, new Psr7Converter(new RequestFactory(), new StreamFactory()), new CollectLastRequestInfoMiddleware());
    $clientBuilder->withHandler($handler);
    $this->CodeUnitGuestInfo = $clientBuilder->build();
```

**Comment by kostajh** [comment]
In the debugger, I can see that the NTLM middleware is added to the WSDL provider, hard to see if it is also added to the client.

**Comment by kostajh** [comment]
If I use a local WSDL provider then I get this error:

```
SoapClient::__doRequest() returned non string value
 /Users/kostajh/src/omega/drupal/sites/all/vendor/phpro/soap-client/src/Phpro/SoapClient/Exception/SoapException.php:19
 /Users/kostajh/src/omega/drupal/sites/all/vendor/phpro/soap-client/src/Phpro/SoapClient/Client.php:105
 /Users/kostajh/src/omega/drupal/sites/all/modules/custom/omega_cenium/src/Api/Client/CodeUnit/GuestInfo.php:19
 /Users/kostajh/src/omega/drupal/sites/all/modules/custom/omega_cenium/tests/src/Integration/CodeUnitGuestInfoTest.php:35
```
I'm guessing the problem is not with this package or with PHP-VCR but rather the response data coming back from the server. With some requests it responds with a 401 unauthorized but then sets "200 OK" in the message body.

**Comment by kostajh** [comment]
Alright, so here's what I've had to do to get this working for a SOAP service that uses NTLM.

1. Comment out these lines in `build()` on ClientBuilder.php in the phpro/soap-client project

``` php
        if ($this->handler && !$soapClient instanceof SoapClient) {
            throw new InvalidArgumentException(sprintf(
                'You can only add handlers if the SoapClientFactory is returning an instance of %s. Got: %s',
                SoapClient::class,
                get_class($soapClient)
            ));
        }

        if ($this->handler) {
            $soapClient->setHandler($this->handler);
        }
```

Otherwise I get this error `Phpro\SoapClient\Exception\InvalidArgumentException: You can only add handlers if the SoapClientFactory is returning an instance of Phpro\SoapClient\Soap\SoapClient. Got: VCR\Util\SoapClient`

2. Set this configuration in my PHPUnit bootstrap file:

``` php
\VCR\VCR::configure()
  ->enableLibraryHooks(['curl']);
```

3. Hack the CurlHelper and HttpClient files in `php-vcr` to use NTLM curl options (next step is getting a cleaner way to configure this and submitting a PR to the `php-vcr` team)

So, I guess from this project, the only thing I need to figure out is an alternative to the issue in item 1 above (`$this->handler && !$soapClient instanceof SoapClient`). Any thoughts on that?

**Comment by veewee** [comment]
Since php-vcr is mocking the SoapClient, there is something wrong other the php-vcr config. You ONLY WANT curl to be locked. Did you turnOn() before you've added the config line?

**Comment by kostajh** [comment]
/facepalm

That was the problem. First configure, _then_ turn on! I'm still running into a few oddities so I'll leave this open until I can follow up next week, if that's alright. Tanks for your help!

**Comment by janvernieuwe** [comment]
Cleaning up older issues, feel free to create a new one if this issue still persists for you.
