### ISSUE TITLE
Order of generating Classes / Dependencies

### ISSUE THREAD

**Issue by tknuppe** [phpro/soap-client#92]
Hi there
For realizing Type-Extension I need to extend a SOAP class from another (the generator doesn't seem to do it by itself). At the moment I'm working on expanding the Constructor- and the JsonSerializable Assemblers to handle extended classes. That seems to work quite well. I will commit it soon.
The problem that I have is that the ExtendAssembler can't extend from classes that are not built yet. This is understandable. So is it possible to determine the order of the classes to be generated? I can run the code generator twice but that is quite ugly. It would be great if someone could implement something like a priority list or dependency. Any ideas?

Regards
Thomas

**Comment by veewee** [comment]
Hi @tknuppe,

Some questions:
- Can you tell me more about your use-case?
-Are you talking about XSD complex types that extend a different complex type? (I am not sure how ext-soap handles these.)
- Can you provide me a WSDL for this?

The ExtendAssembler was not created for this purpose but for extending an existing class to e.g. provide ways to place collection code in an abstract class.

I would prefer to keep both the constructor and jsonserializeable they way they are in this package. Unless you have a very common use-case.

**Comment by tknuppe** [comment]
Yes, a complex type extending another complex type. Sorry I cannot give you the WSDL but I could try to give you an excerpt:

`
<xs:complexType name="MarkenAuftrag">
<xs:complexContent mixed="false">
<xs:extension base="tns:BasisAuftrag">
<xs:sequence/>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:element name="MarkenAuftrag" nillable="true" type="tns:MarkenAuftrag"/>
<xs:complexType name="BasisAuftrag">
<xs:sequence>
<xs:element minOccurs="0" name="Auftragsnummer" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="Eingangsdatum" nillable="true" type="xs:dateTime"/
</xs:sequence>
</xs:complexType>
<xs:element name="BasisAuftrag" nillable="true" type="tns:BasisAuftrag"/>
`

What if I edit the constructor and jsonserializable assember and implement a switch to turn the function on (off by default)? I just call the parent __construct and jsonSerialize functions to handle the case. You can decide when I create the pull request. I don't want to force you into this. It could be useful for others, too.

The only other way for me is to use a fork for the rest of the project lifetime :(

**Comment by veewee** [comment]
You could also create a custom assembler inside your project ;)
I'll need a WSDL to see how ext-soap parses this exactly.

**Comment by tknuppe** [comment]
Okay, then I will keep it for now. Actually I don't know if it works. I'm in the middle of developing. The Assemblers are now ready. I have to use the SOAP functions and then I will see if it works.
Thanks for the hint to put the Assemblers into my project. That should do it.

**Comment by tknuppe** [comment]
Update: Doesn't work. I needed to build a static SoapType for that cases. The idea with extending the construct and jsonSerialize functions was good but the SOAP-XML could not be built properly.
